import _ from "lodash";
import { DataValue, DataValueNumberSingle, DataValueStore, DataValueTextMultiple } from "../entities/DataValue";
import { DataValueRepository, DataElementRefType } from "../repositories/DataValueRepository";
import { Row } from "../../../webapp/reports/autogenerated-forms/GridWithTotalsViewModel";

export class ApplyToAllUseCase {
    constructor(private dataValueRepository: DataValueRepository) {}

    async execute(
        store: DataValueStore,
        dataValue: DataValueTextMultiple,
        __: DataElementRefType[],
        rows: Row[]
    ): Promise<DataValue[]> {
        const onlyRowWithValues = _(rows)
            .map(row => {
                const suma = row.items.reduce((acum, item) => {
                    if (item.dataElement) {
                        const de = store.get(item.dataElement, {
                            period: dataValue.period,
                            orgUnitId: dataValue.orgUnitId,
                            categoryOptionComboId: dataValue.categoryOptionComboId,
                        }) as DataValueNumberSingle;
                        acum += de.value || "";
                    }
                    return acum;
                }, "");
                return suma.length > 0 ? row.items.find(x => x.column.isSourceType) : undefined;
            })
            .compact()
            .value();

        const { updatedDataValues, sourceTypeToUpdate } = _(onlyRowWithValues).reduce(
            (acc, sourceCol) => {
                if (sourceCol.dataElement) {
                    const de = store.get(sourceCol.dataElement, {
                        period: dataValue.period,
                        orgUnitId: dataValue.orgUnitId,
                        categoryOptionComboId: dataValue.categoryOptionComboId,
                    }) as DataValueTextMultiple;
                    return {
                        updatedDataValues: acc.updatedDataValues.concat({
                            ...de,
                            values: dataValue.values,
                        }),
                        sourceTypeToUpdate: acc.sourceTypeToUpdate.concat({
                            id: sourceCol.dataElement.id,
                            name: sourceCol.dataElement.name,
                        }),
                    };
                }
                return acc;
            },
            { updatedDataValues: [] as DataValueTextMultiple[], sourceTypeToUpdate: [] as DataElementRefType[] }
        );
        await this.dataValueRepository.applyToAll(dataValue, sourceTypeToUpdate);
        return updatedDataValues;
    }
}
