import _ from "lodash";
import { getValueAccordingType } from "../../../webapp/reports/autogenerated-forms/hooks/useApplyRules";
import { Id } from "../entities/Base";
import { CompulsoryDataValue } from "../entities/CompulsoryDataValue";
import { DataValue, DataValueStore } from "../entities/DataValue";
import { DataValueRepository } from "../repositories/DataValueRepository";

export class SaveDataFormValueUseCase {
    constructor(private dataValueRepository: DataValueRepository) {}

    async execute(
        store: DataValueStore,
        dataValue: DataValue,
        compulsoryDataValues: CompulsoryDataValue[],
        dataSetId: Id
    ): Promise<DataValue> {
        const existingDataValue = store.get(dataValue.dataElement, dataValue);
        if (_.isEqual(existingDataValue, dataValue) && dataValue.type !== "FILE") {
            return dataValue;
        } else {
            const isCompulsory = compulsoryDataValues.find(
                cdv =>
                    cdv.dataElementId === dataValue.dataElement.id &&
                    cdv.categoryOptionComboId === dataValue.categoryOptionComboId
            );

            const value = getValueAccordingType(dataValue);

            const isEmpty = _.isNil(value) || value.toString().trim() === "";

            const dataValueWithUpdate = await this.dataValueRepository.save(dataValue, dataSetId);

            return {
                ...dataValueWithUpdate,
                categoryOptionComboId: dataValue.dataElement.cocId || dataValue.categoryOptionComboId,
                isRequired: isCompulsory ? isEmpty : false,
            };
        }
    }
}
