/// <reference types="vitest/config" />
import { fileURLToPath } from "node:url";
import { defineConfig, loadEnv, Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { viteSingleFile } from "vite-plugin-singlefile";
import { nodePolyfills } from "vite-plugin-node-polyfills";

const FORM_VARIANT = "autogenerated-forms";
const CONFIGURATOR_VARIANT = "autogenerated-forms-configurator";

function htmlTitlePlugin(title: string): Plugin {
    return {
        name: "html-title",
        transformIndexHtml(html) {
            return html.replace(/<title>[^<]*<\/title>/, `<title>${title}</title>`);
        },
    };
}

const redirectPaths = ["/dhis-web-pivot", "/dhis-web-data-visualizer"];

export default defineConfig(({ mode }) => {
    const env = { ...loadEnv(mode, process.cwd(), ""), ...process.env };
    const variant = env.VITE_REPORT_VARIANT === CONFIGURATOR_VARIANT ? CONFIGURATOR_VARIANT : FORM_VARIANT;
    const isForm = variant === FORM_VARIANT;
    const title = isForm ? "D2 Autogenerated Forms" : "D2 Autogen Configurator";

    const dhis2BaseUrl = env.VITE_DHIS2_BASE_URL;
    const dhis2Auth = env.VITE_DHIS2_AUTH;

    return {
        base: "./",
        envPrefix: "VITE_",
        define: {
            global: "globalThis",
        },
        resolve: {
            alias: {
                fs: fileURLToPath(new URL("./src/utils/fsBrowserStub.ts", import.meta.url)),
            },
        },
        plugins: [
            nodePolyfills({ include: ["buffer"], globals: { Buffer: true } }),
            react(),
            htmlTitlePlugin(title),
            ...(isForm ? [viteSingleFile()] : []),
        ],
        build: {
            outDir: "build",
            sourcemap: false,
        },
        server: {
            port: Number(env.PORT) || 8081,
            proxy: dhis2BaseUrl
                ? {
                      "/dhis2": {
                          target: dhis2BaseUrl,
                          changeOrigin: true,
                          auth: dhis2Auth,
                          rewrite: path => path.replace(/^\/dhis2/, ""),
                          configure: proxy => {
                              proxy.on("proxyReq", (proxyReq, _req, res) => {
                                  const path = proxyReq.path;
                                  const shouldRedirect = redirectPaths.some(p => path.startsWith(p));
                                  if (shouldRedirect && "writeHead" in res) {
                                      const redirectUrl = dhis2BaseUrl.replace(/\/$/, "") + path;
                                      res.writeHead(302, { Location: redirectUrl });
                                      res.end();
                                  }
                              });
                          },
                      },
                  }
                : undefined,
        },
        test: {
            environment: "jsdom",
            globals: true,
            setupFiles: ["./config/testSetup.ts"],
            css: false,
            server: { deps: { inline: ["@eyeseetea/d2-ui-components"] } },
        },
    };
});
