import { ArgumentParser } from "argparse";
import "dotenv-flow/config";
import fs from "node:fs/promises";
import readline from "node:readline";
import { stdin as input, stdout as output } from "node:process";
import { D2Api, SelectedPick, D2DataSetSchema } from "../types/d2-api";

const FILE_TO_PUBLISH = "dist/custom-data-form.html";

const datasetFields = { id: true, name: true, formType: true, dataEntryForm: { id: true, name: true } } as const;
type Dataset = SelectedPick<D2DataSetSchema, typeof datasetFields>;

type PublishOptions = {
    url: string;
    user_auth: string;
    dataSetId?: string;
    force: boolean;
    confirm: boolean;
};

export async function publish(options: PublishOptions): Promise<void> {
    const [username, password] = options.user_auth.split(":", 2);
    if (!username || !password) throw new Error("Invalid username:password format in --user-auth");
    const api = new D2Api({ baseUrl: options.url, auth: { username, password } });

    const contentToUpload = await readFormToUpload();
    if (!contentToUpload) return;

    if (options.dataSetId) {
        await publishSingleDataSet({
            api,
            dataSetId: options.dataSetId,
            contentToUpload,
            force: options.force,
        });
    } else {
        await publishToMultipleDataSets({
            api,
            contentToUpload,
            confirm: options.confirm,
        });
    }
}

type PublishSingleOptions = {
    api: D2Api;
    dataSetId: string;
    contentToUpload: string;
    force: boolean;
};

export async function publishSingleDataSet({
    api,
    dataSetId,
    contentToUpload,
    force,
}: PublishSingleOptions): Promise<void> {
    const datasets = await getDatasets({ api, id: dataSetId });
    const dataset = datasets[0];
    if (!dataset) {
        throw new Error(`DataSet with id ${dataSetId} not found.`);
    }
    const hasCustomForm = dataset.formType === "CUSTOM" && !!dataset.dataEntryForm;
    if (hasCustomForm) {
        const datasetsWithAutogen = await getDatasets({
            api,
            id: dataSetId,
            filterByIsAutoGenForm: true,
        });
        const datasetWithAutogen = datasetsWithAutogen[0];
        if (!datasetWithAutogen && !force) {
            console.debug(
                `DataSet with id ${dataSetId} does not have a d2-autogen-form. Use --force if you are sure you want to replace the current form with the latest d2-autogen-form code.`
            );
            return;
        }
        await updateDataEntryForm(api, dataset, contentToUpload);
    } else {
        if (!force) {
            console.debug(
                `DataSet with id ${dataSetId} does not have a custom form. Use --force if you are sure you want to create a new custom form with the latest d2-autogen-form code.`
            );
            return;
        }
        await updateDataEntryForm(api, dataset, contentToUpload);
    }
    return;
}

type PublishMultipleOptions = {
    api: D2Api;
    contentToUpload: string;
    confirm: boolean;
};

export async function publishToMultipleDataSets({
    api,
    confirm,
    contentToUpload,
}: PublishMultipleOptions): Promise<void> {
    const datasets = await getDatasets({
        api,
        filterByIsAutoGenForm: true,
    });
    if (datasets.length === 0) {
        console.debug("No dataEntryForms that use d2-autogen-forms have been detected. Exiting...");
        return;
    }
    const message = `The following dataSets that use d2-autogen-forms have been detected:
${datasets.map(o => `- #${o.id} ${o.name}`).join("\n")}
    `;
    console.debug(message);

    if (!confirm) {
        const answer = await askYesNo(
            `Do yo want to replace the current code with the latest d2-autogen-form code for all of them?`
        );
        if (!answer) {
            console.debug("Aborting publish.");
            return;
        }
    }
    console.debug("Publishing to all dataSets that use d2-autogen-forms...");
    for (const dataSet of datasets) {
        await updateDataEntryForm(api, dataSet, contentToUpload);
    }
    console.debug(`✓ Published d2-autogen-forms to ${datasets.length} datasets`);
}

function readFormToUpload(): Promise<string> {
    return fs.readFile(FILE_TO_PUBLISH, "utf8").catch(() => {
        console.error(`Custom Form File ${FILE_TO_PUBLISH} not found. Please generate it first using for example:
yarn build-autogenerated-forms`);
        return "";
    });
}

type GetDatasetOptions = {
    api: D2Api;
    id?: string;
    filterByIsAutoGenForm?: boolean;
};

async function getDatasets(options: GetDatasetOptions): Promise<Dataset[]> {
    const HTML_SEARCH_QUERY = 'REACT_APP_REPORT_VARIANT:"autogenerated-forms"';

    const { api, id, filterByIsAutoGenForm } = options;
    const res = await api.models.dataSets
        .get({
            fields: datasetFields,
            paging: false,
            filter: {
                ...(id ? { id: { eq: id } } : {}),
                ...(filterByIsAutoGenForm
                    ? {
                          "dataEntryForm.htmlCode": {
                              like: HTML_SEARCH_QUERY,
                          },
                      }
                    : {}),
            },
        })
        .getData();
    return res.objects;
}

async function updateDataEntryForm(api: D2Api, dataset: Dataset, contentToUpload: string) {
    const url = `/dataSets/${dataset.id}/form`;
    console.debug(`Publishing to dataSet #${dataset.id} ${dataset.name}...`);
    try {
        // Posting to /datasets/{datasetId}/form like dhis-web-maintenance does
        // Using a PUT to /dataEntryForms/{dataEntryFormId} would be the best but couldn't get it working because of 409 errors
        await api
            .post(
                url,
                {},
                {
                    htmlCode: contentToUpload,
                    style: "NORMAL",
                }
            )
            .getData();
    } catch (error) {
        console.error("Error publishing dataEntryForm:", error);
        throw new Error("Error publishing dataEntryForm");
    }
    console.debug(`✓ Published custom form with d2-autogen-forms for dataset #${dataset.id} ${dataset.name} `);
}

async function askYesNo(question: string, defaultYes = true) {
    const suffix = defaultYes ? " [Y/n] " : " [y/N] ";
    async function questionFn(query: string): Promise<string> {
        const rl = readline.createInterface({ input, output });
        const result = await new Promise(resolve => {
            rl.question(query, resolve);
        });
        rl.close();
        return result as string;
    }
    const answer = (await questionFn(question + suffix)).trim().toLowerCase();

    if (answer === "") return defaultYes;
    return ["y", "yes"].includes(answer);
}

async function main() {
    const parser = new ArgumentParser({
        description: "Publish the d2-autogen-forms dataEntryForm a to DHIS2 instance",
    });

    parser.add_argument("-u", "--user-auth", {
        help: "DHIS2 authentication",
        metavar: "USERNAME:PASSWORD",
        default: process.env.REACT_APP_DHIS2_AUTH,
    });

    parser.add_argument("--url", {
        help: "DHIS2 base URL",
        metavar: "URL",
        default: process.env.REACT_APP_DHIS2_BASE_URL,
    });

    parser.add_argument("-y", "--yes", {
        help: "Answer yes to all prompts",
        action: "store_true",
        dest: "confirm",
    });

    parser.add_argument("--force", {
        help: "Force publish - overwrite existing dataEntryForm even if it is not currently using a d2-autogen-form",
        action: "store_true",
    });

    parser.add_argument("dataSetId", {
        help: "The dataSetId to publish the dataEntryForm to. If not provided, the script will publish to all dataSets already using d2-autogen-forms.",
        nargs: "?",
    });

    try {
        const args = parser.parse_args() as PublishOptions;
        publish(args);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

main();
