import { AutogenConfigRepository } from "../../domain/autogenerated-forms-configurator/repositories/AutogenConfigRepository";
import { D2Api } from "../../types/d2-api";
import { AutogenConfig } from "../../domain/common/entities/AutogenConfig";
import { StorageClient } from "../common/clients/storage/StorageClient";
import { Instance } from "../common/entities/Instance";
import { DataStoreStorageClient } from "../common/clients/storage/DataStoreStorageClient";

export class AutogenConfigDataStoreRepository implements AutogenConfigRepository {
    private globalStorageClient: StorageClient;

    constructor(private api: D2Api) {
        const instance = new Instance({ url: this.api.baseUrl });
        this.globalStorageClient = new DataStoreStorageClient("global", instance);
    }

    async get(dataSetCode: string): Promise<AutogenConfig> {
        const dataStoreConfig = await this.globalStorageClient.getObject<AutogenConfig>(dataSetCode);
        if (!dataStoreConfig) {
            throw new Error(`No configuration found for dataset: ${dataSetCode}`);
        }

        return dataStoreConfig;
    }

    async delete(dataSetCode: string): Promise<void> {
        return await this.globalStorageClient.removeObject(dataSetCode);
    }

    async save(dataSetCode: string, config: AutogenConfig): Promise<void> {
        return await this.globalStorageClient.saveObject(dataSetCode, config);
    }
}
