import { CustomFormRepository } from "../../domain/autogenerated-forms-configurator/repositories/CustomFormRepository";
import { Id } from "../../domain/common/entities/Base";
import { D2Api, MetadataPick } from "../../types/d2-api";

export class Dhis2CustomFormRepository implements CustomFormRepository {
    constructor(private api: D2Api) {}

    async getInstalledHtml(dataSetId: Id): Promise<string | null> {
        const { objects } = await this.api.models.dataSets
            .get({
                fields: dataSetFields,
                filter: { id: { eq: dataSetId } },
                paging: false,
            })
            .getData();

        return objects[0]?.dataEntryForm?.htmlCode ?? null;
    }

    async install(dataSetId: Id, htmlCode: string): Promise<void> {
        await this.api.post(`/dataSets/${dataSetId}/form`, {}, { htmlCode, style: "NORMAL" }).getData();
    }
}

const dataSetFields = {
    id: true,
    dataEntryForm: { htmlCode: true },
} as const;

// Silence unused-type lint — the type is implicitly used via the fields object
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _D2DataSet = MetadataPick<{
    dataSets: { fields: typeof dataSetFields };
}>["dataSets"][number];
