import { DataElementRef, DataSet, DataSetDetail } from "../../domain/autogenerated-forms-configurator/entities/DataSet";
import { DataSetRepository } from "../../domain/autogenerated-forms-configurator/repositories/DataSetRepository";
import { Id } from "../../domain/common/entities/Base";
import { D2Api, MetadataPick } from "../../types/d2-api";
import { Namespaces } from "../common/clients/storage/Namespaces";
import { generateUid } from "../../utils/uid";

export class Dhis2DataSetRepository implements DataSetRepository {
    constructor(private api: D2Api) {}

    async get(): Promise<DataSet[]> {
        const d2DataSets = await this.getMetadata();
        const autogenDatastoreKeys = await this.api.dataStore(Namespaces.D2_AUTOGEN_FORMS).getKeys().getData();

        return d2DataSets.map(dataSet => ({
            id: dataSet.id,
            name: dataSet.name.trim(),
            code: dataSet.code.trim(),
            hasCustomForm: dataSet.formType === "CUSTOM",
            canBeModified: dataSet.access.write,
            configExists: autogenDatastoreKeys.includes(dataSet.code.trim()),
        }));
    }

    async getById(id: Id): Promise<DataSet> {
        const { objects } = await this.api.models.dataSets
            .get({
                fields: dataSetFields,
                filter: { id: { eq: id } },
            })
            .getData();

        const dataSet = objects[0];
        if (!dataSet) throw new Error(`DataSet not found: ${id}`);

        const autogenDatastoreKeys = await this.api.dataStore(Namespaces.D2_AUTOGEN_FORMS).getKeys().getData();

        return {
            id: dataSet.id,
            name: dataSet.name.trim(),
            code: dataSet.code.trim(),
            hasCustomForm: dataSet.formType === "CUSTOM",
            canBeModified: dataSet.access.write,
            configExists: autogenDatastoreKeys.includes(dataSet.code.trim()),
        };
    }

    async getWithElements(id: Id): Promise<DataSetDetail> {
        const { objects } = await this.api.models.dataSets
            .get({
                fields: dataSetWithElementsFields,
                filter: { id: { eq: id } },
            })
            .getData();

        const dataSet = objects[0];
        if (!dataSet) throw new Error(`DataSet not found: ${id}`);

        const autogenDatastoreKeys = await this.api.dataStore(Namespaces.D2_AUTOGEN_FORMS).getKeys().getData();

        return {
            id: dataSet.id,
            name: dataSet.name.trim(),
            code: dataSet.code.trim(),
            hasCustomForm: dataSet.formType === "CUSTOM",
            canBeModified: dataSet.access.write,
            configExists: autogenDatastoreKeys.includes(dataSet.code.trim()),
            sections: dataSet.sections,
            dataElements: dataSet.dataSetElements.map(dse => dse.dataElement),
        };
    }

    async createDefaultSection(dataSetId: Id, dataElements: DataElementRef[]): Promise<void> {
        const section = {
            id: generateUid(),
            name: "Default",
            dataSet: { id: dataSetId },
            dataElements: dataElements.map(de => ({ id: de.id })),
            sortOrder: 0,
        };

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await this.api.metadata.post({ sections: [section] } as any).getData();
    }

    private async getMetadata(): Promise<D2DataSet[]> {
        const { objects: dataSets } = await this.api.models.dataSets
            .get({
                fields: dataSetFields,
                filter: {
                    code: {
                        "!null": "true",
                    },
                },
                paging: false,
            })
            .getData();

        return dataSets;
    }
}

const dataSetFields = {
    id: true,
    name: true,
    code: true,
    formType: true,
    access: true,
} as const;

const dataSetWithElementsFields = {
    id: true,
    name: true,
    code: true,
    formType: true,
    access: true,
    sections: { id: true },
    dataSetElements: { dataElement: { id: true, name: true } },
} as const;

type D2DataSet = MetadataPick<{
    dataSets: { fields: typeof dataSetFields };
}>["dataSets"][number];
