import { DataSet } from "../../domain/autogenerated-forms-configurator/entities/DataSet";
import { DataSetRepository } from "../../domain/autogenerated-forms-configurator/repositories/DataSetRepository";
import { D2Api, MetadataPick } from "../../types/d2-api";
import { Namespaces } from "../common/clients/storage/Namespaces";

export class Dhis2DataSetRepository implements DataSetRepository {
    constructor(private api: D2Api) {}

    async get(): Promise<DataSet[]> {
        const d2DataSets = await this.getMetadata();
        const autogenDatastoreKeys = await this.api.dataStore(Namespaces.D2_AUTOGEN_FORMS).getKeys().getData();

        return d2DataSets.map(dataSet => {
            const configExists = autogenDatastoreKeys.includes(dataSet.code);

            return { ...dataSet, configExists };
        });
    }

    private async getMetadata(): Promise<DataSetMetadata[]> {
        const { objects: dataSets } = await this.api.models.dataSets
            .get({
                fields: dataSetFields,
                filter: {
                    code: {
                        "!null": "true",
                    },
                },
                paging: false,
            })
            .getData();

        return dataSets.map(dataSet => ({
            id: dataSet.id,
            name: dataSet.name.trim(),
            code: dataSet.code.trim(),
            hasCustomForm: dataSet.formType === "CUSTOM",
        }));
    }
}

const dataSetFields = {
    id: true,
    name: true,
    code: true,
    formType: true,
} as const;

// Raw API response type (kept for type-checking the .get() call)
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _D2DataSet = MetadataPick<{
    dataSets: { fields: typeof dataSetFields };
}>["dataSets"][number];

type DataSetMetadata = {
    id: string;
    name: string;
    code: string;
    hasCustomForm: boolean;
};
