import { DataStoreConfigurationRepository } from "../../domain/autogenerated-forms-configurator/repositories/DataStoreConfigurationRepository";
import { D2Api } from "../../types/d2-api";
import { DataSet } from "../../domain/autogenerated-forms-configurator/entities/DataSet";

export class Dhis2DataStoreConfigurationRepository implements DataStoreConfigurationRepository {
    constructor(private api: D2Api) {}

    async getDatasets(): Promise<DataSet[]> {
        const { dataSets } = await this.api
            .get<{ dataSets: DataSet[] }>("/dataSets", {
                fields: "id,name,code",
                filter: ["name:ilike:MAL", "name:ilike:NHWA"],
                paging: false,
                rootJunction: "OR",
            })
            .getData();

        return dataSets.filter(dataSet => dataSet.code);
    }
}
