import { CustomForm } from "../../domain/autogenerated-forms-configurator/entities/CustomForm";
import { CustomFormRepository } from "../../domain/autogenerated-forms-configurator/repositories/CustomFormRepository";
import { Id } from "../../domain/common/entities/Base";
import { generateUid } from "../../utils/uid";
import { D2Api, MetadataPick } from "../../types/d2-api";

export class Dhis2CustomFormRepository implements CustomFormRepository {
    constructor(private api: D2Api) {}

    async get(dataSetId: Id): Promise<CustomForm> {
        const { objects } = await this.api.models.dataSets
            .get({
                fields: dataSetFields,
                filter: { id: { eq: dataSetId } },
                paging: false,
            })
            .getData();

        const dataEntryForm = objects[0]?.dataEntryForm;
        return {
            id: dataEntryForm?.id ?? null,
            htmlCode: dataEntryForm?.htmlCode ?? null,
        };
    }

    async install(dataSetId: Id, htmlCode: string, existingFormId: string | null): Promise<void> {
        const formId = existingFormId ?? generateUid();
        await this.api.metadata
            .post({
                dataEntryForms: [{ id: formId, name: `Custom form (${dataSetId})`, style: "NORMAL" as const, htmlCode }],
                dataSets: [{ id: dataSetId, dataEntryForm: { id: formId } }],
            })
            .getData();
    }
}

const dataSetFields = {
    id: true,
    dataEntryForm: { id: true, htmlCode: true },
} as const;

type _D2DataSet = MetadataPick<{
    dataSets: { fields: typeof dataSetFields };
}>["dataSets"][number];
