import { DataSet } from "../../domain/autogenerated-forms-configurator/entities/DataSet";
import { DataSetRepository } from "../../domain/autogenerated-forms-configurator/repositories/DataSetRepository";
import { D2Api } from "../../types/d2-api";

export class Dhis2DataSetRepository implements DataSetRepository {
    constructor(private api: D2Api) {}

    async get(): Promise<DataSet[]> {
        return this.getMetadata();
    }

    private async getMetadata() {
        const { objects: dataSets } = await this.api.models.dataSets
            .get({
                fields: {
                    name: true,
                    code: true,
                },
                filter: {
                    code: {
                        ne: undefined,
                    },
                },
                paging: false,
            })
            .getData();

        return dataSets;
    }
}
