import React from "react";
import _ from "lodash";

import { CellTotal, TotalItem } from "../GridWithCatOptionCombosViewModel";
import { CustomDataTableCell } from "./CustomDataTables";
import { SectionStyle } from "../../../../domain/common/entities/SectionStyle";
import { DataFormInfo } from "../AutogeneratedForm";
import { DataValueNumberSingle, Period } from "../../../../domain/common/entities/DataValue";
import { CustomInput } from "../widgets/NumberWidget";
import { Maybe } from "../../../../utils/ts-utils";
import { getItemTotalDataValue } from "./DataTableCellFormula";
import { resolveDataElement } from "../utils/resolveDataElement";

export type DataTableCellSummaryProps = {
    dataElements: CellTotal[];
    styles: SectionStyle;
    dataFormInfo: DataFormInfo;
    period?: Period;
};

export const DataTableCellSummary: React.FC<DataTableCellSummaryProps> = props => {
    const { dataFormInfo, styles, dataElements, period } = props;
    const totals = _(dataElements).map(cellTotal => {
        const values = cellTotal.items.map(itemTotal => getItemTotalDataValue(dataFormInfo, itemTotal, period));
        const compiled = _.template(cellTotal.formula);
        return compiled(_.merge({}, ...values));
    });

    // formula evaluation in totals can return NaN if values are undefined
    const totalCalculated = totals.every(value => Number.isNaN(Number(value)) || value === "")
        ? ""
        : totals.sumBy(value => (Number.isNaN(Number(value)) ? 0 : Number(value)));

    return (
        <CustomDataTableCell backgroundColor={styles.totals.backgroundColor} key="column-totals">
            <CustomInput value={totalCalculated} disabled readOnly />
        </CustomDataTableCell>
    );
};
export function getValueFromDataElement(
    dataFormInfo: DataFormInfo,
    itemTotal: TotalItem,
    period?: Period
): Maybe<number> {
    const dataElementToRead = resolveDataElement(dataFormInfo, itemTotal.dataElement);
    const dataValue = dataFormInfo.data.values.getOrEmpty(dataElementToRead, {
        categoryOptionComboId: itemTotal.categoryOptionCombo.id,
        orgUnitId: dataFormInfo.orgUnitId,
        period: period || dataFormInfo.period,
    }) as DataValueNumberSingle;
    if (dataValue.value === "") {
        return undefined;
    }
    const numericValue = Number(dataValue.value);
    return window.isNaN(numericValue) ? undefined : numericValue;
}
