import React from "react";
import _ from "lodash";

import { CustomDataTableCell } from "./CustomDataTables";
import { SectionStyle } from "../../../../domain/common/entities/SectionStyle";
import { DataFormInfo } from "../AutogeneratedForm";
import { DataValueNumberSingle, Period } from "../../../../domain/common/entities/DataValue";
import { CustomInput } from "../widgets/NumberWidget";
import { DataElement } from "../../../../domain/common/entities/DataElement";

export type DataTableCellRowTotalProps = {
    styles: SectionStyle;
    dataFormInfo: DataFormInfo;
    dataElement: DataElement;
    colSpan?: number;
    onlyCocIds?: string[];
    period?: Period;
};

export const DataTableCellRowTotal: React.FC<DataTableCellRowTotalProps> = props => {
    const { dataFormInfo, dataElement, styles, colSpan, onlyCocIds, period } = props;

    const combinationsToCalculate =
        onlyCocIds && onlyCocIds.length > 0
            ? dataElement.categoryOptionCombos.filter(coc => onlyCocIds?.includes(coc.id))
            : dataElement.categoryOptionCombos;

    const totalValue = _(combinationsToCalculate)
        .map(coc => {
            const deValue = dataFormInfo.data.values.get(
                {
                    ...dataElement,
                    cocId: coc.id,
                },
                {
                    categoryOptionComboId: coc.id,
                    orgUnitId: dataFormInfo.orgUnitId,
                    period: period || dataFormInfo.period,
                }
            ) as DataValueNumberSingle;
            return Number(deValue.value);
        })
        .compact()
        .sum();

    return (
        <CustomDataTableCell colSpan={colSpan} backgroundColor={styles.rows.backgroundColor} key="total-row">
            <CustomInput value={totalValue} disabled readOnly />
        </CustomDataTableCell>
    );
};
