import React from "react";
import _ from "lodash";

import { CellTotal } from "../GridWithCatOptionCombosViewModel";
import { CustomDataTableCell } from "./CustomDataTables";
import { SectionStyle } from "../../../../domain/common/entities/SectionStyle";
import { DataFormInfo } from "../AutogeneratedForm";
import { CustomInput } from "../widgets/NumberWidget";
import { getValueFromDataElement } from "./DataTableCellSummary";
import { Period } from "../../../../domain/common/entities/DataValue";

export type DataTableCellFormulaProps = {
    total: CellTotal;
    styles: SectionStyle;
    dataFormInfo: DataFormInfo;
    formula: string;
    period?: Period;
};

export const DataTableCellFormula: React.FC<DataTableCellFormulaProps> = props => {
    const { dataFormInfo, formula, period, styles, total } = props;
    const totalCalculated = _(total.items)
        .map(itemTotal => {
            const numericValue = getValueFromDataElement(dataFormInfo, itemTotal, period);
            return numericValue && window.isNaN(numericValue)
                ? undefined
                : { [itemTotal.dataElement.code]: numericValue };
        })
        .compact()
        .value();

    const compiled = _.template(formula);
    const totalValue = compiled(_.merge({}, ...totalCalculated));

    return (
        <CustomDataTableCell backgroundColor={styles.totals.backgroundColor} key={total.columnName}>
            <CustomInput value={!window.isNaN(Number(totalValue)) ? totalValue : ""} disabled readOnly />
        </CustomDataTableCell>
    );
};
