import React from "react";
import _ from "lodash";

import { DataFormInfo } from "../AutogeneratedForm";
import { CustomInput } from "../widgets/NumberWidget";
import { DataValueBoolean, DataValueNumberSingle, Period } from "../../../../domain/common/entities/DataValue";

export type InputFormulaProps = {
    dataFormInfo: DataFormInfo;
    formula: string;
    dataElementCodes: string[];
    period?: Period;
};

const EMPTY_VALUE = "";

export const InputFormula: React.FC<InputFormulaProps> = props => {
    const { dataFormInfo, formula, dataElementCodes, period } = props;

    const objWithValues = _(dataElementCodes)
        .map(dataElementCode => {
            const dataElement = dataFormInfo.metadata.dataForm.dataElements.find(de => de.code === dataElementCode);
            if (!dataElement) {
                console.warn(
                    `InputFormula: Data element with code ${dataElementCode} not found in dataFormInfo metadata.`
                );
                return [dataElementCode, EMPTY_VALUE];
            }

            const dataValue = dataFormInfo.data.values.getOrEmpty(dataElement, {
                categoryOptionComboId: dataFormInfo.categoryOptionComboId,
                orgUnitId: dataFormInfo.orgUnitId,
                period: period ?? dataFormInfo.period,
            });

            switch (dataValue.type) {
                case "NUMBER": {
                    const dataValueNumber = dataValue as DataValueNumberSingle;
                    if (dataValueNumber.value === "") return [dataElementCode, EMPTY_VALUE];
                    const numericValue = Number(dataValueNumber.value);
                    const value = window.isNaN(numericValue) ? undefined : numericValue;
                    return [dataElementCode, value];
                }
                case "BOOLEAN": {
                    const dataValueBoolean = dataValue as DataValueBoolean;
                    return [dataElementCode, dataValueBoolean.value];
                }
                default:
                    // TODO: cover other data types
                    // @ts-ignore
                    return [dataElementCode, dataValue.value ?? EMPTY_VALUE];
            }
        })
        .fromPairs()
        .value();

    const compiled = _.template(formula);
    const totalValue = compiled(_.merge({}, objWithValues));

    const isNaN = window.isNaN(Number(totalValue));

    return <CustomInput value={!isNaN ? totalValue : ""} disabled readOnly />;
};
