import React from "react";
import _ from "lodash";

import { DataFormInfo } from "../AutogeneratedForm";
import { CustomInput } from "../widgets/NumberWidget";
import { DataValueBoolean, DataValueNumberSingle, Period } from "../../../../domain/common/entities/DataValue";

export type InputFormulaProps = {
    dataFormInfo: DataFormInfo;
    formula: string;
    dataElementCodes: string[];
    period?: Period;
};

const EMPTY_VALUE = "";

export const InputFormula: React.FC<InputFormulaProps> = props => {
    const formulaValue = calculateFormula(props);

    const isNaN = window.isNaN(Number(formulaValue));
    const value = !isNaN ? formulaValue : "";

    return <CustomInput value={value} disabled readOnly />;
};

export function calculateFormula(options: InputFormulaProps): string {
    const { dataFormInfo, formula, dataElementCodes, period } = options;

    const objWithValues = _(dataElementCodes)
        .map(dataElementCode => {
            const dataElement = dataFormInfo.metadata.dataForm.dataElements.find(de => de.code === dataElementCode);
            if (!dataElement) {
                console.warn(
                    `InputFormula: Data element with code ${dataElementCode} not found in dataFormInfo metadata.`
                );
                return [dataElementCode, EMPTY_VALUE];
            }

            const dataValue = dataFormInfo.data.values.getOrEmpty(dataElement, {
                categoryOptionComboId: dataFormInfo.categoryOptionComboId,
                orgUnitId: dataFormInfo.orgUnitId,
                period: period ?? dataFormInfo.period,
            });

            switch (dataValue.type) {
                case "NUMBER": {
                    const dataValueNumber = dataValue as DataValueNumberSingle;
                    if (dataValueNumber.value === "") return [dataElementCode, EMPTY_VALUE];
                    const numericValue = Number(dataValueNumber.value);
                    const value = window.isNaN(numericValue) ? undefined : numericValue;
                    return [dataElementCode, value];
                }
                case "BOOLEAN": {
                    const dataValueBoolean = dataValue as DataValueBoolean;
                    return [dataElementCode, dataValueBoolean.value];
                }
                default:
                    // TODO: cover other data types
                    return [dataElementCode, EMPTY_VALUE];
            }
        })
        .fromPairs()
        .value();

    const compiled = _.template(formula, {
        imports: defaultHelpers,
    });
    const value = compiled(_.merge({}, objWithValues));
    return value;
}

type Flag = string | number | null | undefined;

const checkCondition = (v: Flag): boolean => (v === "" ? true : Number(v) !== 0 && !Number.isNaN(Number(v)));

function calculateMNCA(
    numerator: number,
    denominator: number,
    isCorrect: number,
    newValue: number,
    type: "percent" | "number"
): number {
    const denominatorValue = checkCondition(isCorrect) ? denominator : newValue;
    return calculateNumDem(numerator, denominatorValue, type);
}

function calculateNumDem(numerator: number, denominator: number, type: "percent" | "number"): number {
    if (numerator === 0) return 0;

    const times = getTimes(type);
    const result = (numerator / denominator) * times;

    return Math.round(result * 10) / 10;
}

const getTimes = (type: "percent" | "number") => {
    switch (type) {
        case "percent":
            return 100;
        case "number":
            return 1;
        default:
            console.warn(`calculateMNCA: type ${type} not recognized, returning 1 as times multiplier.`);
            return 1;
    }
};

const defaultHelpers = Object.freeze({ fetch: undefined, calculateNumDem, checkCondition, calculateMNCA });
