import React from "react";
import styled from "styled-components";
import { Button, Chip, makeStyles, Tooltip } from "@material-ui/core";
import { DataSetFilter } from "./DataSetFilter";
import { Editor } from "./Editor";
import i18n from "@eyeseetea/d2-ui-components/locales";
import { useConfigurator } from "./hooks/useConfigurator";
import logo from "../../components/share/logo-eyeseetea.png";
import { ConfirmationDialog } from "@eyeseetea/d2-ui-components";
import { useBooleanState } from "../../utils/use-boolean";
import { useFilters } from "./hooks/useFilters";
import { LoadingOverlay } from "../../components/loading-overlay/LoadingOverlay";
import { useInstallCustomForm } from "./hooks/useInstallCustomForm";
import { CustomFormInstallState } from "../../../domain/autogenerated-forms-configurator/usecases/GetInstallStateUseCase";

const AutogeneratedFormConfigurator: React.FC = () => {
    const [isCreateConfigDialogOpen, { enable: openCreateConfigDialog, disable: closeCreateConfigDialog }] =
        useBooleanState(false);
    const [isDeleteConfigDialogOpen, { enable: openDeleteConfigDialog, disable: closeDeleteConfigDialog }] =
        useBooleanState(false);
    const [isInstallDialogOpen, { enable: openInstallDialog, disable: closeInstallDialog }] = useBooleanState(false);

    const {
        configValue,
        dataSet,
        disableSave,
        isLoading,
        newDataSet,
        clearConfig,
        createNewConfig,
        deleteConfig,
        saveConfig,
        updateConfigValue,
        updateDataSet,
        updateJsonValidity,
        updateLoadingState,
        updateNewDataSet,
    } = useConfigurator();
    const { code: dataSetCode, name: dataSetName, id: dataSetId } = dataSet;
    const { code: newDataSetCode, name: newDataSetName } = newDataSet;
    const { dataSets: dataSetItems, newDataSets: newDataSetItems } = useFilters(dataSetCode, updateLoadingState);
    const { installState, bundledVersion, isInstalling, installCustomForm } = useInstallCustomForm(
        dataSetId || undefined,
        updateLoadingState
    );
    const classes = useStyles();

    const isReinstall =
        installState?.type === "installed" ||
        installState?.type === "outdated" ||
        installState?.type === "unknown-version";

    const installButtonDisabled = !dataSetId || !bundledVersion || isInstalling;

    const installDialogTitle = isReinstall ? i18n.t("Re-install custom form") : i18n.t("Install custom form");

    const installDialogBody = isReinstall
        ? i18n.t(
              "This dataset already has a custom form. Installing will overwrite it with the bundled version (v{{version}}). This action cannot be undone.",
              { version: bundledVersion }
          )
        : i18n.t(
              "Install the bundled custom form (v{{version}}) into this dataset. The form will be available in the Data Entry app.",
              { version: bundledVersion }
          );

    return (
        <Container>
            <LoadingOverlay isLoading={isLoading || isInstalling} text={i18n.t("Loading...")} />

            <StyledHeader>
                <Icon src={logo} alt="Logo" />
                <h1>D2 Autogen Configurator</h1>
            </StyledHeader>

            <StyledSection>
                <DataSetFilter dataSetItems={dataSetItems} dataSetCode={dataSetCode} onChange={updateDataSet} />

                <Button color="primary" variant="contained" onClick={openCreateConfigDialog}>
                    {i18n.t("Add new data form configuration")}
                </Button>
            </StyledSection>

            {dataSetCode && (
                <InstallSection>
                    <InstallStateChip installState={installState} />
                    <Tooltip
                        title={
                            !bundledVersion
                                ? i18n.t(
                                      "Bundled custom form not found. Run yarn start-configurator to make it available."
                                  )
                                : ""
                        }
                    >
                        <span>
                            <Button
                                color="primary"
                                variant="outlined"
                                onClick={openInstallDialog}
                                disabled={installButtonDisabled}
                            >
                                {isReinstall ? i18n.t("Re-install custom form") : i18n.t("Install custom form")}
                            </Button>
                        </span>
                    </Tooltip>
                </InstallSection>
            )}

            <Editor
                configValue={configValue}
                dataSetCode={dataSetCode}
                updateConfigValue={updateConfigValue}
                updateJsonValidity={updateJsonValidity}
            />

            <ButtonGroup>
                <Button color="primary" variant="contained" onClick={saveConfig} disabled={disableSave}>
                    {i18n.t("Save")}
                </Button>
                <Button onClick={clearConfig} color="default" variant="contained">
                    {i18n.t("Clear")}
                </Button>
                {dataSetCode && (
                    <Button onClick={openDeleteConfigDialog} className={classes.errorContained} variant="contained">
                        {i18n.t("Delete config")}
                    </Button>
                )}
            </ButtonGroup>

            <ConfirmationDialog
                open={isCreateConfigDialogOpen}
                title={i18n.t("Add new data form configuration")}
                cancelText={i18n.t("Cancel")}
                disableSave={!newDataSetCode}
                saveText={i18n.t("Create config")}
                onClose={closeCreateConfigDialog}
                onSave={() => {
                    createNewConfig(newDataSet);
                    closeCreateConfigDialog();
                }}
                onCancel={closeCreateConfigDialog}
                fullWidth
                maxWidth="md"
            >
                <Container>
                    <DataSetFilter
                        dataSetItems={newDataSetItems}
                        dataSetCode={newDataSetCode}
                        onChange={updateNewDataSet}
                        helperText={i18n.t("Only datasets with codes are listed here.")}
                    />

                    {newDataSetCode && (
                        <p>
                            {i18n.t("An empty configuration will be created for the dataset")}
                            <StyledSpan>
                                {" "}
                                {i18n.t("{{dataSet}}.", {
                                    dataSet: newDataSetName,
                                })}
                            </StyledSpan>
                        </p>
                    )}
                </Container>
            </ConfirmationDialog>

            <ConfirmationDialog
                open={isDeleteConfigDialogOpen}
                title={i18n.t("Delete data form configuration")}
                cancelText={i18n.t("Cancel")}
                saveText={i18n.t("Delete config")}
                disableSave={!dataSetCode}
                onClose={closeDeleteConfigDialog}
                onSave={() => {
                    deleteConfig(dataSet);
                    closeDeleteConfigDialog();
                }}
                onCancel={closeDeleteConfigDialog}
                fullWidth
                maxWidth="md"
            >
                <Container>
                    <p>
                        {i18n.t("Are you sure you want to delete the configuration for dataset")}
                        <StyledSpan>
                            {" "}
                            {i18n.t("{{dataSet}}", {
                                dataSet: dataSetName,
                            })}
                        </StyledSpan>
                        {i18n.t("? This action cannot be undone.")}
                    </p>
                </Container>
            </ConfirmationDialog>

            <ConfirmationDialog
                open={isInstallDialogOpen}
                title={installDialogTitle}
                cancelText={i18n.t("Cancel")}
                saveText={isReinstall ? i18n.t("Overwrite and install") : i18n.t("Install")}
                disableSave={installButtonDisabled}
                onClose={closeInstallDialog}
                onSave={async () => {
                    closeInstallDialog();
                    await installCustomForm();
                }}
                onCancel={closeInstallDialog}
                fullWidth
                maxWidth="sm"
            >
                <Container>
                    <p>{installDialogBody}</p>
                </Container>
            </ConfirmationDialog>
        </Container>
    );
};

function InstallStateChip({ installState }: { installState: CustomFormInstallState | undefined }) {
    if (!installState) return null;

    switch (installState.type) {
        case "not-installed":
            return <Chip label={i18n.t("Not installed")} size="small" />;
        case "installed":
            return (
                <Chip
                    label={i18n.t("Installed (v{{version}})", { version: installState.version })}
                    size="small"
                    color="primary"
                />
            );
        case "outdated":
            return (
                <Chip
                    label={i18n.t("Outdated (v{{installed}} → v{{bundled}})", {
                        installed: installState.installedVersion,
                        bundled: installState.bundledVersion,
                    })}
                    size="small"
                    color="secondary"
                />
            );
        case "unknown-version":
            return <Chip label={i18n.t("Custom form installed (unknown version)")} size="small" color="secondary" />;
    }
}

const useStyles = makeStyles(theme => {
    const error = theme.palette.error.main;

    return {
        errorContained: {
            backgroundColor: error,
            color: theme.palette.getContrastText(error),
            "&:hover": {
                backgroundColor: error,
            },
        },
    };
});

export default React.memo(AutogeneratedFormConfigurator);

const Container = styled.div`
    padding: 1.5rem;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
`;

const StyledHeader = styled.header`
    display: flex;
    align-items: center;
    gap: 2rem;
`;

const Icon = styled.img`
    height: 4rem;
`;

const StyledSection = styled.section`
    display: flex;
    align-items: center;
    justify-content: space-between;
`;

const InstallSection = styled.section`
    display: flex;
    align-items: center;
    gap: 1rem;
`;

const ButtonGroup = styled.div`
    width: 50%;
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 0 1rem;
`;

const StyledSpan = styled.span`
    font-weight: bold;
    color: ${props => props.theme.palette.primary.main};
`;
