import React, { useEffect, useMemo, useState } from "react";
import styled from "styled-components";
import { Button } from "@material-ui/core";
import { useAppContext } from "../../contexts/app-context";
import { DataSet } from "../../../domain/autogenerated-forms-configurator/entities/DataSet";
import _ from "lodash";
import { ConfiguratorFilter, Filters } from "./Filters";
import { Editor } from "./Editor";

const AutogeneratedFormConfigurator: React.FC = () => {
    const { compositionRoot } = useAppContext();
    const [filters, setFilters] = useState(() => getEmptyDataValuesFilter());

    const [dataSets, setDataSets] = useState<DataSet[]>([]);
    const [value, setValue] = useState<string | undefined>();
    const [isJSONValid, setJsonValidity] = useState<boolean>(false);

    const { dsCode, dataElements, sectionCodes, deInSectionCodes } = useMemo(() => {
        const selectedDS = _.find(dataSets, { id: filters.dataSetId });
        if (!selectedDS) return { dsCode: "", sectionCodes: [], dataElements: [], deInSectionCodes: [] };

        setValue(!value ? "{}" : value);

        const sectionDEs = _(selectedDS.sections)
            .flatMap(section =>
                section.dataElements.map(dataElement => ({
                    dataElementCode: dataElement.code,
                    optionSetCode: dataElement.optionSet?.code,
                }))
            )
            .value();
        const dataSetDEs = _(selectedDS.dataSetElements)
            .map(dataSetElement => ({
                dataElementCode: dataSetElement.dataElement?.code,
                optionSetCode: dataSetElement.dataElement.optionSet?.code,
            }))
            .value();
        const dataElements = _.uniqBy(_.concat(sectionDEs, dataSetDEs), "dataElementCode");

        const deInSectionCodes = selectedDS.sections.flatMap(section =>
            section.dataElements.map(dataElement => dataElement.code)
        );
        const sectionCodes = selectedDS.sections.map(section => section.code);

        console.log({
            selectedDS,
            dataElements,
            dsCode: selectedDS.code,
            sectionCodes,
            deInSectionCodes,
        });

        return { dsCode: selectedDS.code, sectionCodes, dataElements, deInSectionCodes };
    }, [dataSets, filters.dataSetId, value]);

    useEffect(() => {
        compositionRoot.dataStoreConfig.getDataSets().then(dataSets => setDataSets(dataSets));
    }, [compositionRoot.dataStoreConfig]);

    useEffect(() => {
        compositionRoot.dataStoreConfig
            .getFormConfig(dsCode)
            .then(config => dsCode !== "" && setValue(JSON.stringify(config, null, 4)));
    }, [compositionRoot.dataStoreConfig, dataSets, dsCode]);

    function handleEditorValidation(markers: any) {
        if (_.isEmpty(markers)) {
            setJsonValidity(true);
        } else {
            setJsonValidity(false);
        }
    }

    return (
        <Container>
            <Filters values={filters} onChange={setFilters} options={{ dataSets }} />

            <Editor
                handleEditorValidation={handleEditorValidation}
                json={value}
                onChange={setValue}
                editorCodes={{
                    dsCode,
                    dataElements,
                    deInSectionCodes,
                    sectionCodes,
                }}
            />

            <ButtonGroup>
                <Button
                    color="primary"
                    variant="contained"
                    onClick={() => compositionRoot.dataStoreConfig.saveFormConfig(dsCode, JSON.parse(value ?? ""))}
                    disabled={!filters.dataSetId || !isJSONValid || !value}
                >
                    Save
                </Button>
                <Button color="default" variant="contained">
                    Cancel
                </Button>
            </ButtonGroup>
        </Container>
    );
};

export default React.memo(AutogeneratedFormConfigurator);

const Container = styled.div`
    padding: 20px;
`;

const ButtonGroup = styled.div`
    width: 50%;
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 0 1rem;
`;

function getEmptyDataValuesFilter(): ConfiguratorFilter {
    return {
        dataSetId: "",
    };
}
