import { Dropdown, DropdownProps } from "@eyeseetea/d2-ui-components";
import i18n from "@eyeseetea/d2-ui-components/locales";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import styled from "styled-components";
import { DataSet } from "../../../domain/autogenerated-forms-configurator/entities/DataSet";
import { useAppContext } from "../../contexts/app-context";
import { CodedRef } from "../../../domain/common/entities/Base";

export type ConfiguratorFiltersProps = {
    values: ConfiguratorFilter;
    onChange: React.Dispatch<React.SetStateAction<ConfiguratorFilter>>;
};

export type ConfiguratorFilter = {
    dataSetCode: string;
};

export const Filters: React.FC<ConfiguratorFiltersProps> = React.memo(props => {
    const { values: filter, onChange } = props;

    const { dataSets } = useFilters();
    const dataSetItems = useMemoOptionsFromNamedRef(dataSets);

    const setDataSet = useCallback<SingleDropdownHandler>(
        dataSetCode => onChange(prev => ({ ...prev, dataSetCode: dataSetCode ?? "" })),
        [onChange]
    );

    return (
        <Container>
            <SingleDropdownStyled
                items={dataSetItems}
                value={filter.dataSetCode}
                onChange={setDataSet}
                label={i18n.t("Data set")}
                hideEmpty
            />
        </Container>
    );
});

export type FiltersState = {
    dataSets: DataSet[];
};

function useFilters(): FiltersState {
    const { compositionRoot } = useAppContext();
    const [dataSets, setDataSets] = useState<DataSet[]>([]);

    useEffect(() => {
        compositionRoot.dataStoreConfig.getDataSets().then(dataSets => setDataSets(dataSets));
    }, [compositionRoot.dataStoreConfig]);

    return { dataSets: dataSets };
}

function useMemoOptionsFromNamedRef(options: CodedRef[]) {
    return useMemo(() => options.map(option => ({ value: option.code, text: option.name })), [options]);
}

const Container = styled.div`
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
`;

const SingleDropdownStyled = styled(Dropdown)`
    margin-left: -10px;
    width: 50%;
`;

type SingleDropdownHandler = DropdownProps["onChange"];
