import { Dropdown, DropdownProps } from "@eyeseetea/d2-ui-components";
import i18n from "@eyeseetea/d2-ui-components/locales";
import React from "react";
import styled from "styled-components";
import { useAutogenSchema } from "./useAutogenSchema";
import { CodedRef } from "../../../domain/autogenerated-forms-configurator/entities/AutogenConfig";
export interface ConfiguratorFiltersProps {
    values: ConfiguratorFilter;
    onChange: React.Dispatch<React.SetStateAction<ConfiguratorFilter>>;
}

export interface ConfiguratorFilter {
    dataSetCode: string;
}

export const Filters: React.FC<ConfiguratorFiltersProps> = React.memo(props => {
    const { values: filter, onChange } = props;

    const { dataSets } = useAutogenSchema(filter.dataSetCode);
    const dataSetItems = useMemoOptionsFromNamedRef(dataSets);

    const setDataSet = React.useCallback<SingleDropdownHandler>(
        dataSetCode => onChange(prev => ({ ...prev, dataSetCode: dataSetCode ?? "" })),
        [onChange]
    );

    return (
        <Container>
            <SingleDropdownStyled
                items={dataSetItems}
                value={filter.dataSetCode}
                onChange={setDataSet}
                label={i18n.t("Data set")}
                hideEmpty
            />
        </Container>
    );
});

function useMemoOptionsFromNamedRef(options: CodedRef[]) {
    return React.useMemo(() => {
        return options.map(option => ({ value: option.code, text: option.name }));
    }, [options]);
}

const Container = styled.div`
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
`;

const SingleDropdownStyled = styled(Dropdown)`
    margin-left: -10px;
    width: 50%;
`;

type SingleDropdownHandler = DropdownProps["onChange"];
