import { useCallback, useEffect, useState } from "react";
import { useAppContext } from "../../contexts/app-context";
import _ from "lodash";
import { Marker } from "../../../domain/autogenerated-forms-configurator/entities/DataSet";

export function useAutogenEditor(dataSetCode: string) {
    const { compositionRoot } = useAppContext();

    const [jsonValue, setJSONValue] = useState<string | undefined>("{}");
    const [isJSONValid, setJsonValidity] = useState<boolean>(false);

    useEffect(() => {
        compositionRoot.dataStoreConfig
            .getFormConfig(dataSetCode)
            .then(config => dataSetCode !== "" && setJSONValue(JSON.stringify(config, null, 4)));
    }, [compositionRoot.dataStoreConfig, dataSetCode]);

    const saveConfig = useCallback(async () => {
        await compositionRoot.dataStoreConfig.saveFormConfig(dataSetCode, JSON.parse(jsonValue ?? ""));
    }, [compositionRoot.dataStoreConfig, dataSetCode, jsonValue]);

    const handleEditorValidation = useCallback((markers: Marker[]) => {
        return _.isEmpty(markers) ? setJsonValidity(true) : setJsonValidity(false);
    }, []);

    const disableSave = !dataSetCode || !isJSONValid || !jsonValue;

    return {
        disableSave,
        isJSONValid,
        jsonValue,
        handleEditorValidation,
        saveConfig,
        setJSONValue,
    };
}
