import { DataElement } from "../../../../domain/common/entities/DataElement";
import { DataFormInfo } from "../AutogeneratedForm";

/**
 * If dataElement contains mirrorFrom, resolves and returns the referenced data element from dataFormInfo.
 * Otherwise, returns the original data element.
 */
export function resolveDataElement(dataFormInfo: DataFormInfo, dataElement: DataElement): DataElement {
    if (!dataElement.mirrorFrom) return dataElement;
    const mirrorDataElement = dataFormInfo.metadata.dataForm.dataElements.find(
        de => de.code === dataElement.mirrorFrom
    );
    if (!mirrorDataElement) {
        console.warn(`Mirror data element with code ${dataElement.mirrorFrom} not found.`);
        return dataElement;
    }
    return mirrorDataElement;
}
