import { useCallback, useEffect, useMemo, useState } from "react";
import { useAppContext } from "../../../contexts/app-context";
import { useJsonProcessor } from "./useJsonProcessor";
import { AutogenConfig } from "../../../../domain/common/entities/AutogenConfig";
import { CodedRef, Id } from "../../../../domain/common/entities/Base";
import { useSnackbar } from "@eyeseetea/d2-ui-components";
import i18n from "@eyeseetea/d2-ui-components/locales";
import { DataElementRef } from "../../../../domain/autogenerated-forms-configurator/entities/DataSet";

export type DataSetViewModel = CodedRef & { id: Id; canBeModified: boolean };

type ConfiguratorState = {
    configValue: string;
    dataSet: DataSetViewModel;
    disableSave: boolean;
    isLoading: boolean;
    newDataSet: DataSetViewModel;
    showCreateSectionDialog: boolean;
    clearConfig: () => void;
    createNewConfig: (dataSet: DataSetViewModel) => void;
    deleteConfig: (dataSet: DataSetViewModel) => void;
    saveConfig: () => Promise<void>;
    confirmCreateSection: () => Promise<void>;
    cancelCreateSection: () => void;
    updateConfigValue: (value: string) => void;
    updateDataSet: (dataSet: DataSetViewModel) => void;
    updateJsonValidity: (isValid: boolean) => void;
    updateLoadingState: (isLoading: boolean) => void;
    updateNewDataSet: (dataSet: DataSetViewModel) => void;
};

export function useConfigurator(): ConfiguratorState {
    const { compositionRoot } = useAppContext();
    const snackbar = useSnackbar();
    const { formatJson, parseJson } = useJsonProcessor();

    const [isLoading, updateLoadingState] = useState(false);
    const [configValue, updateConfigValue] = useState<string>(DEFAULT_JSON_VALUE);
    const [isJSONValid, updateJsonValidity] = useState<boolean>(false);
    const [dataSet, updateDataSet] = useState<DataSetViewModel>(emptyDataSetViewModel);
    const [newDataSet, updateNewDataSet] = useState<DataSetViewModel>(emptyDataSetViewModel);
    const [showCreateSectionDialog, setShowCreateSectionDialog] = useState(false);
    const [pendingDataElements, setPendingDataElements] = useState<DataElementRef[]>([]);

    useEffect(() => {
        if (!dataSet.code) return;

        updateLoadingState(true);
        compositionRoot.dataStoreConfig
            .getFormConfig(dataSet.code)
            .then(async config => {
                const formattedConfig = await formatJson(config);
                updateConfigValue(formattedConfig);
            })
            .finally(() => updateLoadingState(false));
    }, [compositionRoot.dataStoreConfig, dataSet, formatJson]);

    const clearConfig = useCallback(() => {
        updateConfigValue(DEFAULT_JSON_VALUE);
        updateJsonValidity(false);
    }, []);

    const createNewConfig = useCallback(
        (dataSet: DataSetViewModel) => {
            updateLoadingState(true);
            const newConfig: AutogenConfig = {
                dataSets: {
                    [dataSet.code]: {},
                },
            };
            const formattedConfig = JSON.stringify(newConfig, null, 4);

            compositionRoot.dataStoreConfig
                .saveFormConfig(dataSet.code, newConfig)
                .then(() => {
                    updateDataSet(dataSet);
                    updateConfigValue(formattedConfig);
                    updateJsonValidity(true);
                    snackbar.success(i18n.t("New configuration created"));
                })
                .catch(error => snackbar.error(error.message))
                .finally(() => updateLoadingState(false));
        },
        [compositionRoot.dataStoreConfig, snackbar]
    );

    const deleteConfig = useCallback(
        (dataSet: DataSetViewModel) => {
            updateLoadingState(true);

            compositionRoot.dataStoreConfig
                .deleteFormConfig(dataSet.code)
                .then(() => {
                    updateDataSet(emptyDataSetViewModel);
                    clearConfig();
                    snackbar.success(i18n.t("Configuration deleted"));
                })
                .catch(error => snackbar.error(error.message))
                .finally(() => updateLoadingState(false));
        },
        [compositionRoot.dataStoreConfig, clearConfig, snackbar]
    );

    const saveConfig = useCallback(async () => {
        if (!dataSet) return;

        updateLoadingState(true);
        const parsedConfig = await parseJson(configValue);
        await compositionRoot.dataStoreConfig
            .saveFormConfig(dataSet.code, parsedConfig)
            .then(async () => {
                snackbar.success(i18n.t("Configuration saved"));
                const dataSetDetail = await compositionRoot.dataSet.getWithElements(dataSet.id);
                if (dataSetDetail.sections.length === 0) {
                    setPendingDataElements(dataSetDetail.dataElements);
                    setShowCreateSectionDialog(true);
                }
            })
            .catch(error => snackbar.error(error.message))
            .finally(() => updateLoadingState(false));
    }, [dataSet, parseJson, configValue, compositionRoot.dataStoreConfig, compositionRoot.dataSet, snackbar]);

    const confirmCreateSection = useCallback(async () => {
        setShowCreateSectionDialog(false);
        updateLoadingState(true);
        await compositionRoot.dataSet
            .createDefaultSection(dataSet.id, pendingDataElements)
            .then(() => snackbar.success(i18n.t("Default section created. Reload the data entry form to see it.")))
            .catch(error => snackbar.error(error.message))
            .finally(() => updateLoadingState(false));
    }, [compositionRoot.dataSet, dataSet.id, pendingDataElements, snackbar]);

    const cancelCreateSection = useCallback(() => {
        setShowCreateSectionDialog(false);
    }, []);

    const disableSave = useMemo(() => !dataSet || !isJSONValid || !configValue, [dataSet, isJSONValid, configValue]);

    return {
        configValue: configValue,
        dataSet: dataSet,
        disableSave: disableSave,
        isLoading: isLoading,
        newDataSet: newDataSet,
        showCreateSectionDialog: showCreateSectionDialog,
        clearConfig: clearConfig,
        createNewConfig: createNewConfig,
        deleteConfig: deleteConfig,
        saveConfig: saveConfig,
        confirmCreateSection: confirmCreateSection,
        cancelCreateSection: cancelCreateSection,
        updateDataSet: updateDataSet,
        updateConfigValue: updateConfigValue,
        updateJsonValidity: updateJsonValidity,
        updateLoadingState: updateLoadingState,
        updateNewDataSet: updateNewDataSet,
    };
}

export const DEFAULT_JSON_VALUE = "{}";
const emptyDataSetViewModel: DataSetViewModel = { id: "", code: "", name: "", canBeModified: false };
