import { useEffect, useMemo, useState } from "react";
import { useAppContext } from "../../../contexts/app-context";
import { AutogenConfigDataSets } from "../../../../domain/autogenerated-forms-configurator/usecases/GetDataSetsUseCase";
import { CodedRef, Id } from "../../../../domain/common/entities/Base";
import { useSnackbar } from "@eyeseetea/d2-ui-components";
import i18n from "@eyeseetea/d2-ui-components/locales";

type FiltersState = {
    dataSets: Option[];
    newDataSets: Option[];
};

export type Option = {
    value: string;
    text: string;
    id: Id;
    hasCustomForm: boolean;
    canBeModified: boolean;
};

export function useFilters(dataSetCode: string, updateLoadingState: (isLoading: boolean) => void): FiltersState {
    const { compositionRoot } = useAppContext();
    const snackbar = useSnackbar();

    const [dataSets, setDataSets] = useState<AutogenConfigDataSets>({
        dataSetsWithExistingConfig: [],
        dataSetsWithoutConfig: [],
    });

    useEffect(() => {
        updateLoadingState(true);
        compositionRoot.dataStoreConfig
            .getDataSets()
            .then(dataSets => setDataSets(dataSets))
            .catch(error => snackbar.error(i18n.t(`Error fetching datasets: ${error.message}`)))
            .finally(() => updateLoadingState(false));
    }, [compositionRoot.dataStoreConfig, dataSetCode, snackbar, updateLoadingState]);

    const dataSetItems = useMemoOptionsFromDataSet(dataSets.dataSetsWithExistingConfig);
    const newDataSetItems = useMemoOptionsFromDataSet(dataSets.dataSetsWithoutConfig);

    return { dataSets: dataSetItems, newDataSets: newDataSetItems };
}

function useMemoOptionsFromDataSet(
    options: (CodedRef & { id: Id; hasCustomForm: boolean; canBeModified: boolean })[]
): Option[] {
    return useMemo(
        () =>
            options.map(option => ({
                value: option.code,
                text: option.name,
                id: option.id,
                hasCustomForm: option.hasCustomForm,
                canBeModified: option.canBeModified,
            })),
        [options]
    );
}
