import { useCallback, useEffect, useState } from "react";
import { useAppContext } from "../../../contexts/app-context";
import {
    CustomFormInstallState,
    parseVersionMarker,
} from "../../../../domain/autogenerated-forms-configurator/usecases/GetInstallStateUseCase";
import { useSnackbar } from "@eyeseetea/d2-ui-components";
import i18n from "@eyeseetea/d2-ui-components/locales";
import { Id } from "../../../../domain/common/entities/Base";

const BUNDLED_FORM_PATH = "./custom-data-form.html";

type InstallCustomFormState = {
    installState: CustomFormInstallState | undefined;
    bundledHtml: string | undefined;
    bundledVersion: string | undefined;
    isInstalling: boolean;
    installCustomForm: () => Promise<void>;
};

export function useInstallCustomForm(
    dataSetId: Id | undefined,
    updateLoadingState: (isLoading: boolean) => void
): InstallCustomFormState {
    const { compositionRoot } = useAppContext();
    const snackbar = useSnackbar();

    const [bundledHtml, setBundledHtml] = useState<string | undefined>(undefined);
    const [installState, setInstallState] = useState<CustomFormInstallState | undefined>(undefined);
    const [isInstalling, setIsInstalling] = useState(false);

    useEffect(() => {
        fetch(BUNDLED_FORM_PATH)
            .then(res => (res.ok ? res.text() : Promise.reject(new Error(`HTTP ${res.status}`))))
            .then(html => setBundledHtml(html))
            .catch(() => setBundledHtml(undefined));
    }, []);

    useEffect(() => {
        if (!dataSetId || !bundledHtml) {
            setInstallState(undefined);
            return;
        }

        updateLoadingState(true);
        compositionRoot.customForm
            .getInstallState(dataSetId, bundledHtml)
            .then(state => setInstallState(state))
            .catch(() => setInstallState(undefined))
            .finally(() => updateLoadingState(false));
    }, [compositionRoot.customForm, dataSetId, bundledHtml, updateLoadingState]);

    const installCustomForm = useCallback(async () => {
        if (!dataSetId || !bundledHtml) return;

        setIsInstalling(true);
        try {
            await compositionRoot.customForm.install(dataSetId, bundledHtml);
            snackbar.success(i18n.t("Custom form installed successfully"));
            const state = await compositionRoot.customForm.getInstallState(dataSetId, bundledHtml);
            setInstallState(state);
        } catch (error: unknown) {
            const message = error instanceof Error ? error.message : String(error);
            snackbar.error(i18n.t(`Error installing custom form: ${message}`));
        } finally {
            setIsInstalling(false);
        }
    }, [compositionRoot.customForm, dataSetId, bundledHtml, snackbar]);

    const bundledVersion = bundledHtml ? (parseVersionMarker(bundledHtml) ?? undefined) : undefined;

    return { installState, bundledHtml, bundledVersion, isInstalling, installCustomForm };
}
