import { useCallback, useRef, useState } from "react";
import { AutogenConfig } from "../../../../domain/autogenerated-forms-configurator/entities/AutogenConfig";

type JsonProcessorState = {
    error: string | null;
    isProcessing: boolean;
    formatJson: (config: AutogenConfig) => Promise<string>;
    parseJson: (json: string) => Promise<AutogenConfig>;
    validateJson: (json: string) => Promise<boolean>;
};

export const useJsonProcessor = (): JsonProcessorState => {
    const [isProcessing, setIsProcessing] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const cancelRef = useRef<boolean>(false);

    const processWithYielding = useCallback(async <T>(processor: () => T): Promise<T> => {
        return new Promise((resolve, reject) => {
            cancelRef.current = false;
            setIsProcessing(true);
            setError(null);

            const processChunk = () => {
                if (cancelRef.current) {
                    setIsProcessing(false);
                    reject(new Error("Processing cancelled"));
                    return;
                }

                try {
                    const result = processor();
                    setIsProcessing(false);
                    resolve(result);
                } catch (error) {
                    setIsProcessing(false);
                    const errorMessage = error instanceof Error ? error.message : "Processing error";
                    setError(errorMessage);
                    reject(error);
                }
            };

            requestAnimationFrame(() => {
                setTimeout(processChunk, 0);
            });
        });
    }, []);

    const formatJson = useCallback(
        async (config: AutogenConfig): Promise<string> => processWithYielding(() => JSON.stringify(config, null, 4)),
        [processWithYielding]
    );

    const parseJson = useCallback(
        async (json: string): Promise<AutogenConfig> =>
            processWithYielding(() => {
                if (!json.trim()) return null;
                return JSON.parse(json);
            }),
        [processWithYielding]
    );

    const validateJson = useCallback(
        async (json: string): Promise<boolean> => {
            return processWithYielding(() => {
                if (!json.trim()) return true;

                try {
                    const parsed = parseJson(json);
                    if (typeof parsed !== "object" || parsed === null) {
                        return false;
                    }

                    return true;
                } catch {
                    return false;
                }
            });
        },
        [parseJson, processWithYielding]
    );

    return {
        error: error,
        isProcessing: isProcessing,
        formatJson: formatJson,
        parseJson: parseJson,
        validateJson: validateJson,
    };
};
