import { useEffect, useMemo } from "react";
import { getValueAccordingType, useApplyRules } from "./useApplyRules";
import { DataElement, dataInputPeriodsType } from "../../../../domain/common/entities/DataElement";
import { DataFormInfo } from "../AutogeneratedForm";
import { Maybe } from "../../../../utils/ts-utils";
import { DataEntryItemProps } from "../DataEntryItem";
import { UseDeleteRuleReturn } from "./useDeleteDataValues";
import { STATE_CONDITIONS } from "../../../../domain/common/entities/DataElementRule";

type DataEntryItemState = {
    isDataEntryItemVisible: boolean;
    isDataEntryItemDisabled: boolean;
};

export function useDataEntryItem(
    props: DataEntryItemProps & Pick<UseDeleteRuleReturn, "deleteDataValues">
): DataEntryItemState {
    const { dataElement, dataFormInfo, lockException, manualyDisabled: handDisabled, period, deleteDataValues } = props;
    const { isVisible, isDisabled } = useApplyRules({ dataElement, dataFormInfo, period: period });

    const disabled = !handDisabled
        ? isInputExpired(
              props.period,
              dataFormInfo.period,
              dataFormInfo.metadata.dataForm.dataInputPeriods,
              dataFormInfo.metadata.dataForm.expiryDays,
              lockException ?? false
          )
        : handDisabled;

    const isInputDisabled = useMemo(
        () => isDisabled || disabled || Boolean(dataElement.disabled),
        [isDisabled, disabled, dataElement.disabled]
    );
    const isInputVisible = useMemo(
        () => isVisible && checkVisibleRelatedDataElement(dataElement, dataFormInfo, props.period),
        [isVisible, dataElement, dataFormInfo, props.period]
    );

    useEffect(() => {
        const clearRules = dataElement.rules.filter(rule => rule.type === "clear");
        if (clearRules.length === 0) return;

        const dataValue = dataFormInfo.data.values.getOrEmpty(dataElement, {
            orgUnitId: dataElement.orgUnit || dataFormInfo.orgUnitId,
            period: period || dataFormInfo.period,
            categoryOptionComboId: dataFormInfo.categoryOptionComboId,
        });

        const doClearOnDisabled =
            isInputDisabled &&
            clearRules.some(rule => rule.condition === STATE_CONDITIONS.disabled) &&
            getValueAccordingType(dataValue);
        if (!doClearOnDisabled) return;

        deleteDataValues([dataValue]);
    }, [isInputDisabled, dataElement, deleteDataValues, dataFormInfo, period]);

    return { isDataEntryItemVisible: isInputVisible, isDataEntryItemDisabled: isInputDisabled };
}

function checkVisibleRelatedDataElement(dataElement: DataElement, dataFormInfo: DataFormInfo, period: Maybe<string>) {
    if (dataElement.related) {
        const dataValue = dataFormInfo.data.values.getOrEmpty(dataElement.related.dataElement, {
            orgUnitId: dataElement.orgUnit || dataFormInfo.orgUnitId,
            period: period || dataFormInfo.period,
            categoryOptionComboId: dataFormInfo.categoryOptionComboId,
        });
        const value = getValueAccordingType(dataValue);
        return dataElement.related.value === String(value);
    }
    return true;
}

function isInputExpired(
    period: string | undefined,
    dataFormPeriod: string,
    dataInputPeriods: dataInputPeriodsType,
    expiryDays: number,
    lockException: boolean
) {
    if (lockException) return false;
    const periodToCheck = period ?? dataFormPeriod;

    const dataInputPeriod = dataInputPeriods?.find(p => p.period.id === periodToCheck);

    if (!dataInputPeriod || !dataInputPeriod?.closingDate) {
        return periodToCheck !== dataFormPeriod;
    } else {
        const closingDate = new Date(`${dataInputPeriod?.closingDate}Z`);
        closingDate.setDate(closingDate.getDate() + expiryDays);

        const now = new Date();

        return closingDate < now;
    }
}
