import { useMemo } from "react";
import { getValueAccordingType, useApplyRules } from "./useApplyRules";
import { useOrgUnitToggle } from "./useOrgUnitToggle";
import { DataElement, dataInputPeriodsType } from "../../../../domain/common/entities/DataElement";
import { DataFormInfo } from "../AutogeneratedForm";
import { Maybe } from "../../../../utils/ts-utils";
import { DataEntryItemProps } from "../DataEntryItem";

export function useDataEntryItem(props: DataEntryItemProps) {
    const { dataElement, dataFormInfo, lockException, manualyDisabled: handDisabled, period } = props;
    const { isVisible, isDisabled } = useApplyRules({ dataElement, dataFormInfo, period: period });
    const { isVisibleByOrgUnit, isDisabledByOrgUnit } = useOrgUnitToggle(dataFormInfo, dataElement);

    const disabled = !handDisabled
        ? isInputExpired(
              props.period,
              dataFormInfo.period,
              dataFormInfo.metadata.dataForm.dataInputPeriods,
              dataFormInfo.metadata.dataForm.expiryDays,
              lockException ?? false
          )
        : handDisabled;

    const isInputDisabled = useMemo(
        () => isDisabled || disabled || isDisabledByOrgUnit,
        [isDisabled, disabled, isDisabledByOrgUnit]
    );
    const isInputVisible = useMemo(
        () =>
            isVisible && isVisibleByOrgUnit && checkVisibleRelatedDataElement(dataElement, dataFormInfo, props.period),
        [isVisible, isVisibleByOrgUnit, dataElement, dataFormInfo, props.period]
    );

    return { isDataEntryItemVisible: isInputVisible, isDataEntryItemDisabled: isInputDisabled };
}

function checkVisibleRelatedDataElement(dataElement: DataElement, dataFormInfo: DataFormInfo, period: Maybe<string>) {
    if (dataElement.related) {
        const dataValue = dataFormInfo.data.values.getOrEmpty(dataElement.related.dataElement, {
            orgUnitId: dataElement.orgUnit || dataFormInfo.orgUnitId,
            period: period || dataFormInfo.period,
            categoryOptionComboId: dataFormInfo.categoryOptionComboId,
        });
        const value = getValueAccordingType(dataValue);
        return dataElement.related.value === String(value);
    }
    return true;
}

function isInputExpired(
    period: string | undefined,
    dataFormPeriod: string,
    dataInputPeriods: dataInputPeriodsType,
    expiryDays: number,
    lockException: boolean
) {
    if (lockException) return false;
    const periodToCheck = period ?? dataFormPeriod;

    const dataInputPeriod = dataInputPeriods?.find(p => p.period.id === periodToCheck);

    if (!dataInputPeriod || !dataInputPeriod?.closingDate) {
        return periodToCheck !== dataFormPeriod;
    } else {
        const closingDate = new Date(`${dataInputPeriod?.closingDate}Z`);
        closingDate.setDate(closingDate.getDate() + expiryDays);

        const now = new Date();

        return closingDate < now;
    }
}
