import React from "react";
import _ from "lodash";

import { DataElement } from "../../../../domain/common/entities/DataElement";
import { DataFormInfo } from "../AutogeneratedForm";
import { verifyConditionByDataValueType } from "./useApplyRules";
import { DataValue } from "../../../../domain/common/entities/DataValue";

type UseDeleteRulesProps = {
    dataElement: DataElement;
    dataFormInfo: DataFormInfo;
    period?: string;
};

type UseDeleteRuleReturn = {
    applyDeleteRule: (dataValue: DataValue) => Promise<void>;
    deleteRuleInProgress: boolean;
};

export function useDeleteRule(props: UseDeleteRulesProps): UseDeleteRuleReturn {
    const { dataElement, dataFormInfo, period } = props;
    const [deleteRuleInProgress, setDeleteRuleInProgress] = React.useState(false);

    const applyDeleteRule = React.useCallback(
        async (dataValueCb: DataValue) => {
            if (dataElement.deleteRules.length === 0) return;
            setDeleteRuleInProgress(true);

            const runDelete = dataFormInfo.data.delete;

            const allDataValuesToDelete = dataElement.deleteRules.flatMap(rule => {
                const shouldDelete = verifyConditionByDataValueType(dataValueCb, rule);
                if (shouldDelete) {
                    return rule.dataElements.flatMap(deId =>
                        _(dataFormInfo.data.values.store)
                            .filter(
                                dataValue =>
                                    dataValue.dataElement.code === deId &&
                                    dataValue.orgUnitId === dataFormInfo.orgUnitId
                            )
                            .compact()
                            .value()
                    );
                } else return [];
            });
            await runDelete(allDataValuesToDelete);
            setDeleteRuleInProgress(false);
        },
        [dataElement, dataFormInfo, period]
    );

    return {
        applyDeleteRule,
        deleteRuleInProgress,
    };
}
