import React from "react";
import _ from "lodash";

import { DataElement } from "../../../../domain/common/entities/DataElement";
import { DataFormInfo } from "../AutogeneratedForm";
import { verifyConditionByDataValueType } from "./useApplyRules";
import { DataValue } from "../../../../domain/common/entities/DataValue";

type UseDeleteRulesProps = {
    dataElement: DataElement;
    dataFormInfo: DataFormInfo;
    period?: string;
};

export type UseDeleteRuleReturn = {
    applyDeleteRule: (dataValue: DataValue) => Promise<void>;
    deleteDataValues: (dataValues: DataValue[]) => Promise<void>;
    deleteRuleInProgress: boolean;
};

export function useDeleteDataValues(props: UseDeleteRulesProps): UseDeleteRuleReturn {
    const { dataElement, dataFormInfo } = props;
    const [deleteRuleInProgress, setDeleteRuleInProgress] = React.useState(false);

    const deleteDataValues = React.useCallback(
        async (dataValuesToDelete: DataValue[]) => {
            const runDelete = dataFormInfo.data.delete;

            await runDelete(dataValuesToDelete).catch(err => {
                console.error("Error applying delete rules", err);
            });
        },
        [dataFormInfo]
    );

    const applyDeleteRule = React.useCallback(
        async (dataValueCb: DataValue) => {
            if (dataElement.deleteRules.length === 0) return;
            setDeleteRuleInProgress(true);

            const allDataValuesToDelete = dataElement.deleteRules.flatMap(rule => {
                const shouldDelete = verifyConditionByDataValueType(dataValueCb, rule);
                if (!shouldDelete) return [];
                return rule.dataElements.flatMap(deId =>
                    _(dataFormInfo.data.values.store)
                        .filter(
                            dataValue =>
                                dataValue.dataElement.code === deId &&
                                dataValue.orgUnitId === dataFormInfo.orgUnitId &&
                                dataValue.period === dataValueCb.period
                        )
                        .compact()
                        .value()
                );
            });
            await deleteDataValues(allDataValuesToDelete).finally(() => {
                setDeleteRuleInProgress(false);
            });
        },
        [dataElement, dataFormInfo, deleteDataValues]
    );

    return {
        applyDeleteRule,
        deleteRuleInProgress,
        deleteDataValues,
    };
}
