import { useMemo } from "react";
import { DataElement } from "../../../../domain/common/entities/DataElement";
import { DataFormInfo } from "../AutogeneratedForm";

type OrgUnitToggleState = {
    isVisibleByOrgUnit: boolean;
    isDisabledByOrgUnit: boolean;
};

export function useOrgUnitToggle(dataFormInfo: DataFormInfo, dataElement: DataElement): OrgUnitToggleState {
    const section = useMemo(
        () =>
            dataFormInfo.metadata.dataForm.sections.find(section =>
                section.dataElements.some(de => de.id === dataElement.id)
            ),
        [dataFormInfo.metadata.dataForm.sections, dataElement.id]
    );
    if (!section) return getOUToggleState(false, true);

    const { toggle } = section;
    if (toggle.type !== "orgUnit") return getOUToggleState(false, true);
    if (toggle.dataElements.length === 0 && toggle.disabled) return getOUToggleState(true, true);

    const orgUnitCode = dataFormInfo.metadata.dataForm.orgUnit.code;
    if (!orgUnitCode) {
        console.warn(`Org unit ${dataFormInfo.metadata.dataForm.orgUnit.name} has no code`);
        return getOUToggleState(false, true);
    }
    const isOrgUnitInToggleList = toggle.orgUnits.includes(orgUnitCode);
    const dataElementExistsInToggle = toggle.dataElements.includes(dataElement.code);

    switch (toggle.condition) {
        case "hide": {
            if (isOrgUnitInToggleList && dataElementExistsInToggle) {
                if (toggle.disabled) return getOUToggleState(true, true);
                return getOUToggleState(false, false);
            }
            return getOUToggleState(false, true);
        }
        case "show": {
            if (isOrgUnitInToggleList && dataElementExistsInToggle) return getOUToggleState(false, true);
            else {
                if (toggle.disabled) return getOUToggleState(true, true);
                return getOUToggleState(false, false);
            }
        }
    }
}

const getOUToggleState = (isDisabled: boolean, isVisible: boolean): OrgUnitToggleState => ({
    isDisabledByOrgUnit: isDisabled,
    isVisibleByOrgUnit: isVisible,
});
