import React from "react";
import { DataFormInfo } from "../AutogeneratedForm";

type UseSectionRuleActionsResult = {
    messages: string[];
};

export function useSectionRuleActions({
    sectionId,
    dataFormInfo,
}: {
    sectionId: string;
    dataFormInfo: DataFormInfo;
}): UseSectionRuleActionsResult {
    return React.useMemo<UseSectionRuleActionsResult>(() => {
        const section = dataFormInfo.metadata.dataForm.sections.find(s => s.id === sectionId);
        const messages =
            section?.rules.filter(rule => rule.action.type === "showMessage").map(rule => rule.action.text) ?? [];
        return {
            messages: messages,
        };
    }, [sectionId, dataFormInfo]);
}
