import { useMemo } from "react";
import { Section } from "../../../../domain/common/entities/DataForm";
import { DataElementToggle } from "../../../../domain/common/entities/ToggleMultiple";
import { DataFormInfo } from "../AutogeneratedForm";
import { evaluateTotalRule, verifyConditionByDataValueType } from "./useApplyRules";
import { isDataValueEnabled } from "../DataElementItem";
import { DataTableSectionObj } from "../DataTableSection";

export type SectionVisibilityState = {
    isDisabled: boolean;
    isOpen: boolean;
    isVisible: boolean;
};

export function useSectionVisibility(section: DataTableSectionObj, dataFormInfo: DataFormInfo): SectionVisibilityState {
    const { toggle, toggleMultiple } = section;
    const sectionTotalRules = useMemo(
        () =>
            dataFormInfo.metadata.dataForm.totalRules.sectionTotalRules.filter(sectionTotalRule =>
                sectionTotalRule.sections.includes(section.id)
            ),
        [dataFormInfo, section.id]
    );

    const isDisabled = useMemo(() => {
        if (toggle.type === "none" && !toggleMultiple) return false;
        if (toggleMultiple) {
            const isVisibleFromToggleMultiple = evaluateToggleMultiple(dataFormInfo, toggleMultiple);
            if (!isVisibleFromToggleMultiple) {
                const hasDisabledFlag = toggleMultiple.toggleDataElements.some(t => t.dataElement.disabled);
                return hasDisabledFlag;
            }
            return false;
        }
        return toggle.type !== "none" ? toggle.disabled : false;
    }, [toggle, toggleMultiple, dataFormInfo]);

    const isOpen = useMemo(() => {
        return evaluateSectionOpenState(toggle, dataFormInfo);
    }, [toggle, dataFormInfo]);

    const isVisibleFromTotals = useMemo(() => {
        if (sectionTotalRules.length === 0) return true;
        return sectionTotalRules.map(rule => evaluateTotalRule(rule, dataFormInfo)).some(value => value);
    }, [dataFormInfo, sectionTotalRules]);

    const isVisible = useMemo(() => {
        if (section.hidden) return !section.hidden;
        if (toggle.type === "dataElementExternal" && !isOpen) return false;
        if (sectionTotalRules.length > 0 && !isVisibleFromTotals) return false;
        if (toggleMultiple) {
            const isVisibleFromToggleMultiple = evaluateToggleMultiple(dataFormInfo, toggleMultiple);
            if (!isVisibleFromToggleMultiple) {
                const hasDisabledFlag = toggleMultiple.toggleDataElements.some(t => t.dataElement.disabled);
                return hasDisabledFlag;
            }
            return true;
        }

        return true;
    }, [
        section.hidden,
        toggle.type,
        isOpen,
        sectionTotalRules.length,
        isVisibleFromTotals,
        toggleMultiple,
        dataFormInfo,
    ]);

    return { isDisabled: isDisabled, isOpen: isOpen, isVisible: isVisible };
}

function evaluateSectionOpenState(toggle: Section["toggle"], dataFormInfo: DataFormInfo): boolean {
    switch (toggle.type) {
        case "dataElement": {
            const dataValue = dataFormInfo.data.values.getOrEmpty(toggle.dataElement, dataFormInfo);
            return isDataValueEnabled(dataValue);
        }
        case "dataElementExternal": {
            const dataValue = dataFormInfo.data.values.getOrEmpty(toggle.dataElement, dataFormInfo);
            return verifyConditionByDataValueType(dataValue, toggle);
        }
        default:
            return true;
    }
}

function evaluateToggleMultiple(dataFormInfo: DataFormInfo, toggleMultiple: DataElementToggle): boolean {
    const hasToggleDataElements = toggleMultiple.toggleDataElements.length > 0;
    if (!hasToggleDataElements) return true;

    const currentOrgUnitCode = dataFormInfo.orgUnit.code;
    const { logicalOperator, toggleDataElements } = toggleMultiple;

    const evaluateToggleCondition = (toggle: DataElementToggle["toggleDataElements"][number]): boolean => {
        switch (toggle.type) {
            case "orgUnit": {
                const isOrgUnitInToggleList = toggle.orgUnitCodes.includes(currentOrgUnitCode);
                return toggle.condition === "show" ? isOrgUnitInToggleList : !isOrgUnitInToggleList;
            }
            case "dataElement": {
                const dataValue = dataFormInfo.data.values.getOrEmpty(toggle.dataElement, dataFormInfo);
                return verifyConditionByDataValueType(dataValue, toggle);
            }
        }
    };

    switch (logicalOperator) {
        case "AND":
            return toggleDataElements.every(evaluateToggleCondition);
        case "OR":
            return toggleDataElements.some(evaluateToggleCondition);
    }
}
