import { useMemo } from "react";
import { Section } from "../../../../domain/common/entities/DataForm";
import { DataElementToggle } from "../../../../domain/common/entities/ToggleMultiple";
import { DataFormInfo } from "../AutogeneratedForm";
import { evaluateTotalRule, verifyConditionByDataValueType } from "./useApplyRules";
import { isDataValueEnabled } from "../DataElementItem";
import { DataTableSectionObj } from "../DataTableSection";

export type SectionVisibilityState = {
    isDisabled: boolean;
    isOpen: boolean;
    isVisible: boolean;
};

export function useSectionVisibility(section: DataTableSectionObj, dataFormInfo: DataFormInfo): SectionVisibilityState {
    return useMemo(() => getSectionVisibilityState(section, dataFormInfo), [section, dataFormInfo]);
}

type SectionVisibilityInput = {
    id: DataTableSectionObj["id"];
    hidden?: DataTableSectionObj["hidden"];
    toggle: DataTableSectionObj["toggle"];
    toggleMultiple?: DataTableSectionObj["toggleMultiple"];
};

export function getSectionVisibilityState(
    section: SectionVisibilityInput,
    dataFormInfo: DataFormInfo
): SectionVisibilityState {
    const { toggle, toggleMultiple } = section;
    const sectionTotalRules = dataFormInfo.metadata.dataForm.totalRules.sectionTotalRules.filter(sectionTotalRule =>
        sectionTotalRule.sections.includes(section.id)
    );

    const isOpen = evaluateSectionOpenState(toggle, dataFormInfo);

    const isVisibleFromTotals =
        sectionTotalRules.length === 0
            ? true
            : sectionTotalRules.map(rule => evaluateTotalRule(rule, dataFormInfo)).some(value => value);
    const toggleMultipleState = toggleMultiple ? evaluateToggleMultipleState(dataFormInfo, toggleMultiple) : undefined;

    const isDisabled = (() => {
        if (toggle.type === "none" && !toggleMultiple) return false;
        if (toggleMultiple) {
            return toggleMultipleState?.isVisible ? Boolean(toggleMultipleState?.isDisabled) : false;
        }
        return toggle.type !== "none" ? toggle.disabled : false;
    })();

    const isVisible = (() => {
        if (section.hidden) return !section.hidden;
        if (toggle.type === "dataElementExternal" && !isOpen) return false;
        if (sectionTotalRules.length > 0 && !isVisibleFromTotals) return false;
        if (toggleMultiple) {
            return Boolean(toggleMultipleState?.isVisible);
        }

        return true;
    })();

    return { isDisabled, isOpen, isVisible };
}

function evaluateSectionOpenState(toggle: Section["toggle"], dataFormInfo: DataFormInfo): boolean {
    switch (toggle.type) {
        case "dataElement": {
            const dataValue = dataFormInfo.data.values.getOrEmpty(toggle.dataElement, dataFormInfo);
            return isDataValueEnabled(dataValue);
        }
        case "dataElementExternal": {
            const dataValue = dataFormInfo.data.values.getOrEmpty(toggle.dataElement, dataFormInfo);
            return verifyConditionByDataValueType(dataValue, toggle);
        }
        default:
            return true;
    }
}

type ToggleMultipleConditionState = {
    isMatch: boolean;
    isDisabled: boolean;
    affectsVisibility: boolean;
};

function evaluateToggleMultipleState(
    dataFormInfo: DataFormInfo,
    toggleMultiple: DataElementToggle
): { isVisible: boolean; isDisabled: boolean } {
    const currentOrgUnitCode = dataFormInfo.orgUnit.code;
    const { logicalOperator, toggleDataElements, orgUnitConditions } = toggleMultiple;
    const conditions: ToggleMultipleConditionState[] = [
        ...toggleDataElements.map(toggle => {
            const isMatch = evaluateToggleCondition(toggle, dataFormInfo, currentOrgUnitCode);
            const isDisabled = Boolean(toggle.dataElement.disabled);
            return { isMatch, isDisabled, affectsVisibility: !isDisabled };
        }),
        ...orgUnitConditions.map(condition => {
            const isMatch = evaluateOrgUnitCondition(condition.orgUnitCodes, condition.condition, currentOrgUnitCode);
            const isDisabled = Boolean(condition.disabled);
            return { isMatch, isDisabled, affectsVisibility: !isDisabled };
        }),
    ];

    const visibilityConditions = conditions.filter(condition => condition.affectsVisibility);
    const isVisible = (() => {
        if (visibilityConditions.length === 0) return true;
        switch (logicalOperator) {
            case "AND":
                return visibilityConditions.every(condition => condition.isMatch);
            case "OR":
                return visibilityConditions.some(condition => condition.isMatch);
        }
    })();

    const isDisabled = conditions.some(condition => condition.isDisabled && condition.isMatch);
    return { isVisible, isDisabled };
}

function evaluateToggleCondition(
    toggle: DataElementToggle["toggleDataElements"][number],
    dataFormInfo: DataFormInfo,
    currentOrgUnitCode: string
): boolean {
    switch (toggle.type) {
        case "orgUnit": {
            return evaluateOrgUnitCondition(toggle.orgUnitCodes, toggle.condition, currentOrgUnitCode);
        }
        case "dataElement": {
            const dataValue = dataFormInfo.data.values.getOrEmpty(toggle.dataElement, dataFormInfo);
            return verifyConditionByDataValueType(dataValue, toggle);
        }
    }
}

function evaluateOrgUnitCondition(orgUnitCodes: string[], condition: string, currentOrgUnitCode: string): boolean {
    const isOrgUnitInToggleList = orgUnitCodes.includes(currentOrgUnitCode);
    return condition === "show" ? isOrgUnitInToggleList : !isOrgUnitInToggleList;
}
