import _ from "lodash";
import { useMemo } from "react";
import { Section } from "../../../../domain/common/entities/DataForm";
import { getTabIndices, isTabHeader, TabPanelProps } from "../SectionsTabs";
import { DataFormInfo } from "../AutogeneratedForm";
import { getSectionVisibilityState } from "./useSectionVisibility";
import { calculateFormula } from "../datatables/InputFormula";
import { Maybe } from "../../../../utils/ts-utils";

export interface VisibleTab {
    readonly primaryIndex: number;
    readonly label: string;
}

type TabVisibilityState = {
    tabVisibilityByIndex: Record<number, boolean>;
    firstVisibleTabIndex: Maybe<number>;
    visiblePrimaryTabs: ReadonlyArray<VisibleTab>;
};

export function useTabVisibility(props: TabPanelProps): TabVisibilityState {
    const { tabbedSections, untabbedSections, dataFormInfo } = props;

    const tabVisibilityByIndex = useMemo(() => {
        const acc = tabbedSections.reduce<Record<number, boolean>>((acc, section) => {
            const [primaryTabIndex] = getTabIndices(section.tabs.order);
            if (!Number.isFinite(primaryTabIndex) || primaryTabIndex === -1) return acc;

            const { isVisible } = getSectionVisibilityState(section, dataFormInfo);
            if (isVisible) acc[primaryTabIndex] = true;

            return acc;
        }, {});

        const hasVisibleUntabbedSection = untabbedSections.some(
            section => getSectionVisibilityState(section, dataFormInfo).isVisible
        );
        if (hasVisibleUntabbedSection) acc[-1] = true;

        return acc;
    }, [tabbedSections, untabbedSections, dataFormInfo]);

    const sortedVisibleTabIndices = useMemo(
        () =>
            Object.keys(tabVisibilityByIndex)
                .map(Number)
                .filter(Number.isFinite)
                .sort((a, b) => a - b),
        [tabVisibilityByIndex]
    );

    const firstVisibleTabIndex = sortedVisibleTabIndices[0];

    const visiblePrimaryTabs: ReadonlyArray<VisibleTab> = useMemo(() => {
        return _.uniqBy(
            tabbedSections.flatMap(section => {
                if (!isTabHeader(section.tabs.order)) return [];

                const primaryValue = _(section.tabs.order).split(".").first() ?? "0";
                const primaryIndex = Number(primaryValue);
                if (!Number.isFinite(primaryIndex) || primaryIndex === -1) return [];
                if (!tabVisibilityByIndex[primaryIndex]) return [];

                if (!isFormulaVisible(section, dataFormInfo)) return [];

                const label = section.texts.tabLabel || section.name;
                return [{ primaryIndex, label }];
            }),
            tab => tab.primaryIndex
        );
    }, [tabbedSections, tabVisibilityByIndex, dataFormInfo]);

    return { tabVisibilityByIndex, firstVisibleTabIndex, visiblePrimaryTabs };
}

function isFormulaVisible(section: Section, dataFormInfo: DataFormInfo): boolean {
    const visibleRule = section.tabs.rules?.visible;
    if (!visibleRule) return true;

    const dataElementCodes = visibleRule.dataElements.map(de => de.code);
    const value =
        dataElementCodes.length > 0
            ? calculateFormula({
                  dataElementCodes,
                  dataFormInfo,
                  formula: visibleRule.formula.value,
              })
            : undefined;

    return value === visibleRule.formula.condition;
}
