import { defaultObjectProperties } from "..";
import { DataElementSchema } from "../../../../../domain/autogenerated-forms-configurator/entities/DataElement";
import { dataElementSchema } from "./dataElement";

export const getDataElementSchema = (dataElements: DataElementSchema[], constants: string[]) => {
    return defaultObjectProperties({ properties: dataElementSchema(dataElements, constants) });
};
