import React from "react";
import AutogeneratedForm from "./autogenerated-forms/AutogeneratedForm";
import { getVariant } from "./variants";

const widget = getVariant();

const Component: React.FC = () => {
    switch (widget) {
        case "autogenerated-forms": {
            return <AutogeneratedForm />;
        }
        default: {
            return <AutogeneratedForm />;
        }
    }
};

function Reports() {
    return <Component />;
}

export default Reports;
