import { isElementOfUnion, UnionFromValues } from "../../utils/ts-utils";

const reportVariants = ["autogenerated-forms"] as const;

export type ReportVariant = UnionFromValues<typeof reportVariants>;

export function getVariant(): ReportVariant {
    const value = process.env.REACT_APP_REPORT_VARIANT || "";
    return isElementOfUnion(value, reportVariants) ? value : reportVariants[0];
}
