import React, { useCallback, useEffect, useRef, useState } from "react";

import { useAppContext } from "../../contexts/app-context";

import {
    DataForm,
    DataFormM,
    SectionWithIndicatorsCalculated,
    SectionWithSubnationals,
} from "../../../domain/common/entities/DataForm";
import {
    DataValue,
    DataValueNumberSingle,
    DataValueStore,
    DataValueTextMultiple,
    Period,
} from "../../../domain/common/entities/DataValue";
import { useDataEntrySelector } from "./useDataEntrySelector";
import i18n from "@eyeseetea/d2-ui-components/locales";
import GridForm from "./GridForm";
import { assertUnreachable, Maybe } from "../../../utils/ts-utils";
import { Id } from "../../../domain/common/entities/Base";
import TableForm from "./TableForm";
import SectionsTabs from "./SectionsTabs";
import { useBooleanState } from "../../utils/use-boolean";
import { LinearProgress } from "@material-ui/core";
import GridWithPeriods from "./GridWithPeriods";
import { Html } from "./Html";
import _ from "lodash";
import GridWithTotals from "./GridWithTotals";
import GridWithCombos from "./GridWithCombos";
import { DataElementRefType } from "../../../domain/common/repositories/DataValueRepository";
import { DataElement } from "../../../domain/common/entities/DataElement";
import { Row } from "./GridWithTotalsViewModel";
import GridWithSubNational from "./GridWithSubNational";
import GridWithCatOptionCombos from "./GridWithCatOptionCombos";
import { AlertRules } from "../../components/alert-rule/AlertRules";
import MatrixGridForm from "./MatrixGridForm";
import DisaggregatedCOCsGrid from "./DisaggregatedCOCsGrid";
import GridIndicatorsCalculated from "./GridIndicatorsCalculated";
import GridWithCategoryColumns from "./GridWithCategoryColumns";
import { useValidationRules } from "./hooks/useValidationRules";
import { useRemovePrefixOnRunValidations } from "./hooks/useOnRunValidation";
import { OrgUnit } from "../../../domain/common/entities/OrgUnit";
import { useDataFormRuleActions } from "./hooks/useDataFormRuleActions";
import { Modal } from "../../components/modal/Modal";
import { useDataFormCustomCss } from "./hooks/useDataFormCustomCss";
import { useParentDataEntryAppStyles } from "./hooks/useParentDataEntryAppStyles";
import { FormInfo } from "./FormInfo";

const AutogeneratedForm: React.FC = () => {
    const { dataFormInfo, isLoading, loadingCompulsory, rules, ignoreRules, onCloseAlert } = useDataFormInfo();
    const dataFormRuleActions = useDataFormRuleActions(dataFormInfo?.metadata.dataForm);
    useDataFormCustomCss(dataFormInfo?.metadata.dataForm);
    useParentDataEntryAppStyles();
    if (!dataFormInfo) return <div>{i18n.t("Loading...")}</div>;
    const { dataForm } = dataFormInfo.metadata;
    if (dataForm.sections.length === 0)
        return <p>{i18n.t("There are no sections in this data set. Check README for more details")}</p>;

    const tabSectionsMap = dataForm.sections.flatMap(section => {
        const { tabs } = section;
        if (tabs.active === true) {
            return section;
        } else {
            return [];
        }
    });

    const sectionsMap = dataForm.sections.flatMap(section => {
        const { tabs } = section;
        if (tabs.active === false) {
            return section;
        } else {
            return [];
        }
    });

    return (
        <div ref={dataFormInfo.initForm} data-autogen-form-id={dataForm.id}>
            {<LinearProgress style={isLoading || loadingCompulsory ? styles.visible : styles.invisible} />}

            <CommentDialogStyles />
            <AlertRules rules={rules} ignoreRules={ignoreRules} onCloseAlert={onCloseAlert} />
            <FormInfo />

            <Html content={dataForm.texts.header} />

            {tabSectionsMap.length !== 0 ? (
                <div key={dataFormInfo.period + "tabs"}>
                    <SectionsTabs
                        dataFormInfo={dataFormInfo}
                        tabbedSections={tabSectionsMap}
                        untabbedSections={sectionsMap}
                    />
                </div>
            ) : (
                <div key={dataFormInfo.period}>
                    {sectionsMap.map(section => {
                        const { viewType } = section;
                        switch (viewType) {
                            case "table":
                                return <TableForm key={section.id} dataFormInfo={dataFormInfo} section={section} />;
                            case "grid":
                                return <GridForm key={section.id} dataFormInfo={dataFormInfo} section={section} />;
                            case "grid-with-periods":
                                return (
                                    <GridWithPeriods key={section.id} dataFormInfo={dataFormInfo} section={section} />
                                );
                            case "grid-with-totals":
                                return (
                                    <GridWithTotals
                                        key={`${section.id}+tab`}
                                        dataFormInfo={dataFormInfo}
                                        section={section}
                                    />
                                );
                            case "matrix-grid":
                                return (
                                    <MatrixGridForm key={section.id} dataFormInfo={dataFormInfo} section={section} />
                                );
                            case "grid-with-combos":
                                return (
                                    <GridWithCombos key={section.id} dataFormInfo={dataFormInfo} section={section} />
                                );
                            case "grid-with-cat-option-combos":
                                return (
                                    <GridWithCatOptionCombos
                                        key={`${section.id}+tab`}
                                        dataFormInfo={dataFormInfo}
                                        section={section}
                                    />
                                );

                            case "grid-disaggregated-cocs":
                                return (
                                    <DisaggregatedCOCsGrid
                                        key={`${section.id}+tab`}
                                        dataFormInfo={dataFormInfo}
                                        section={section}
                                    />
                                );
                            case "grid-with-subnational-ous":
                                return (
                                    <GridWithSubNational
                                        key={`${section.id}+tab`}
                                        dataFormInfo={dataFormInfo}
                                        section={section as SectionWithSubnationals}
                                    />
                                );
                            case "grid-indicators-calculated":
                                return (
                                    <GridIndicatorsCalculated
                                        key={`${section.id}+tab`}
                                        dataFormInfo={dataFormInfo}
                                        section={section as SectionWithIndicatorsCalculated}
                                    />
                                );
                            case "grid-category-columns":
                                return (
                                    <GridWithCategoryColumns
                                        key={`${section.id}+tab`}
                                        dataFormInfo={dataFormInfo}
                                        section={section}
                                    />
                                );
                            default:
                                assertUnreachable(viewType);
                        }
                    })}
                </div>
            )}

            <Html content={dataForm.texts.footer} />

            {dataFormRuleActions.displayWarning && (
                <Modal
                    dismissable={!dataFormRuleActions.displayWarning.blockEntry}
                    text={dataFormRuleActions.displayWarning.text}
                />
            )}
        </div>
    );
};

function useDataFormInfo() {
    const { compositionRoot, config } = useAppContext();
    const { orgUnitId, period, dataSetId, reloadKey, initForm } = useDataEntrySelector();

    const [dataForm, setDataForm] = useState<DataForm>();
    const [dataValues, setDataValues] = useState<DataValueStore>();
    const dataValuesRef = useRef<Maybe<DataValueStore>>(undefined);
    const totalSaveQueuesRef = useRef(new Map<string, Promise<void>>());

    useEffect(() => {
        dataValuesRef.current = dataValues;
    }, [dataValues]);

    const [isLoading, loadingActions] = useBooleanState(false);
    const [orgUnit, setOrgUnit] = useState<OrgUnit>();

    const [loadingCompulsory, setLoadingCompulsory] = React.useState(false);

    const { rules, ignoreRules, onCloseAlert, checkValidationRules, resetRules } = useValidationRules({
        dataForm,
    });

    useRemovePrefixOnRunValidations(dataForm?.removePrefix || "");

    const defaultCategoryOptionComboId = config.categoryOptionCombos.default.id;

    const orgUnits = React.useMemo(() => {
        return _(dataForm?.sections)
            .flatMap(section => (section.viewType === "grid-with-subnational-ous" ? section.subNationals : []))
            .map(de => de.id)
            .compact()
            .value();
    }, [dataForm]);

    React.useEffect(() => {
        if (!dataForm) return;
        // add event listener to button #completeButton
        const completeButton = document.getElementById("completeButton");
        const incompleteButton = document.getElementById("undoButton");
        function handleCompleteButtonClick() {
            // Data Entry display a different popup error for custom forms after complete/incomplete action
            document.querySelector("#headerMessage")?.remove();
            setLoadingCompulsory(true);
            compositionRoot.dataForms
                .getValues(dataSetId, {
                    orgUnits: orgUnits.length > 0 ? orgUnits : [orgUnitId],
                    periods: dataForm ? DataFormM.getReferencedPeriods(dataForm, period) : [],
                })
                .then(({ store, dataValues }) => {
                    const requiredDataValues = dataValues.filter(dv => dv.isRequired);
                    if (requiredDataValues.length > 0 && dataForm?.showErrorOnCompulsory) {
                        window.dhis2?.de.displayValidationDialog(
                            `<h3>Validation Result &nbsp;<img src="../images/warning_small.png"></h3><p class="bold">This form has compulsory fields. Please fill those items marked red in the form.</p>`,
                            300
                        );
                    }
                    setDataValues(store);
                    setLoadingCompulsory(false);
                })
                .catch(() => {
                    setLoadingCompulsory(false);
                });
        }
        completeButton?.addEventListener("click", handleCompleteButtonClick);
        incompleteButton?.addEventListener("click", handleCompleteButtonClick);

        return () => {
            completeButton?.removeEventListener("click", handleCompleteButtonClick);
            incompleteButton?.removeEventListener("click", handleCompleteButtonClick);
        };
    }, [dataForm, orgUnits, compositionRoot.dataForms, dataSetId, orgUnitId, period]);

    React.useEffect(() => {
        // Hiding arrows for input of type number
        // adding directly to css works in dev, but not in data entry.
        const css =
                'input::-webkit-outer-spin-button,input::-webkit-inner-spin-button {-webkit-appearance: none !important; margin: 0; } input[type=number] { -moz-appearance: textfield !important; }[data-test="dhis2-uicore-layer"] {z-index: 10 !important;}',
            head = document.head || document.getElementsByTagName("head")[0],
            style = document.createElement("style");
        style.setAttribute("id", "disabled-arrows-css");
        style.appendChild(document.createTextNode(css));
        head.appendChild(style);

        function disableScrollInputs() {
            if (
                window.document.activeElement instanceof HTMLInputElement &&
                window.document.activeElement.type === "number" &&
                window.document.activeElement.classList.contains("noscroll")
            ) {
                window.document.activeElement.blur();
            }
        }

        document.addEventListener("wheel", disableScrollInputs);

        return () => {
            document.removeEventListener("wheel", disableScrollInputs);
        };
    }, []);

    useEffect(() => {
        compositionRoot.dataForms.get({ dataSetId, period, orgUnitId }).then(({ dataForm, orgUnit }) => {
            setDataForm(dataForm);
            setOrgUnit(orgUnit);
        });
    }, [compositionRoot, dataSetId, period, orgUnitId]);

    useEffect(() => {
        if (!dataForm) return;

        loadingActions.enable();
        compositionRoot.dataForms
            .getValues(dataForm.id, {
                orgUnits: orgUnits.length > 0 ? orgUnits : [orgUnitId],
                periods: DataFormM.getReferencedPeriods(dataForm, period),
            })
            .then(({ store }) => {
                resetRules();
                setDataValues(undefined);
                setDataValues(store);
            })
            .finally(() => {
                loadingActions.disable();
            });
    }, [dataForm, orgUnits, compositionRoot, orgUnitId, period, reloadKey, loadingActions, resetRules]);

    const saveDataValue = useCallback<DataFormInfo["data"]["save"]>(
        async (dataValue: DataValue) => {
            if (!dataValues) return dataValues;
            await compositionRoot.dataForms
                .saveValue(dataValues, dataValue, dataForm?.compulsoryDataValues ?? [])
                .then(savedValue => {
                    setDataValues(prev => {
                        if (!prev) return prev;
                        return prev.set(savedValue);
                    });
                });
            if (!dataForm?.disableAutoValidation) {
                checkValidationRules(dataValue);
            }
        },
        [
            compositionRoot,
            dataValues,
            dataForm?.compulsoryDataValues,
            dataForm?.disableAutoValidation,
            checkValidationRules,
        ]
    );

    const deleteDataValues = useCallback<DataFormInfo["data"]["delete"]>(
        async (dataValuesToDelete: DataValue[]) => {
            if (!dataValues) return dataValues;
            await compositionRoot.dataForms.deleteValues(dataValuesToDelete).then(savedDataValues => {
                setDataValues(prev => {
                    if (!prev) return undefined;
                    return prev.merge(savedDataValues);
                });
            });
        },
        [compositionRoot, dataValues]
    );

    const SourceTypeApplyToAll = useCallback<DataFormInfo["data"]["stApplyToAll"]>(
        async (dataValue: DataValueTextMultiple, sourceTypeDEs: DataElementRefType[], rows: Row[]) => {
            if (!dataValues) return undefined;
            return compositionRoot.dataForms
                .applyToAll(dataValues, dataValue, sourceTypeDEs, rows)
                .then(savedDataValues => {
                    setDataValues(prev => {
                        if (!prev) return undefined;
                        return prev.merge(savedDataValues);
                    });
                });
        },
        [compositionRoot, dataValues]
    );

    const saveWithTotals = useCallback<DataFormInfo["data"]["saveWithTotals"]>(
        (dataValue, columnTotal, columnDataElements, cocId) => {
            const queues = totalSaveQueuesRef.current;
            const previousSave = queues.get(columnTotal.id) ?? Promise.resolve();

            const currentSave = previousSave
                .catch(error => console.error(`Failed to save totals for column ${columnTotal.id}`, error)) // a failed save must not block later saves in the column
                .then(async () => {
                    const store = dataValuesRef.current;
                    if (!store) return;

                    const savedDataValues = await compositionRoot.dataForms.saveWithTotals(
                        store,
                        dataValue,
                        columnTotal,
                        columnDataElements,
                        cocId
                    );

                    setDataValues(prev => (prev ?? store).merge(savedDataValues));
                    dataValuesRef.current = (dataValuesRef.current ?? store).merge(savedDataValues);

                    if (!dataForm?.disableAutoValidation) {
                        checkValidationRules(dataValue);
                    }
                });

            queues.set(columnTotal.id, currentSave);
            return currentSave;
        },
        [compositionRoot, dataForm?.disableAutoValidation, checkValidationRules]
    );

    const dataFormInfo = React.useMemo<Maybe<DataFormInfo>>(
        () =>
            dataForm && dataValues && orgUnit
                ? {
                      metadata: { dataForm },
                      data: {
                          values: dataValues,
                          save: saveDataValue,
                          delete: deleteDataValues,
                          stApplyToAll: SourceTypeApplyToAll,
                          saveWithTotals: saveWithTotals,
                      },
                      initForm,
                      orgUnitId,
                      orgUnit,
                      period,
                      categoryOptionComboId: defaultCategoryOptionComboId,
                  }
                : undefined,
        [
            dataForm,
            dataValues,
            orgUnit,
            saveDataValue,
            deleteDataValues,
            SourceTypeApplyToAll,
            saveWithTotals,
            initForm,
            orgUnitId,
            period,
            defaultCategoryOptionComboId,
        ]
    );

    return {
        dataFormInfo,
        isLoading,
        loadingCompulsory,
        rules,
        ignoreRules,
        onCloseAlert,
    };
}

export interface DataFormInfo {
    metadata: { dataForm: DataForm };
    data: {
        values: DataValueStore;
        save: (dataValue: DataValue) => Promise<void>;
        delete: (dataValues: DataValue[]) => Promise<void>;
        stApplyToAll: (
            dataValue: DataValueTextMultiple,
            sourceTypeDEs: DataElementRefType[],
            rows: Row[]
        ) => Promise<void>;
        saveWithTotals: (
            dataValue: DataValueNumberSingle,
            columnTotal: DataElement,
            columnDataElements: DataElement[],
            cocId: string
        ) => Promise<void>;
    };
    initForm: () => void;
    categoryOptionComboId: Id;
    orgUnitId: Id;
    orgUnit: OrgUnit;
    period: Period;
}

const commentDialogCss = `
    [aria-describedby="historyDiv"] {
        inset-block-start: 65px !important;
    }
`;

const styles = {
    visible: { opacity: "1" },
    invisible: { opacity: "0" },
};

const CommentDialogStyles: React.FC = () => {
    return <style>{commentDialogCss}</style>;
};

export default React.memo(AutogeneratedForm);
