import React from "react";
import { DataValue } from "../../../domain/common/entities/DataValue";
import { assertUnreachable } from "../../../utils/ts-utils";
import BooleanDropdownWidget from "./widgets/BooleanDropdownWidget";
import NumberWidget from "./widgets/NumberWidget";
import TextWidget from "./widgets/TextWidget";
import SingleSelectWidget from "./widgets/SingleSelectWidget";
import MultipleSelectWidget from "./widgets/MultipleSelectWidget";
import { DataElement } from "../../../domain/common/entities/DataElement";
import { DataFormInfo } from "./AutogeneratedForm";
import SingleSelectRadioWidget from "./widgets/SingleSelectRadioWidget";
import YesNoWidget from "./widgets/YesNoWidget";
import FileWidget from "./widgets/FileWidget";
import DateWidget from "./widgets/DateWidget";
import YearPickerWidget from "./widgets/YearPickerWidget";
import SourceTypeWidget from "./widgets/SourceTypeWidget";
import { Row } from "./GridWithTotalsViewModel";
import PercentageWidget from "./widgets/PercentageWidget";
import { DataForm } from "../../../domain/common/entities/DataForm";
import CheckboxWidget from "./widgets/CheckboxWidget";
import { useUpdatableDataValueWithFeedback } from "./hooks/useUpdatableDataValueWithFeedback";
import { useDataEntryItem } from "./hooks/useDataEntryItem";

export interface DataEntryItemProps {
    dataElement: DataElement;
    dataFormInfo: DataFormInfo;
    period?: string; // Override period in dataFormInfo
    onValueChange: (dataValue: DataValue) => Promise<DataValue>;
    manualyDisabled?: boolean;
    total?: DataElement;
    columnTotal?: DataElement;
    columnDataElements?: DataElement[];
    cocId: string;
    rows?: Row[];
    lockException?: boolean; // If true, the input will be not disabled when the period is not the same as the data form period
}

const DataEntryItem: React.FC<DataEntryItemProps> = props => {
    const { dataElement, dataFormInfo, rows } = props;

    const [dataValue, state, notifyChange] = useUpdatableDataValueWithFeedback(props);
    const { isDataEntryItemVisible, isDataEntryItemDisabled } = useDataEntryItem(props);

    const hasCompulsoryError = dataValue.isRequired ? "required" : state;

    const { type } = dataValue;
    const { options } = dataElement;
    const config = dataFormInfo.metadata.dataForm.options.dataElements[dataElement.id];
    const SingleComponent = config?.widget === "radio" ? SingleSelectRadioWidget : SingleSelectWidget;
    const BooleanComponent = getBooleanComponent(dataFormInfo.metadata.dataForm, dataElement.id);

    if (!isDataEntryItemVisible) return null;

    if (options) {
        switch (type) {
            case "BOOLEAN":
            case "FILE":
            case "PERCENTAGE":
                return <>Not supported</>;
            case "DATE":
                return (
                    <YearPickerWidget
                        dataValue={dataValue}
                        options={options.items}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "MULTI_TEXT":
                return (
                    <MultipleSelectWidget
                        dataValue={dataValue}
                        options={options.items}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "TEXT":
                if (config?.widget === "sourceType" && dataValue.isMultiple) {
                    return (
                        <SourceTypeWidget
                            dataValue={dataValue}
                            dataFormInfo={dataFormInfo}
                            options={options.items}
                            onValueChange={notifyChange}
                            state={hasCompulsoryError}
                            disabled={isDataEntryItemDisabled}
                            sourceTypeDEs={[]}
                            rows={rows}
                        />
                    );
                } else {
                    return dataValue.isMultiple ? (
                        <MultipleSelectWidget
                            dataValue={dataValue}
                            options={options.items}
                            onValueChange={notifyChange}
                            state={hasCompulsoryError}
                            disabled={isDataEntryItemDisabled}
                        />
                    ) : (
                        <SingleComponent
                            dataValue={dataValue}
                            options={options.items}
                            onValueChange={notifyChange}
                            state={hasCompulsoryError}
                            disabled={isDataEntryItemDisabled}
                        />
                    );
                }
            case "NUMBER":
                return dataValue.isMultiple ? (
                    <MultipleSelectWidget
                        dataValue={dataValue}
                        options={options.items}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                ) : (
                    <SingleComponent
                        dataValue={dataValue}
                        options={options.items}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            default:
                assertUnreachable(type);
        }
    } else if (!dataValue.isMultiple) {
        switch (type) {
            case "BOOLEAN":
                return (
                    <BooleanComponent
                        dataValue={dataValue}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "NUMBER":
                return (
                    <NumberWidget
                        dataValue={dataValue}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "PERCENTAGE":
                return (
                    <PercentageWidget
                        dataValue={dataValue}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "TEXT":
                return (
                    <TextWidget
                        dataValue={dataValue}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "FILE":
                return (
                    <FileWidget
                        dataValue={dataValue}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "DATE":
                return (
                    <DateWidget
                        dataValue={dataValue}
                        onValueChange={notifyChange}
                        state={hasCompulsoryError}
                        disabled={isDataEntryItemDisabled}
                    />
                );
            case "MULTI_TEXT":
                return null;

            default:
                return assertUnreachable(type);
        }
    } else {
        return <p>Data element not supported: {JSON.stringify(dataValue?.dataElement)}</p>;
    }
};

export default React.memo(DataEntryItem);

function getBooleanComponent(dataForm: DataForm, dataElementId: string) {
    const config = dataForm.options.dataElements[dataElementId];
    switch (config?.widget) {
        case "dropdown":
            return BooleanDropdownWidget;
        case "checkbox":
            return CheckboxWidget;
        default:
            return YesNoWidget;
    }
}
