import { makeStyles } from "@material-ui/core";
import React from "react";
import { Section } from "../../../domain/common/entities/DataForm";
import { DataFormInfo } from "./AutogeneratedForm";
import { DataElementItem } from "./DataElementItem";
import { Html } from "./Html";
import { Id } from "../../../domain/common/entities/Base";
import { useSectionVisibility } from "./hooks/useSectionVisibility";
import { getTabIndices } from "./SectionsTabs";
import { Maybe } from "../../../utils/ts-utils";
import { useSectionRuleActions } from "./hooks/useSectionRuleActions";

export interface DataTableProps {
    section: DataTableSectionObj;
    dataFormInfo: DataFormInfo;
    children: React.ReactNode;
    sectionStyles?: Section["styles"];
}

export type DataTableSectionObj = {
    id: Id;
    name: string;
    showIndex?: Section["showIndex"];
    tabs?: Section["tabs"];
    titleVariant?: Section["titleVariant"];
    texts: Section["texts"];
    toggle: Section["toggle"];
    toggleMultiple: Section["toggleMultiple"];
    hidden: boolean;
};

const DataTableSection: React.FC<DataTableProps> = React.memo(props => {
    const { section, children, dataFormInfo, sectionStyles } = props;
    const classes = useStyles();
    const { name: sectionName, toggle } = section;
    const sectionLabel = getIndexedLabel(section, dataFormInfo, sectionName, undefined);
    const { messages: sectionMessages } = useSectionRuleActions({ sectionId: section.id, dataFormInfo });
    const {
        isVisible: isSectionVisible,
        isOpen: isSectionOpen,
        isDisabled: isSectionDisabled,
    } = useSectionVisibility(section, dataFormInfo);

    const titleStyle = section.titleVariant ? `${classes.title} ${classes[section.titleVariant]}` : classes.title;

    if (!isSectionVisible) return null;

    return (
        <>
            {sectionMessages.map(sectionMessage => (
                <div key={sectionMessage} className={`${classes.sectionMessage} section-message`}>
                    <Html content={sectionMessage} />
                </div>
            ))}
            <div className={classes.wrapper}>
                <div style={{ backgroundColor: sectionStyles?.title.backgroundColor }}>
                    <h3
                        style={{ color: sectionStyles?.title.color, fontSize: sectionStyles?.title.fontSize }}
                        className={titleStyle}
                    >
                        {sectionLabel}
                    </h3>
                </div>

                <Html backgroundColor={sectionStyles?.title.backgroundColor} content={section.texts.header} />

                {toggle.type === "dataElement" && (
                    <div className={classes.toggleWrapper}>
                        <div className={classes.toggleTitle}>{toggle.dataElement.name}</div>
                        <DataElementItem dataElement={toggle.dataElement} dataFormInfo={dataFormInfo} />
                    </div>
                )}

                {(isSectionOpen || isSectionDisabled) && (
                    <>
                        {children}
                        <Html content={section.texts.footer} />
                    </>
                )}
            </div>
        </>
    );
});

const useStyles = makeStyles({
    wrapper: { margin: 10, border: "1px solid black" },
    toggleWrapper: { margin: 10 },
    toggleTitle: { marginBlockEnd: 10 },
    title: { textAlign: "center", margin: 0, padding: "1em" },
    subtitle: { textAlign: "center", marginBlockEnd: 10 },
    h1: {
        fontSize: "6rem !important",
        margin: "18px !important",
    },
    h2: {
        fontSize: "3.75rem !important",
        margin: "18px !important",
    },
    h3: {
        fontSize: "3rem !important",
        margin: "18px !important",
    },
    h4: {
        fontSize: "2.125rem !important",
        margin: "18px !important",
    },
    h5: {
        fontSize: "1.5rem !important",
        margin: "18px !important",
    },
    h6: {
        fontSize: "1.25rem !important",
        margin: "18px !important",
    },
    sectionMessage: {
        margin: 10,
        padding: "1em",
        backgroundColor: "#FFF3CD",
        border: "1px solid #FFEEBA",
        color: "rgb(50, 38, 1)",
    },
});

export function getIndexedLabel(
    section: { tabs?: { active: boolean; order?: string }; showIndex?: boolean },
    dataFormInfo: DataFormInfo,
    name: string,
    dataElementIndex: Maybe<number>
): string {
    if (!section.showIndex) {
        return name;
    }

    const allSections = dataFormInfo.metadata.dataForm.sections;
    const [adjustedPrimaryIdx, adjustedSecondaryIdx] = allSections
        ? getTabIndices(section.tabs?.order, allSections, section.showIndex ?? false)
        : [-1, -1];

    if (adjustedPrimaryIdx !== -1) {
        return `${adjustedPrimaryIdx + 1}.${adjustedSecondaryIdx + 1}${
            dataElementIndex ? `.${dataElementIndex}` : ""
        } - ${name}`;
    }

    return name;
}

export default React.memo(DataTableSection);
