import React from "react";
import { SectionSimple } from "../../../domain/common/entities/DataForm";
import { DataFormInfo } from "./AutogeneratedForm";
import { makeStyles } from "@material-ui/core";
import DataTableSection from "./DataTableSection";
import {
    DataTable,
    DataTableRow,
    TableBody,
    TableHead,
    // @ts-ignore
} from "@dhis2/ui";
import { DataElementItem } from "./DataElementItem";
import { CustomDataTableCell, CustomDataTableColumnHeader } from "./datatables/CustomDataTables";
import { DisaggregatedCOCsGridViewModel } from "./DisaggregatedCOCsGridViewModel";

type DisaggregatedCOCsGridProps = {
    dataFormInfo: DataFormInfo;
    section: SectionSimple;
};

const DisaggregatedCOCsGrid: React.FC<DisaggregatedCOCsGridProps> = props => {
    const { dataFormInfo, section } = props;
    const classes = useStyles();
    const grid = React.useMemo(
        () => DisaggregatedCOCsGridViewModel.get(section, dataFormInfo),
        [section, dataFormInfo]
    );

    const colSpan = (index: number) => {
        return index === 0 ? grid.columns.length + 1 : grid.columns.length;
    };

    return (
        <DataTableSection section={grid} dataFormInfo={dataFormInfo} sectionStyles={props.section.styles}>
            <DataTable className={classes.table} layout="fixed" width="initial">
                <TableHead>
                    <DataTableRow>
                        {section.dataElements.map((dataElement, index) => (
                            <CustomDataTableColumnHeader
                                backgroundColor={props.section.styles.columns.backgroundColor}
                                key={`column-${dataElement.id}`}
                                colSpan={colSpan(index)}
                            >
                                <span className={classes.header}>{dataElement.name}</span>
                            </CustomDataTableColumnHeader>
                        ))}
                    </DataTableRow>
                    <DataTableRow>
                        <CustomDataTableColumnHeader
                            backgroundColor={props.section.styles.columns.backgroundColor}
                            width="400px"
                            colSpan="1"
                        ></CustomDataTableColumnHeader>
                        {grid.columns.map(column => (
                            <CustomDataTableColumnHeader
                                backgroundColor={props.section.styles.columns.backgroundColor}
                                key={column.name}
                            >
                                <div className={classes.header}>
                                    <span>{column.name}</span>
                                    <span
                                        className={classes.description}
                                        dangerouslySetInnerHTML={{ __html: column.description || "" }}
                                    ></span>
                                </div>
                            </CustomDataTableColumnHeader>
                        ))}
                    </DataTableRow>
                </TableHead>

                <TableBody>
                    {grid.rows.map(row => (
                        <DataTableRow key={row.name}>
                            <CustomDataTableCell backgroundColor={props.section.styles.rows.backgroundColor}>
                                <span>{row.name}</span>
                            </CustomDataTableCell>

                            {row.items.map(({ columnName, dataElement }) =>
                                dataElement ? (
                                    <CustomDataTableCell
                                        backgroundColor={props.section.styles.rows.backgroundColor}
                                        key={`${dataElement.id}-${dataElement.cocId}`}
                                    >
                                        <DataElementItem
                                            dataElement={dataElement}
                                            dataFormInfo={dataFormInfo}
                                            noComment={dataElement.disabledComments}
                                        />
                                    </CustomDataTableCell>
                                ) : (
                                    <CustomDataTableCell
                                        key={columnName}
                                        backgroundColor={props.section.styles.rows.backgroundColor}
                                    />
                                )
                            )}
                        </DataTableRow>
                    ))}
                </TableBody>
            </DataTable>
        </DataTableSection>
    );
};

const useStyles = makeStyles({
    header: {
        fontSize: "1.2em",
        fontWeight: "bold",
        flexDirection: "column",
        textAlign: "center",
        display: "flex",
        padding: "4px",
    },
    description: { fontWeight: "normal", fontSize: "0.8em" },
    table: { borderWidth: "3px !important", minWidth: "100%" },
    rowTitle: { fontSize: "1.2em", fontWeight: "bold" },
});

export default React.memo(DisaggregatedCOCsGrid);
