import _ from "lodash";
import { SectionDisaggregatedCocs } from "../../../domain/common/entities/DataForm";
import { DataFormInfo } from "./AutogeneratedForm";
import { CategoryOptionCombo, DataElement } from "../../../domain/common/entities/DataElement";
import { Indicator } from "../../../domain/common/entities/Indicator";
import { getDescription } from "../../../utils/viewTypes";
import { Maybe } from "../../../utils/ts-utils";
import { getDataElementLabel } from "./GridFormViewModel";
import { calculateFormula } from "./datatables/InputFormula";
import { isToggleMultipleDeDisabled } from "../../../domain/common/entities/ToggleMultiple";

export class DisaggregatedCOCsGridViewModel {
    static get(section: SectionDisaggregatedCocs, dataFormInfo: DataFormInfo): Grid {
        const columns = DisaggregatedCOCsGridViewModel.getGridColumns(section, dataFormInfo);
        const rows = DisaggregatedCOCsGridViewModel.getGridRows(section, columns, dataFormInfo);

        const summary = DisaggregatedCOCsGridViewModel.getSummary(section, dataFormInfo, columns, rows);

        return {
            id: section.id,
            indicators: section.indicators,
            name: section.name,
            columns: columns,
            rows: rows,
            showIndex: section.showIndex,
            tabs: section.tabs,
            toggle: section.toggle,
            toggleMultiple: section.toggleMultiple,
            texts: section.texts,
            summary: section.totals ? summary : [],
            hidden: section.hidden || false,
        };
    }

    private static getGridColumns(section: SectionDisaggregatedCocs, dataFormInfo: DataFormInfo): Column[] {
        const columns = section.dataElements.map(dataElement => {
            const columnItems = _(dataElement.categoryOptionCombos)
                .map((coc): ColumnItem => {
                    const categoryOption = getCocOption(coc);
                    const columnCode = `${dataElement.code}${COLUMNS_CONFIG_SEPARATOR}${categoryOption.code}`;
                    const overrideName = section.columnsConfig?.[columnCode]?.columnName;
                    const columnName = overrideName ?? categoryOption.formName;

                    const columnItem: ColumnItem = {
                        name: overrideName ? columnName : _(columnName).capitalize(),
                        code: columnCode,
                        description: getDescription(section.columnsDescriptions, dataFormInfo, categoryOption.formName),
                        isVisible: true,
                        sortOrder: categoryOption.sortOrder,
                    };

                    if (!section.columnsConfig) return columnItem;

                    return this.isColumnItemVisible({ section, column: columnItem, dataFormInfo });
                })
                .filter(column => column.isVisible)
                .uniqBy(column => column.name)
                .value();

            return {
                columnItems: sortItems(columnItems),
                dataElement: {
                    ...dataElement,
                    name: getDataElementLabel(section, dataFormInfo, dataElement, dataElement.name),
                },
            };
        });

        return columns;
    }

    private static getGridRows(
        section: SectionDisaggregatedCocs,
        columns: Column[],
        dataFormInfo: DataFormInfo
    ): Row[] {
        const rows = _(section.dataElements)
            .flatMap(dataElement => dataElement.categoryOptionCombos)
            .groupBy(coc => getRowCategoryOptionCodeFromCoc(coc))
            .map((_group, rowCatOptionCode) => {
                if (!rowCatOptionCode) {
                    console.warn("Skipping row with empty row name");
                    return undefined;
                }

                const rowConfig = section.rowsConfig?.[rowCatOptionCode];
                if (rowConfig?.hide) return undefined;

                const items = section.dataElements
                    .filter(dataElement =>
                        dataElement.categoryOptionCombos.some(
                            coc => getRowCategoryOptionCodeFromCoc(coc) === rowCatOptionCode
                        )
                    )
                    .map(dataElement => {
                        const rowItems = _(dataElement.categoryOptionCombos)
                            .filter(item => getRowCategoryOptionCodeFromCoc(item) === rowCatOptionCode)
                            .map(coc => {
                                const cocOption = getCocOption(coc);
                                const cocColumnCode = `${dataElement.code}${COLUMNS_CONFIG_SEPARATOR}${cocOption.code}`;
                                const columnName =
                                    columns
                                        .find(column => column.dataElement.id === dataElement.id)
                                        ?.columnItems.find(columnItem => columnItem.code === cocColumnCode)?.name || "";

                                if (!columnName) return undefined;

                                const orgUnitCode = dataFormInfo.orgUnit.code;
                                return {
                                    ...dataElement,
                                    cocId: coc.id,
                                    categoryOptionCombos: [coc],
                                    categoryCombos: {
                                        ...dataElement.categoryCombos,
                                        categoryOptionCombos: [{ ...coc, formName: coc.formName }],
                                    },
                                    columnName: columnName,
                                    disabled: isToggleMultipleDeDisabled(section, dataElement, orgUnitCode),
                                };
                            })
                            .compact()
                            .value();

                        const disaggregatedDataElement = {
                            ...dataElement,
                            categoryCombos: {
                                ...dataElement.categoryCombos,
                                categoryOptionCombos: dataElement.categoryCombos.categoryOptionCombos.filter(
                                    coc => getRowCategoryOptionCodeFromCoc(coc) === rowCatOptionCode
                                ),
                            },
                            categoryOptionCombos: dataElement.categoryOptionCombos.filter(
                                coc => getRowCategoryOptionCodeFromCoc(coc) === rowCatOptionCode
                            ),
                        };

                        return {
                            dataElement: disaggregatedDataElement,
                            cocIdsToSum: rowItems.map(ri => ri.cocId),
                            rowItems: rowItems,
                        };
                    });

                const catOptionFormName = getCocFormNameFromCombos(
                    items.flatMap(i => i.dataElement.categoryOptionCombos),
                    rowCatOptionCode
                );
                return {
                    name: rowConfig?.rowName ?? _(catOptionFormName.name).capitalize(),
                    sortOrder: catOptionFormName.sortOrder,
                    items: items,
                };
            })
            .compact()
            .value();

        return sortItems(rows);
    }

    private static getSummary(
        section: SectionDisaggregatedCocs,
        dataFormInfo: DataFormInfo,
        columns: Column[],
        rows: Row[]
    ): Summary[] {
        const allDataElements = dataFormInfo.metadata.dataForm.dataElements;

        const summary = _(section.totals)
            .map((sectionTotal, key) => {
                const selectedDataElements = allDataElements.filter(dataElement =>
                    sectionTotal.dataElementsCodes.includes(dataElement.code)
                );

                const cells = selectedDataElements.map(dataElement => {
                    const columnDE = columns.find(column => column.dataElement.id === dataElement.id);
                    const columnItems = columnDE ? columnDE.columnItems : [];
                    const allRowsInDe = rows.flatMap(row =>
                        row.items.filter(item => item.dataElement.id === dataElement.id)
                    );
                    const allowedCocIds = allRowsInDe.flatMap(item => item.cocIdsToSum);

                    return {
                        ...dataElement,
                        columnItems: columnItems,
                        cocIdsToSum: allowedCocIds,
                    };
                });

                return {
                    cellName: key,
                    cells: cells,
                };
            })
            .value();

        return summary;
    }

    private static isColumnItemVisible(options: {
        section: SectionDisaggregatedCocs;
        column: ColumnItem;
        dataFormInfo: DataFormInfo;
    }): ColumnItem {
        const { section, column, dataFormInfo } = options;

        const config = section.columnsConfig ? section.columnsConfig[column.code] : undefined;
        if (!config || !config.rules?.visible) return { ...column, isVisible: true };

        const dataElementCodes = _(config.rules?.visible?.dataElements)
            .map(dataElement => dataElement.code)
            .compact()
            .value();

        const value = calculateFormula({
            dataElementCodes: dataElementCodes,
            dataFormInfo,
            formula: config.rules?.visible?.formula.value ?? "",
            period: dataFormInfo.period,
        });

        return { ...column, isVisible: value === config.rules?.visible?.formula.condition };
    }
}

export type Grid = {
    id: string;
    name: string;
    columns: Column[];
    rows: Row[];
    showIndex: SectionDisaggregatedCocs["showIndex"];
    tabs: SectionDisaggregatedCocs["tabs"];
    toggle: SectionDisaggregatedCocs["toggle"];
    toggleMultiple: SectionDisaggregatedCocs["toggleMultiple"];
    texts: SectionDisaggregatedCocs["texts"];
    summary: Summary[];
    indicators: Indicator[];
    hidden: boolean;
};

export type ColumnItem = {
    name: string;
    description?: string;
    isVisible: boolean;
    code: string;
    sortOrder: number;
};

type Column = {
    dataElement: DataElement;
    columnItems: ColumnItem[];
};

type Row = {
    name: string;
    sortOrder: number;
    items: { cocIdsToSum: string[]; dataElement: DataElement; rowItems: Array<DataElement & { columnName: string }> }[];
};

type Summary = {
    cellName: string;
    cells: Array<DataElement & { columnItems: ColumnItem[]; cocIdsToSum: string[] }>;
};

const separator = ", ";

// Sort columns/rows by the DHIS2 metadata sortOrder of the underlying category
// option. This is independent of the (translated) display label, so column
// order is stable across languages. Items missing a sortOrder fall to the end.
const sortItems = <T extends { sortOrder: number }>(items: T[]): T[] => {
    return _.sortBy(items, item => item.sortOrder);
};

function getRowCategoryOptionCodeFromCoc(categoryOptionCombo: CategoryOptionCombo): Maybe<string> {
    return categoryOptionCombo.name.split(separator)[1];
}

function getCocFormNameFromCombos(
    categoryOptionCombos: CategoryOptionCombo[],
    optionCode: string
): { name: string; sortOrder: number } {
    const coc = categoryOptionCombos.find(coc => getRowCategoryOptionCodeFromCoc(coc) === optionCode);
    if (!coc) return { name: optionCode, sortOrder: Number.POSITIVE_INFINITY };
    const matchedOption = coc.categoryOptions.find(co => optionCode.includes(co.name));
    return {
        name: matchedOption?.displayFormName || optionCode,
        sortOrder: matchedOption?.sortOrder ?? Number.POSITIVE_INFINITY,
    };
}

function getCocOption(
    categoryOptionCombo: CategoryOptionCombo
): { code: string; name: string; formName: string; sortOrder: number } {
    const cocName = categoryOptionCombo.name.split(separator)[0];
    const cocFormName = categoryOptionCombo.categoryOptions.find(co => cocName?.includes(co.name));

    if (!cocFormName) {
        return { code: "", name: "", formName: "", sortOrder: Number.POSITIVE_INFINITY };
    }

    return {
        code: cocFormName.code,
        name: cocFormName.name,
        formName: cocFormName.displayFormName,
        sortOrder: cocFormName.sortOrder,
    };
}

const COLUMNS_CONFIG_SEPARATOR = "||";
