import React from "react";
import { SectionSimple } from "../../../domain/common/entities/DataForm";
import { DataFormInfo } from "./AutogeneratedForm";
import { makeStyles } from "@material-ui/core";
import DataTableSection from "./DataTableSection";
import {
    DataTable,
    DataTableRow,
    TableBody,
    TableHead,
    // @ts-ignore
} from "@dhis2/ui";
import { DataElementItem } from "./DataElementItem";
import { CustomDataTableCell, CustomDataTableColumnHeader } from "./datatables/CustomDataTables";
import { DisaggregatedCOCsGridViewModel } from "./DisaggregatedCOCsGridViewModel";
import { DataTableCellRowTotal } from "./datatables/DataTableCellRowTotal";
import { Html } from "./Html";

type DisaggregatedCOCsGridProps = {
    dataFormInfo: DataFormInfo;
    section: SectionSimple;
};

/*
    This view type converts data forms with disaggregated data elements into a grid format with one category represented in the columns and the other in the rows.
    An example using the section ITNs:

    Data element                                        Categories                                      Category option combos
    ITNs - By age group and gender                      Age group => [0-12, 12-18, 18-24, 25-49, 50+]   "0-12, Male", "0-12, Female", "12-18, Male", "12-18, Female", "18-24, Male", "18-24, Female", "25-49, Male", "25-49, Female", "50+, Male", "50+, Female"
                                                        Gender => [Male, Female]
    ITNs - By age group and gender (Policy Extra)       Age group => [0-12, 12-18, 18-24, 25-49, 50+]   "0-12, Male", "0-12, Female", "12-18, Male", "12-18, Female", "18-24, Male", "18-24, Female", "25-49, Male", "25-49, Female", "50+, Male", "50+, Female"
                                                        Gender => [Male, Female]

    The grouping is done by separating the category option combination names with a (", ").
    This will create this table:

            |   ITNs - By age group and gender                        |  ITNs - By age group and gender (Policy Extra)                         
    ---------------------------------------------------------------------------------------------------------------------------
            |   0-12    |   12-18   |   18-24   |   25-49   |   50+   |   0-12   |   12-18   |   18-24   |   25-49   |   50+   |  
    ---------------------------------------------------------------------------------------------------------------------------|    
    Female  |           |           |           |           |         |          |           |           |           |         |
    Male    |           |           |           |           |         |          |           |           |           |         |
*/

const DisaggregatedCOCsGrid: React.FC<DisaggregatedCOCsGridProps> = props => {
    const { dataFormInfo, section } = props;
    const classes = useStyles();
    const grid = React.useMemo(
        () => DisaggregatedCOCsGridViewModel.get(section, dataFormInfo),
        [section, dataFormInfo]
    );

    const showRowTotals = props.section.showRowTotals;
    const colSpan = (index?: number) => {
        return index === 0 ? grid.columns.length + 2 : grid.columns.length + 1;
    };

    return (
        <DataTableSection section={grid} dataFormInfo={dataFormInfo} sectionStyles={props.section.styles}>
            <DataTable className={classes.table} layout="fixed" width="initial">
                <TableHead>
                    <DataTableRow>
                        {section.dataElements.map((dataElement, index) => (
                            <CustomDataTableColumnHeader
                                backgroundColor={props.section.styles.columns.backgroundColor}
                                key={`column-${dataElement.id}`}
                                colSpan={colSpan(index)}
                            >
                                <span className={classes.header}>{dataElement.name}</span>
                            </CustomDataTableColumnHeader>
                        ))}
                    </DataTableRow>
                    <DataTableRow>
                        <CustomDataTableColumnHeader
                            backgroundColor={props.section.styles.columns.backgroundColor}
                            width="250px"
                            colSpan="1"
                        ></CustomDataTableColumnHeader>
                        {grid.columns.map(column => (
                            <CustomDataTableColumnHeader
                                backgroundColor={props.section.styles.columns.backgroundColor}
                                key={column.name}
                            >
                                <div className={classes.header}>
                                    <span>{column.name}</span>
                                    <span
                                        className={classes.description}
                                        dangerouslySetInnerHTML={{ __html: column.description || "" }}
                                    ></span>
                                </div>
                            </CustomDataTableColumnHeader>
                        ))}
                        {showRowTotals && (
                            <CustomDataTableColumnHeader
                                backgroundColor={props.section.styles.columns.backgroundColor}
                                key="column-row-totals"
                            >
                                <div className={classes.header}>
                                    <div dangerouslySetInnerHTML={{ __html: grid.texts.rowTotals || "" }}></div>
                                </div>
                            </CustomDataTableColumnHeader>
                        )}
                    </DataTableRow>
                </TableHead>

                <TableBody>
                    {grid.rows.map(row => (
                        <DataTableRow key={row.name}>
                            <CustomDataTableCell backgroundColor={props.section.styles.rows.backgroundColor}>
                                <span>{row.name}</span>
                            </CustomDataTableCell>

                            {row.items.map(({ dataElement, rowItems }) => {
                                return (
                                    <>
                                        {rowItems.map(rowItem => {
                                            return (
                                                <CustomDataTableCell
                                                    backgroundColor={props.section.styles.rows.backgroundColor}
                                                    key={`${rowItem.id}-${rowItem.cocId}`}
                                                >
                                                    <DataElementItem
                                                        dataElement={rowItem}
                                                        dataFormInfo={dataFormInfo}
                                                        noComment={rowItem.disabledComments}
                                                    />
                                                </CustomDataTableCell>
                                            );
                                        })}

                                        {showRowTotals && (
                                            <DataTableCellRowTotal
                                                dataFormInfo={dataFormInfo}
                                                styles={props.section.styles}
                                                dataElement={dataElement}
                                            />
                                        )}
                                    </>
                                );
                            })}
                        </DataTableRow>
                    ))}

                    {grid.summary.map(summary => (
                        <DataTableRow key={`${summary.cellName}-totals`}>
                            <CustomDataTableCell
                                backgroundColor={props.section.styles.totals.backgroundColor}
                                key="total-column-name"
                            >
                                <Html content={summary.cellName} />
                            </CustomDataTableCell>
                            {summary.cells.map(cell => {
                                return (
                                    <DataTableCellRowTotal
                                        key={cell.id}
                                        colSpan={colSpan()}
                                        dataFormInfo={dataFormInfo}
                                        styles={props.section.styles}
                                        dataElement={cell}
                                    />
                                );
                            })}
                        </DataTableRow>
                    ))}
                </TableBody>
            </DataTable>
        </DataTableSection>
    );
};

const useStyles = makeStyles({
    header: {
        fontSize: "1.2em",
        fontWeight: "bold",
        flexDirection: "column",
        textAlign: "center",
        display: "flex",
        padding: "4px",
    },
    description: { fontWeight: "normal", fontSize: "0.8em" },
    table: { borderWidth: "3px !important", minWidth: "100%" },
    rowTitle: { fontSize: "1.2em", fontWeight: "bold" },
});

export default React.memo(DisaggregatedCOCsGrid);
