import _ from "lodash";
import { SectionDisaggregatedCocs } from "../../../domain/common/entities/DataForm";
import { DataFormInfo } from "./AutogeneratedForm";
import { CategoryOptionCombo, DataElement } from "../../../domain/common/entities/DataElement";
import { Indicator } from "../../../domain/common/entities/Indicator";
import { getDescription } from "../../../utils/viewTypes";
import { Maybe } from "../../../utils/ts-utils";
import { getDataElementLabel } from "./GridFormViewModel";
import { calculateFormula } from "./datatables/InputFormula";
import { isToggleMultipleDeDisabled } from "../../../domain/common/entities/ToggleMultiple";

export class DisaggregatedCOCsGridViewModel {
    static get(section: SectionDisaggregatedCocs, dataFormInfo: DataFormInfo): Grid {
        const columns = DisaggregatedCOCsGridViewModel.getGridColumns(section, dataFormInfo);
        const rows = DisaggregatedCOCsGridViewModel.getGridRows(section, columns, dataFormInfo);

        const summary = DisaggregatedCOCsGridViewModel.getSummary(section, dataFormInfo, columns, rows);

        return {
            id: section.id,
            indicators: section.indicators,
            name: section.name,
            columns: columns,
            rows: rows,
            showIndex: section.showIndex,
            tabs: section.tabs,
            toggle: section.toggle,
            toggleMultiple: section.toggleMultiple,
            texts: section.texts,
            summary: section.totals ? summary : [],
            hidden: section.hidden || false,
        };
    }

    private static getGridColumns(section: SectionDisaggregatedCocs, dataFormInfo: DataFormInfo): Column[] {
        const columns = section.dataElements.map(dataElement => {
            const columnItems = _(dataElement.categoryOptionCombos)
                .map((coc): ColumnItem => {
                    const categoryOption = getCocOption(coc);
                    const columnName = categoryOption.formName;

                    const columnItem: ColumnItem = {
                        name: _(columnName).capitalize(),
                        code: `${dataElement.code}${COLUMNS_CONFIG_SEPARATOR}${categoryOption.code}`,
                        description: getDescription(section.columnsDescriptions, dataFormInfo, columnName),
                        isVisible: true,
                    };

                    if (!section.columnsConfig) return columnItem;

                    return this.isColumnItemVisible({ section, column: columnItem, dataFormInfo });
                })
                .filter(column => column.isVisible)
                .uniqBy(column => column.name)
                .value();

            return {
                columnItems: sortItems(columnItems),
                dataElement: {
                    ...dataElement,
                    name: getDataElementLabel(section, dataFormInfo, dataElement, dataElement.name),
                },
            };
        });

        return columns;
    }

    private static getGridRows(
        section: SectionDisaggregatedCocs,
        columns: Column[],
        dataFormInfo: DataFormInfo
    ): Row[] {
        const rows = _(section.dataElements)
            .flatMap(dataElement => dataElement.categoryOptionCombos)
            .groupBy(coc => getRowCategoryOptionCodeFromCoc(coc))
            .map((_group, rowCatOptionCode) => {
                if (!rowCatOptionCode) {
                    console.warn("Skipping row with empty row name");
                    return undefined;
                }

                const rowConfig = section.rowsConfig?.[rowCatOptionCode];
                if (rowConfig?.hide) return undefined;

                const items = section.dataElements
                    .filter(dataElement =>
                        dataElement.categoryOptionCombos.some(
                            coc => getRowCategoryOptionCodeFromCoc(coc) === rowCatOptionCode
                        )
                    )
                    .map(dataElement => {
                        const rowItems = _(dataElement.categoryOptionCombos)
                            .filter(item => getRowCategoryOptionCodeFromCoc(item) === rowCatOptionCode)
                            .map(coc => {
                                const columnName =
                                    columns
                                        .find(column => column.dataElement.id === dataElement.id)
                                        ?.columnItems.find(columnItem => columnItem.name === getColumnNameFromCoc(coc))
                                        ?.name || "";

                                if (!columnName) return undefined;

                                const orgUnitCode = dataFormInfo.orgUnit.code;
                                return {
                                    ...dataElement,
                                    cocId: coc.id,
                                    categoryOptionCombos: [coc],
                                    categoryCombos: {
                                        ...dataElement.categoryCombos,
                                        categoryOptionCombos: [{ ...coc, formName: coc.formName }],
                                    },
                                    columnName: columnName,
                                    disabled: isToggleMultipleDeDisabled(section, dataElement, orgUnitCode),
                                };
                            })
                            .compact()
                            .value();

                        const disaggregatedDataElement = {
                            ...dataElement,
                            categoryCombos: {
                                ...dataElement.categoryCombos,
                                categoryOptionCombos: dataElement.categoryCombos.categoryOptionCombos.filter(
                                    coc => getRowCategoryOptionCodeFromCoc(coc) === rowCatOptionCode
                                ),
                            },
                            categoryOptionCombos: dataElement.categoryOptionCombos.filter(
                                coc => getRowCategoryOptionCodeFromCoc(coc) === rowCatOptionCode
                            ),
                        };

                        return {
                            dataElement: disaggregatedDataElement,
                            cocIdsToSum: rowItems.map(ri => ri.cocId),
                            rowItems: rowItems,
                        };
                    });

                const catOptionFormName = getCocFormNameFromCombos(
                    items.flatMap(i => i.dataElement.categoryOptionCombos),
                    rowCatOptionCode
                );
                return {
                    name: rowConfig?.rowName ?? _(catOptionFormName).capitalize(),
                    items: items,
                };
            })
            .compact()
            .value();

        return sortItems(rows);
    }

    private static getSummary(
        section: SectionDisaggregatedCocs,
        dataFormInfo: DataFormInfo,
        columns: Column[],
        rows: Row[]
    ): Summary[] {
        const allDataElements = dataFormInfo.metadata.dataForm.dataElements;

        const summary = _(section.totals)
            .map((sectionTotal, key) => {
                const selectedDataElements = allDataElements.filter(dataElement =>
                    sectionTotal.dataElementsCodes.includes(dataElement.code)
                );

                const cells = selectedDataElements.map(dataElement => {
                    const columnDE = columns.find(column => column.dataElement.id === dataElement.id);
                    const columnItems = columnDE ? columnDE.columnItems : [];
                    const allRowsInDe = rows.flatMap(row =>
                        row.items.filter(item => item.dataElement.id === dataElement.id)
                    );
                    const allowedCocIds = allRowsInDe.flatMap(item => item.cocIdsToSum);

                    return {
                        ...dataElement,
                        columnItems: columnItems,
                        cocIdsToSum: allowedCocIds,
                    };
                });

                return {
                    cellName: key,
                    cells: cells,
                };
            })
            .value();

        return summary;
    }

    private static isColumnItemVisible(options: {
        section: SectionDisaggregatedCocs;
        column: ColumnItem;
        dataFormInfo: DataFormInfo;
    }): ColumnItem {
        const { section, column, dataFormInfo } = options;

        const config = section.columnsConfig ? section.columnsConfig[column.code] : undefined;
        if (!config) return { ...column, isVisible: true };

        const dataElementCodes = _(config.rules?.visible?.dataElements)
            .map(dataElement => dataElement.code)
            .compact()
            .value();

        const value = calculateFormula({
            dataElementCodes: dataElementCodes,
            dataFormInfo,
            formula: config.rules?.visible?.formula.value ?? "",
            period: dataFormInfo.period,
        });

        return { ...column, isVisible: value === config.rules?.visible?.formula.condition };
    }
}

export type Grid = {
    id: string;
    name: string;
    columns: Column[];
    rows: Row[];
    showIndex: SectionDisaggregatedCocs["showIndex"];
    tabs: SectionDisaggregatedCocs["tabs"];
    toggle: SectionDisaggregatedCocs["toggle"];
    toggleMultiple: SectionDisaggregatedCocs["toggleMultiple"];
    texts: SectionDisaggregatedCocs["texts"];
    summary: Summary[];
    indicators: Indicator[];
    hidden: boolean;
};

export type ColumnItem = {
    name: string;
    description?: string;
    isVisible: boolean;
    code: string;
};

type Column = {
    dataElement: DataElement;
    columnItems: ColumnItem[];
};

type Row = {
    name: string;
    items: { cocIdsToSum: string[]; dataElement: DataElement; rowItems: Array<DataElement & { columnName: string }> }[];
};

type Summary = {
    cellName: string;
    cells: Array<DataElement & { columnItems: ColumnItem[]; cocIdsToSum: string[] }>;
};

const separator = ", ";

// Unknown patterns: "Other/unknown" will always be at the end. This logic is specific for TUB_ANNUAL_DATA dataSet
// TO-DO: Move patterns into datastore config when rules vary per dataset.
const sortItems = <T extends { name: string }>(items: T[], unknownPatterns: string[] = ["unknown", "other"]): T[] => {
    const itemsWithSortKeys = items.map(item => {
        const raw = item.name;
        const lower = raw.toLowerCase();
        const isUnknown = _.some(unknownPatterns, p => lower.includes(p.toLowerCase()));

        const matches = raw.match(/\d+/g) ?? [];
        const hasNumber = matches.length > 0 && !isUnknown;

        const start = hasNumber && matches[0] ? parseInt(matches[0], 10) : Number.POSITIVE_INFINITY;

        const end =
            hasNumber && matches[1]
                ? parseInt(matches[1], 10)
                : hasNumber && raw.includes("+")
                ? Number.POSITIVE_INFINITY
                : start;

        return {
            item,
            sortKey: {
                isUnknown,
                hasNumber,
                start,
                end,
                alpha: lower,
            },
        };
    });

    const sortedItems = _.sortBy(itemsWithSortKeys, [
        x => (x.sortKey.isUnknown ? 1 : 0),
        x => (x.sortKey.hasNumber ? 0 : 1),

        x => x.sortKey.start,
        x => x.sortKey.end,

        x => x.sortKey.alpha,
    ]);

    return sortedItems.map(x => x.item);
};

function getColumnNameFromCoc(categoryOptionCombo: CategoryOptionCombo): Maybe<string> {
    const cocName = categoryOptionCombo.name.split(separator)[0];
    return getCocFormName(categoryOptionCombo, cocName);
}

function getRowCategoryOptionCodeFromCoc(categoryOptionCombo: CategoryOptionCombo): Maybe<string> {
    return categoryOptionCombo.name.split(separator)[1];
}

function getCocFormNameFromCombos(categoryOptionCombos: CategoryOptionCombo[], optionCode: string): string {
    const coc = categoryOptionCombos.find(coc => getRowCategoryOptionCodeFromCoc(coc) === optionCode);
    if (!coc) return optionCode;
    return getCocFormName(coc, optionCode) || optionCode;
}

function getCocFormName(categoryOptionCombo: CategoryOptionCombo, cocName: Maybe<string>): Maybe<string> {
    const cocFormName = categoryOptionCombo.categoryOptions.find(co => cocName?.includes(co.name))?.displayFormName;
    return cocFormName || cocName;
}

function getCocOption(categoryOptionCombo: CategoryOptionCombo): { code: string; name: string; formName: string } {
    const cocName = categoryOptionCombo.name.split(separator)[0];
    const cocFormName = categoryOptionCombo.categoryOptions.find(co => cocName?.includes(co.name));

    if (!cocFormName) {
        return { code: "", name: "", formName: "" };
    }

    return { code: cocFormName.code, name: cocFormName.name, formName: cocFormName.displayFormName };
}

const COLUMNS_CONFIG_SEPARATOR = "||";
