import _ from "lodash";
import { Section, SectionWithPeriods } from "../../../domain/common/entities/DataForm";
import { DataElement } from "../../../domain/common/entities/DataElement";
import { Id } from "../../../domain/common/entities/Base";
import {
    CategoryOptionCombo,
    DEFAULT_CATEGORY_OPTION_COMBO_CODE,
} from "../../../domain/common/entities/CategoryOptionCombo";
import { Maybe } from "../../../utils/ts-utils";
import { getDescription } from "../../../utils/viewTypes";
import { DataFormInfo } from "./AutogeneratedForm";
import { getFormulaByColumnName, Summary } from "./GridWithCatOptionCombosViewModel";
import {
    getIndicatorRelatedToDataElement,
    getNonDirectionalIndicatorsCountAtSectionStart,
    Indicator,
} from "../../../domain/common/entities/Indicator";
import { GridViewModel } from "./GridFormViewModel";
import { getIndexedLabel } from "./DataTableSection";
import { Period, PeriodType } from "../../../domain/common/entities/Period";
import { isToggleMultipleDeDisabled } from "../../../domain/common/entities/ToggleMultiple";
import { getIndexedIndicator } from "./utils/indicatorIndexing";

export interface GridWithPeriodsI {
    id: string;
    name: string;
    rows: Row[];
    periods: Period[];
    showIndex: Section["showIndex"];
    tabs: Section["tabs"];
    toggle: Section["toggle"];
    toggleMultiple: Section["toggleMultiple"];
    texts: Section["texts"];
    periodTabs: PeriodTab[];
    summary: Summary[];
    indicators: Indicator[];
    indicatorsPosition: Section["indicatorsPosition"];
    lockException: boolean;
    hidden: boolean;
}

interface DataElementRow {
    type: "dataElement" | "dataElementFile";
    dataElement: DataElement;
    indicator: Maybe<Indicator>;
}

interface DataElementGroup {
    type: "group";
    groupDescription: Maybe<string>;
    name: string;
    rows: DataElementRow[];
}

export interface DataElementSubGroupRow {
    indicator: Maybe<Indicator>;
    groupName: Maybe<string>;
    subGroup: Maybe<string>;
    colSpan: string;
    dataElement: DataElement;
    dataElementsPerSubGroup: number;
}

interface DataElementSubGroup {
    type: "subGroup";
    rows: DataElementSubGroupRow[];
}

type Row = DataElementGroup | DataElementSubGroup | DataElementRow;

const separator = /:| - /;

export class GridWithPeriodsViewModel {
    static get(section: SectionWithPeriods, dataFormInfo: DataFormInfo): GridWithPeriodsI {
        const rows = GridWithPeriodsViewModel.getRows(section, dataFormInfo);
        const summary = GridWithPeriodsViewModel.getSummary(section);
        const indicatorIndexOffset = section.indicatorsPosition === "start" ? 0 : section.dataElements.length;
        const indicators = GridWithPeriodsViewModel.getIndicators(rows, section).map((indicator, index) =>
            getIndexedIndicator(section, dataFormInfo, indicator, indicatorIndexOffset + index + 1)
        );
        const lockException = dataFormInfo.metadata.dataForm.periodType !== PeriodType.YEARLY;

        return {
            id: section.id,
            name: section.name,
            rows: rows,
            periods: section.periods,
            toggle: section.toggle,
            texts: section.texts,
            tabs: section.tabs,
            showIndex: section.showIndex,
            toggleMultiple: section.toggleMultiple,
            summary: section.totals ? summary : [],
            indicators: indicators,
            indicatorsPosition: section.indicatorsPosition,
            lockException: lockException,
            periodTabs: this.buildTabs(section.dataElements),
            hidden: section.hidden || false,
        };
    }

    private static getIndicators(rows: Row[], section: SectionWithPeriods): Indicator[] {
        const indicatorsRelatedToDataElements = getIndicatorIdsFromRows(rows);

        return indicatorsRelatedToDataElements.length > 0
            ? section.indicators.filter(indicator => !indicatorsRelatedToDataElements.includes(indicator.id))
            : section.indicators;
    }

    private static getRows(section: SectionWithPeriods, dataFormInfo: DataFormInfo) {
        return _(section.dataElements)
            .groupBy(dataElement => _(dataElement.name).split(separator).first())
            .toPairs()
            .map(([groupName, dataElementsForGroup]): Row => {
                if (dataElementsForGroup.length === 1) {
                    const firstDataElement = dataElementsForGroup[0];
                    const code = firstDataElement.code;
                    const indicatorBase = getIndicatorRelatedToDataElement(section.indicators, code);
                    const indicator = indicatorBase
                        ? getIndexedIndicator(section, dataFormInfo, indicatorBase)
                        : undefined;
                    const orgUnitCode = dataFormInfo.orgUnit.code;
                    return {
                        type: firstDataElement.type === "FILE" ? "dataElementFile" : "dataElement",
                        dataElement: {
                            ...firstDataElement,
                            name: getDataElementLabel(firstDataElement, section, dataFormInfo, firstDataElement.name),
                            htmlText: getDataElementHtmlText(firstDataElement, section, dataFormInfo),
                            disabled:
                                firstDataElement.disabled ??
                                isToggleMultipleDeDisabled(section, firstDataElement, orgUnitCode),
                        },
                        indicator: indicator,
                    };
                } else {
                    const hasSubGroup = _(dataElementsForGroup).some(dataElement => isRowSubGroup(dataElement));

                    if (hasSubGroup) {
                        const subGroups = _(dataElementsForGroup)
                            .map((dataElement, index) => {
                                const hasSubGroup = isRowSubGroup(dataElement);
                                if (!hasSubGroup) return undefined;

                                return {
                                    position: index,
                                    subGroup: _(dataElement.name).split(separator).nth(1),
                                };
                            })
                            .compact()
                            .value();

                        const uniqueSubGroups = _(subGroups)
                            .uniqBy(subGroup => subGroup.subGroup)
                            .value();

                        const rows = dataElementsForGroup.map((dataElement, index) => {
                            const hasSubGroup = isRowSubGroup(dataElement);
                            const subGroup = uniqueSubGroups.find(subGroup => subGroup.position === index);

                            const indicatorBase = getIndicatorRelatedToDataElement(
                                section.indicators,
                                dataElement.code
                            );
                            const indicator = indicatorBase
                                ? getIndexedIndicator(section, dataFormInfo, indicatorBase)
                                : undefined;
                            const orgUnitCode = dataFormInfo.orgUnit.code;

                            return {
                                groupName: index === 0 ? groupName : undefined,
                                subGroup: subGroup ? subGroup.subGroup : undefined,
                                colSpan: hasSubGroup ? "0" : "2",
                                dataElement: {
                                    ...dataElement,
                                    name: getDataElementLabel(dataElement, section, dataFormInfo, dataElement.name),
                                    htmlText: getDataElementHtmlText(dataElement, section, dataFormInfo),
                                    disabled:
                                        dataElement.disabled ??
                                        isToggleMultipleDeDisabled(section, dataElement, orgUnitCode),
                                },
                                indicator: indicator,
                                dataElementsPerSubGroup: subGroup
                                    ? subGroups.filter(sg => sg.subGroup === subGroup.subGroup).length
                                    : 0,
                            };
                        });

                        return { type: "subGroup", rows: rows };
                    } else {
                        const firstDeInGroup = dataElementsForGroup[0];
                        if (!firstDeInGroup) {
                            throw new Error("Data element group is empty");
                        }

                        const firstDeCode = firstDeInGroup.code;
                        const groupDescription = getDescription(section.groupDescriptions, dataFormInfo, firstDeCode);

                        return {
                            type: "group",
                            name: groupName,
                            groupDescription: groupDescription,
                            rows: dataElementsForGroup.map(dataElement => {
                                const indicatorBase = getIndicatorRelatedToDataElement(
                                    section.indicators,
                                    dataElement.code
                                );
                                const indicator = indicatorBase
                                    ? getIndexedIndicator(section, dataFormInfo, indicatorBase)
                                    : undefined;
                                const orgUnitCode = dataFormInfo.orgUnit.code;

                                return {
                                    type: "dataElement",
                                    dataElement: {
                                        ...dataElement,
                                        name: getDataElementLabel(dataElement, section, dataFormInfo, dataElement.name),
                                        htmlText: getDataElementHtmlText(dataElement, section, dataFormInfo),
                                        disabled:
                                            dataElement.disabled ??
                                            isToggleMultipleDeDisabled(section, dataElement, orgUnitCode),
                                    },
                                    indicator: indicator,
                                };
                            }),
                        };
                    }
                }
            })
            .value();
    }

    private static getSummary(section: SectionWithPeriods): Summary[] {
        return _(section.totals)
            .map((sectionTotal, key) => {
                const cellTotals = section.periods.map(column => {
                    const allDataElements = section.dataElements;
                    const selectedDataElements = allDataElements.filter(dataElement =>
                        sectionTotal.dataElementsCodes.includes(dataElement.code)
                    );

                    const columnWithDataElements = GridViewModel.getColumnWithDataElements(
                        selectedDataElements,
                        column.id
                    );

                    return {
                        columnName: column.label,
                        formula: getFormulaByColumnName(section, "") || sectionTotal.formula || "",
                        items: columnWithDataElements,
                        strict: sectionTotal.strict,
                    };
                });

                return {
                    cellName: key,
                    cells: cellTotals,
                };
            })
            .filter(summaryRow => summaryRow.cells.every(cell => cell.items.length > 0))
            .value();
    }

    private static buildTabs(dataElements: DataElement[]): PeriodTab[] {
        const uniqueCategoryOptions = _(dataElements)
            .flatMap(dataElement => dataElement.categoryCombos.categoryOptionCombos)
            .uniqBy(categoryOptionCombo => categoryOptionCombo.id)
            .value();

        if (this.hasOnlyDefaultCategoryOption(uniqueCategoryOptions)) return [];

        return _(uniqueCategoryOptions)
            .map(categoryOption => {
                return { id: categoryOption.id, name: categoryOption.name };
            })
            .uniqBy(periodTab => periodTab.id)
            .value();
    }

    private static hasOnlyDefaultCategoryOption(allCategoryOptions: CategoryOptionCombo[]): boolean {
        return allCategoryOptions.filter(c => c.name === DEFAULT_CATEGORY_OPTION_COMBO_CODE).length === 1;
    }
}

function getIndicatorIdsFromRows(rows: Row[]) {
    return _(rows)
        .flatMap(row => {
            if (row.type === "dataElement") {
                return row.indicator?.id || [];
            } else if (row.type === "group") {
                return row.rows.map(row => row.indicator?.id);
            } else if (row.type === "subGroup") {
                return row.rows.map(row => row.indicator?.id);
            }
        })
        .compact()
        .value();
}

function isRowSubGroup(dataElement: DataElement): boolean {
    return dataElement.name.split(separator).length === 3;
}

function getDataElementLabel(
    dataElement: DataElement,
    section: SectionWithPeriods,
    dataFormInfo: DataFormInfo,
    label: string
) {
    const deName = _(label).split(separator).last() || "-";
    const deIndex = section.dataElements.findIndex(de => de.id === dataElement.id) + 1;
    return getIndexedLabel(
        section,
        dataFormInfo,
        deName,
        deIndex + getNonDirectionalIndicatorsCountAtSectionStart(section)
    );
}

function getDataElementHtmlText(dataElement: DataElement, section: SectionWithPeriods, dataFormInfo: DataFormInfo) {
    if (!dataElement.htmlText) return undefined;
    return getDataElementLabel(dataElement, section, dataFormInfo, dataElement.htmlText);
}

type PeriodTab = { id: Id | undefined; name: string };
