import React from "react";
import {
    DataTable,
    TableHead,
    DataTableRow,
    TableBody,
    // @ts-ignore
} from "@dhis2/ui";
import { Grid, GridViewModel, Row } from "./GridFormViewModel";
import { DataFormInfo } from "./AutogeneratedForm";
import { SectionGrid } from "../../../domain/common/entities/DataForm";
import { DataElementItem } from "./DataElementItem";
import { makeStyles } from "@material-ui/core";
import DataTableSection from "./DataTableSection";
import { CustomDataTableCell, CustomDataTableColumnHeader, fixHeaderClasses } from "./datatables/CustomDataTables";
import { DataTableCellFormula } from "./datatables/DataTableCellFormula";
import { DataTableCellRowName } from "./datatables/DataTableCellRowName";
import _ from "lodash";
import { IndicatorItem, RowIndicatorItem } from "../../components/IndicatorItem/IndicatorItem";
import i18n from "../../../locales";
import { Maybe } from "../../../utils/ts-utils";
import { useSyncedScroll } from "./hooks/Scroll";

/*
 * Convert data forms into table, using "-" as a separator. An example for section ITNs:
 *
 *    - ITNs - Basic - Written Policy
 *    - ITNs - Basic - Policy Implemented
 *    - ITNs - Extended - Written Policy
 *    - ITNs - Extended - Policy Implemented
 *
 *    This will create this table:
 *
 *    ITNs            | Written Policy | Policy Implemented |
 *    ITNs - Basic    |                |                    |
 *    ITNs - Extended |                |                    |
 **/

export interface GridFormProps {
    dataFormInfo: DataFormInfo;
    section: SectionGrid;
}

const GridForm: React.FC<GridFormProps> = props => {
    const { dataFormInfo, section } = props;
    const grid = React.useMemo(() => GridViewModel.get(section, dataFormInfo, "grid"), [section, dataFormInfo]);
    const classes = useStyles();

    const { wrapper1Ref, wrapper2Ref, wrapper2Width } = useSyncedScroll({ enable: section.enableTopScroll });

    const fixColumns = section.fixedHeaders;
    const fixRows = section.fixedRowNames;
    const mainContentStyles = fixColumns ? fixHeaderClasses.fixedHeaders : {};
    const firstColumnWidth = section.firstColumnConfig?.width || 800;

    const NonDirectionalIndicators = grid.nonDirectionalIndicators.map(indicator => (
        <RowIndicatorItem
            key={`parent_${indicator.id}`}
            indicator={indicator}
            colSpan="2"
            dataFormInfo={dataFormInfo}
            periods={[grid.dataEntryPeriod?.id || dataFormInfo.period]}
        />
    ));
    return (
        <DataTableSection section={grid} sectionStyles={props.section.styles} dataFormInfo={dataFormInfo}>
            {section.enableTopScroll && (
                <div style={{ overflowX: "scroll", overflowY: "hidden", height: "11px" }} ref={wrapper1Ref}>
                    <div style={{ height: "11px", width: `${wrapper2Width}px` }}></div>
                </div>
            )}

            <div ref={wrapper2Ref} style={mainContentStyles}>
                <DataTable className={classes.table}>
                    <TableHead className={fixColumns ? classes.tableHeader : ""}>
                        <DataTableRow>
                            {grid.hasGroups && (
                                <>
                                    <CustomDataTableColumnHeader
                                        backgroundColor={props.section.styles.columns.backgroundColor}
                                        position={fixColumns ? "sticky" : undefined}
                                        left={fixColumns ? "0" : undefined}
                                    ></CustomDataTableColumnHeader>
                                    <CustomDataTableColumnHeader
                                        backgroundColor={props.section.styles.columns.backgroundColor}
                                        position={fixColumns ? "sticky" : undefined}
                                        left={fixColumns ? "40px" : undefined}
                                    ></CustomDataTableColumnHeader>
                                </>
                            )}
                            {grid.useIndexes ? (
                                <CustomDataTableColumnHeader
                                    backgroundColor={props.section.styles.columns.backgroundColor}
                                    width="30px"
                                >
                                    <span className={classes.header}>#</span>{" "}
                                </CustomDataTableColumnHeader>
                            ) : (
                                !_.isEmpty(grid.rows) && (
                                    <CustomDataTableColumnHeader
                                        backgroundColor={props.section.styles.columns.backgroundColor}
                                        width={`${firstColumnWidth}px`}
                                        position={fixColumns ? "sticky" : undefined}
                                        left={fixColumns ? "162px" : undefined}
                                    >
                                        <span className={classes.header}>
                                            {section.firstColumnConfig?.header || ""}
                                        </span>
                                    </CustomDataTableColumnHeader>
                                )
                            )}

                            {grid.dataEntryPeriod && (
                                <CustomDataTableColumnHeader
                                    backgroundColor={props.section.styles.columns.backgroundColor}
                                    width="50px"
                                >
                                    <span className={classes.header}>
                                        {props.section.texts.periodHeader ?? i18n.t("Period")}
                                    </span>
                                </CustomDataTableColumnHeader>
                            )}

                            {grid.hasIndicatorsBefore && (
                                <CustomDataTableColumnHeader
                                    backgroundColor={section.styles.columns.backgroundColor}
                                    key="column-indicators-before"
                                >
                                    {grid.indicatorsConfig.before?.headers.map(indicatorHeader => (
                                        <span className={classes.header} key={indicatorHeader}>
                                            {indicatorHeader}
                                        </span>
                                    ))}
                                </CustomDataTableColumnHeader>
                            )}

                            {grid.columns.map(column => {
                                if (!column.isVisible) {
                                    return null;
                                }
                                return (
                                    <CustomDataTableColumnHeader
                                        backgroundColor={props.section.styles.columns.backgroundColor}
                                        className={classes.columnWidth}
                                        key={`column-${column.name}`}
                                    >
                                        <div className={classes.header}>
                                            <span>{column.name}</span>
                                            <span
                                                className={classes.description}
                                                dangerouslySetInnerHTML={{ __html: column.description || "" }}
                                            ></span>
                                        </div>
                                    </CustomDataTableColumnHeader>
                                );
                            })}

                            {grid.hasIndicatorsAfter && (
                                <CustomDataTableColumnHeader
                                    backgroundColor={section.styles.columns.backgroundColor}
                                    key="column-indicators-after"
                                >
                                    {grid.indicatorsConfig.after?.headers.map(indicatorHeader => (
                                        <span className={classes.header} key={indicatorHeader}>
                                            {indicatorHeader}
                                        </span>
                                    ))}
                                </CustomDataTableColumnHeader>
                            )}
                        </DataTableRow>
                    </TableHead>

                    <TableBody>
                        {grid.indicatorsConfig.position === "start" && NonDirectionalIndicators}

                        {grid.rows.map((row, idx) => {
                            return (
                                <DataTableRow key={`row.name-${row.name}`}>
                                    <GridGroups
                                        grid={grid}
                                        row={row}
                                        backgroundColor={props.section.styles.rows.backgroundColor}
                                        fixed={fixRows}
                                    />

                                    <GridSubGroups
                                        grid={grid}
                                        row={row}
                                        backgroundColor={props.section.styles.rows.backgroundColor}
                                        fixed={fixRows}
                                    />

                                    <CustomDataTableCell
                                        position={fixRows ? "sticky" : undefined}
                                        left={fixRows ? "162px" : undefined}
                                        backgroundColor={props.section.styles.rows.backgroundColor}
                                        zIndex={fixRows ? 2 : undefined}
                                    >
                                        <DataTableCellRowName
                                            html={row.htmlText}
                                            name={grid.useIndexes ? (idx + 1).toString() : row.name}
                                        />
                                    </CustomDataTableCell>

                                    {grid.dataEntryPeriod && (
                                        <CustomDataTableCell
                                            backgroundColor={props.section.styles.rows.backgroundColor}
                                        >
                                            <span>{grid.dataEntryPeriod.label}</span>
                                        </CustomDataTableCell>
                                    )}

                                    {row.indicators.before.map(indicator => (
                                        <IndicatorItem
                                            key={`${indicator.id}-${row.name}`}
                                            indicator={indicator}
                                            dataFormInfo={dataFormInfo}
                                            periods={[grid.dataEntryPeriod?.id || dataFormInfo.period]}
                                        />
                                    ))}

                                    {row.items
                                        .filter(item => item.isVisible)
                                        .map((item, idx) =>
                                            item.dataElement ? (
                                                <CustomDataTableCell
                                                    backgroundColor={props.section.styles.rows.backgroundColor}
                                                    key={item.dataElement.id}
                                                >
                                                    <DataElementItem
                                                        columnTotal={item.columnTotal}
                                                        columnDataElements={item.columnDataElements}
                                                        manualyDisabled={item.disabled}
                                                        noComment={item.disableComments}
                                                        dataElement={item.dataElement}
                                                        dataFormInfo={dataFormInfo}
                                                        rows={grid.rows}
                                                        period={grid.dataEntryPeriod?.id || dataFormInfo.period}
                                                        lockException={grid.dataEntryPeriod !== undefined}
                                                    />
                                                </CustomDataTableCell>
                                            ) : (
                                                <CustomDataTableCell
                                                    backgroundColor={props.section.styles.rows.backgroundColor}
                                                    key={`cell-${idx}`}
                                                ></CustomDataTableCell>
                                            )
                                        )}

                                    {row.indicators.after.map(indicator => (
                                        <IndicatorItem
                                            key={`${indicator.id}-${row.name}`}
                                            indicator={indicator}
                                            dataFormInfo={dataFormInfo}
                                            periods={[grid.dataEntryPeriod?.id || dataFormInfo.period]}
                                        />
                                    ))}
                                </DataTableRow>
                            );
                        })}
                        {grid.summary.map(summary => (
                            <DataTableRow key={`total-custom-row-${summary.cellName}`}>
                                <CustomDataTableCell
                                    backgroundColor={props.section.styles.totals.backgroundColor}
                                    key={`total-column-${summary.cellName}`}
                                >
                                    {summary.cellName}
                                </CustomDataTableCell>
                                {summary.cells.map(itemTotal => {
                                    return (
                                        <DataTableCellFormula
                                            key={itemTotal.columnName}
                                            dataFormInfo={dataFormInfo}
                                            styles={props.section.styles}
                                            total={itemTotal}
                                            formula={itemTotal.formula}
                                        />
                                    );
                                })}
                            </DataTableRow>
                        ))}

                        {grid.indicatorsConfig.position === "end" && NonDirectionalIndicators}
                    </TableBody>
                </DataTable>
            </div>
        </DataTableSection>
    );
};

const GridGroups: React.FC<{ grid: Grid; row: Row; backgroundColor: Maybe<string>; fixed?: boolean }> = props => {
    const { grid, row, backgroundColor, fixed } = props;
    if (!grid.hasGroups) return null;
    if (!grid.groupInfo) return null;
    if (!row.group) return null;

    const groupInfo = grid.groupInfo[row.group];

    if (groupInfo?.rowName !== row.name) return null;

    return (
        <CustomDataTableCell
            textAlign="center"
            writingMode="sideways-lr"
            rowSpan={groupInfo.rowSpan.toString()}
            backgroundColor={backgroundColor}
            position={fixed ? "sticky" : undefined}
            left={fixed ? "0" : undefined}
            zIndex={fixed ? 2 : undefined}
        >
            <DataTableCellRowName name={row.group} />
        </CustomDataTableCell>
    );
};

const GridSubGroups: React.FC<{ grid: Grid; row: Row; backgroundColor: Maybe<string>; fixed?: boolean }> = props => {
    const { grid, row, backgroundColor, fixed } = props;
    if (!grid.hasGroups) return null;
    if (!grid.subGroupInfo) return null;
    if (!row.subGroup) return null;

    const groupInfo = grid.subGroupInfo[row.subGroup];

    if (groupInfo?.rowName !== row.name) return null;

    return (
        <CustomDataTableCell
            position={fixed ? "sticky" : undefined}
            left={fixed ? "41px" : undefined}
            rowSpan={groupInfo.rowSpan.toString()}
            backgroundColor={backgroundColor}
            zIndex={fixed ? 2 : undefined}
        >
            <DataTableCellRowName name={row.subGroup} />
        </CustomDataTableCell>
    );
};

const useStyles = makeStyles({
    wrapper: { margin: 10 },
    header: {
        fontSize: "1.2em",
        fontWeight: "bold",
        flexDirection: "column",
        textAlign: "center",
        display: "flex",
        padding: "4px",
    },
    description: { fontWeight: "normal", fontSize: "0.8em" },
    table: { borderWidth: "3px !important" },
    columnWidth: { minWidth: "14.25em !important" },
    tableHeader: { position: "sticky", top: 0, left: 0, zIndex: 3 },
});

export default React.memo(GridForm);
