import _ from "lodash";
import { Section, SectionWithPeriods } from "../../../domain/common/entities/DataForm";
import { DataElement } from "../../../domain/common/entities/DataElement";
import { CategoryOptionCombo } from "../../../domain/common/entities/CategoryOptionCombo";
import { Maybe } from "../../../utils/ts-utils";
import { DataFormInfo } from "./AutogeneratedForm";
import { getDescription } from "../../../utils/viewTypes";
import {
    checkIndicatorDirection,
    getNonDirectionalIndicatorsCountAtSectionStart,
    Indicator,
    IndicatorDirection,
    isNonDirectionalIndicator,
} from "../../../domain/common/entities/Indicator";
import { getIndexedLabel } from "./DataTableSection";
import { Period } from "../../../domain/common/entities/Period";
import { isToggleMultipleDeDisabled } from "../../../domain/common/entities/ToggleMultiple";
import { getIndexedIndicator } from "./utils/indicatorIndexing";
import { calculateFormula } from "./datatables/InputFormula";

export interface Grid {
    id: string;
    name: string;
    columns: Column[];
    periods: Period[];
    rows: Row[];
    showIndex: Section["showIndex"];
    tabs: Section["tabs"];
    toggle: SectionWithPeriods["toggle"];
    toggleMultiple: SectionWithPeriods["toggleMultiple"];
    texts: Section["texts"];
    summary: Summary[];
    indicators: Indicator[];
    hidden: boolean;
    hasIndicatorsBefore: boolean;
    hasIndicatorsAfter: boolean;
    nonDirectionalIndicators: Indicator[];
    indicatorsConfig: Section["indicatorsConfig"];
}

interface SubSectionGrid {
    name: string;
    code: Maybe<string>;
    dataElements: DataElement[];
}

interface Column {
    name: string;
    dataElements: DataElement[];
    description?: string;
    isVisible: boolean;
}

type Row = {
    groupName: string;
    groupDescription: Maybe<string>;
    rows: SubRow[];
};

type SubRow = {
    dataElement: DataElement;
    deName: string;
    name: string;
    period?: Period;
    indicators: {
        before: Indicator[];
        after: Indicator[];
    };
};

const separator = " - ";

export function getFormulaByColumnName(section: Section, columnName: string): Maybe<string> {
    if (!section.totals) return undefined;

    const allFormulas = _.flatMap(section.totals, totals => {
        const mappedFormulas = _.map(totals.formulas, (value, key) => ({
            columnKey: key.toLowerCase(),
            formula: value.formula,
        }));

        return totals.formulas ? mappedFormulas : [];
    });

    const columnFormula = _.find(allFormulas, entry => entry.columnKey === columnName.toLowerCase());
    if (!columnFormula) return undefined;

    return columnFormula.formula;
}

export class GridWithCatOptionCombosViewModel {
    static get(section: SectionWithPeriods, dataFormInfo: DataFormInfo): Grid {
        const subsections = _(section.dataElements)
            .flatMap(dataElement => {
                const categoryOptionCombos = dataElement.categoryCombos.categoryOptionCombos;
                return categoryOptionCombos.map(coc => {
                    const categoryOptionCombo = dataElement.categoryCombos.categoryOptionCombos.find(
                        c => c.name === coc.name
                    );
                    return {
                        ...dataElement,
                        cocId: categoryOptionCombo?.id,
                        name: `${coc.name} - ${_(dataElement.name).split(separator).last()}`,
                        fullName: dataElement.name,
                        cocName: coc.formName ?? coc.name,
                        catOptionCode: _(coc.categoryOptions).first()?.code || "",
                    };
                });
            })
            .filter(dataElement => dataElement.cocId !== undefined)
            .groupBy(dataElement => `${dataElement.cocName}--${dataElement.catOptionCode}`)
            .toPairs()
            .map(([groupName, dataElementsForGroup]): SubSectionGrid => {
                const [name, code] = groupName.split("--");
                if (!name) throw Error(`Cannot find column name: ${name}`);
                return {
                    name: name,
                    code: code,
                    dataElements: dataElementsForGroup.map(dataElement => ({
                        ...dataElement,
                        name: dataElement.fullName,
                    })),
                };
            })
            .value();

        const rows = GridWithCatOptionCombosViewModel.getRows(subsections, section, dataFormInfo);
        const columns = GridWithCatOptionCombosViewModel.getColumns(subsections, section, dataFormInfo, rows);
        const summary = GridWithCatOptionCombosViewModel.getSummary(section, columns, dataFormInfo);

        const indicatorIndexOffset = section.indicatorsConfig.position === "start" ? 0 : section.dataElements.length;
        let nonDataElementIndex = 0;
        const indicators = section.indicators.map(indicator => {
            const indexOverride = indicator.dataElement ? undefined : indicatorIndexOffset + ++nonDataElementIndex;
            return getIndexedIndicator(section, dataFormInfo, indicator, indexOverride);
        });

        const allSubRows = rows.flatMap(row => row.rows);
        const hasIndicatorsBefore = allSubRows.some(subRow => subRow.indicators.before.length > 0);
        const hasIndicatorsAfter = allSubRows.some(subRow => subRow.indicators.after.length > 0);
        const nonDirectionalIndicators = indicators.filter(indicator => isNonDirectionalIndicator(indicator));

        return {
            id: section.id,
            indicators: indicators,
            name: section.name,
            columns: columns,
            periods: section.periods,
            rows: rows,
            showIndex: section.showIndex,
            tabs: section.tabs,
            toggle: section.toggle,
            toggleMultiple: section.toggleMultiple,
            texts: section.texts,
            summary: section.totals ? summary : [],
            hidden: section.hidden || false,
            hasIndicatorsBefore,
            hasIndicatorsAfter,
            nonDirectionalIndicators,
            indicatorsConfig: section.indicatorsConfig,
        };
    }

    private static getRows(
        subsections: SubSectionGrid[],
        section: SectionWithPeriods,
        dataFormInfo: DataFormInfo
    ): Row[] {
        return _(subsections)
            .flatMap(subsection => subsection.dataElements)
            .uniqBy(de => de.name)
            .groupBy(de => _(de.name.split(separator)).initial().join(" - "))
            .map((group, groupName) => {
                const firstDeInGroup = _(group).first()?.code || "";
                const groupDescription = getDescription(section.groupDescriptions, dataFormInfo, firstDeInGroup);
                return {
                    groupName: group.length > 1 ? groupName : "",
                    groupDescription: groupDescription,
                    rows: group.flatMap(de => {
                        const deLabel = getDataElementLabel(de, section, dataFormInfo, de.name);
                        const dataElement = { ...de, htmlText: getDataElementHtmlText(de, section, dataFormInfo) };
                        const row: SubRow = {
                            dataElement: dataElement,
                            deName: deLabel,
                            name: de.name,
                            indicators: {
                                before: getFilteredIndicators(section.indicators, dataElement, "before"),
                                after: getFilteredIndicators(section.indicators, dataElement, "after"),
                            },
                        };
                        return section.periods.length > 0 ? section.periods.map(period => ({ ...row, period })) : [row];
                    }),
                };
            })
            .value();
    }

    private static getColumns(
        subsections: SubSectionGrid[],
        section: SectionWithPeriods,
        dataFormInfo: DataFormInfo,
        rows: Row[]
    ): Column[] {
        const subsectionColumns = subsections.map(subsection => {
            const columnDescription = getDescription(section.columnsDescriptions, dataFormInfo, subsection.code || "");
            const orgUnitCode = dataFormInfo.orgUnit.code;
            const columnDataElements = rows
                .flatMap(({ rows }) => subsection.dataElements.filter(de => rows.some(row => row.name === de.name)))
                .map(de => ({ ...de, disabled: isToggleMultipleDeDisabled(section, de, orgUnitCode) }));

            const column: Column = {
                name: subsection.name,
                dataElements: columnDataElements,
                description: columnDescription,
                isVisible: true,
            };
            return GridWithCatOptionCombosViewModel.applyColumnVisibility(section, column, dataFormInfo, subsection);
        });

        const visibleColumns = subsectionColumns.filter(column => column.isVisible);
        return _.orderBy(visibleColumns, [section.sortRowsBy ? section.sortRowsBy : ""]);
    }

    private static getSummary(section: SectionWithPeriods, columns: Column[], dataFormInfo: DataFormInfo): Summary[] {
        return _(section.totals)
            .map((sectionTotal, key) => {
                const cellTotals = columns.map(column => {
                    const allDataElements = dataFormInfo.metadata.dataForm.dataElements;
                    const selectedDataElements = allDataElements.filter(dataElement =>
                        sectionTotal.dataElementsCodes.includes(dataElement.code)
                    );

                    const columnWithDataElements = GridWithCatOptionCombosViewModel.getColumnWithDataElements(
                        selectedDataElements,
                        column
                    );

                    return {
                        columnName: column.name,
                        formula: getFormulaByColumnName(section, column.name) || sectionTotal.formula || "",
                        items: columnWithDataElements,
                    };
                });

                return {
                    cellName: key,
                    cells: cellTotals,
                };
            })
            .filter(summaryRow => summaryRow.cells.every(cell => cell.items.length > 0))
            .value();
    }

    private static getColumnWithDataElements(selectedDataElements: DataElement[], column: Column): TotalItem[] {
        const hasInvalidDataElement = selectedDataElements.some(dataElement => {
            if (dataElement.type !== "NUMBER") return true;

            const categoryOptionCombo = getCategoryOptionComboByColumnName(dataElement, column);
            return categoryOptionCombo === undefined;
        });

        if (hasInvalidDataElement) return [];

        return _(selectedDataElements)
            .map((dataElement): TotalItem => {
                const categoryOptionCombo = getCategoryOptionComboByColumnName(dataElement, column);
                if (!categoryOptionCombo)
                    throw new Error(
                        `Cannot find categoryOptionCombo in column ${column.name} for dataElement ${dataElement.code}`
                    );

                return { dataElement, categoryOptionCombo };
            })
            .value();
    }

    /**
     * Returns the column with the visible property applied based on the section's columnsConfig.
     * columnConfig key can be either "categoryOptionCode" or "dataElementCode||categoryOptionCode".
     * If both "categoryOptionCode" and "dataElementCode||categoryOptionCode" are defined, "categoryOptionCode" takes precendence
     */
    private static applyColumnVisibility(
        section: SectionWithPeriods,
        column: Column,
        dataFormInfo: DataFormInfo,
        subsection: SubSectionGrid
    ): Column {
        if (!section.columnsConfig) return column;

        const applyVisibilityRule = (configKey: string): Maybe<Column> => {
            const visibleRule = section.columnsConfig?.[configKey]?.rules?.visible;
            if (!visibleRule) return undefined;

            const dataElementCodesForFormula = _(visibleRule.dataElements)
                .map(de => de.code)
                .compact()
                .value();

            const value = calculateFormula({
                dataElementCodes: dataElementCodesForFormula,
                dataFormInfo,
                formula: visibleRule.formula.value ?? "",
                period: dataFormInfo.period,
            });

            const isVisible = value === visibleRule.formula.condition;
            return { ...column, isVisible };
        };

        const categoryOptionCode = subsection.code || "";
        const columnWithCatOptionVisibility = applyVisibilityRule(categoryOptionCode);
        if (columnWithCatOptionVisibility) return columnWithCatOptionVisibility;

        const dataElementConfigKeys = subsection.dataElements
            .map(de => `${de.code}${COLUMNS_CONFIG_SEPARATOR}${categoryOptionCode}`)
            .filter(key => key in (section.columnsConfig || {}));

        const isVisibleForAllRows = dataElementConfigKeys.every(configKey => {
            const columnWithDeVisibility = applyVisibilityRule(configKey);
            return columnWithDeVisibility ? columnWithDeVisibility.isVisible : true;
        });

        if (!isVisibleForAllRows) {
            return { ...column, isVisible: false };
        }

        return column;
    }
}

export type Summary = { cells: CellTotal[]; cellName: string };
export type CellTotal = { formula: string; columnName: string; items: TotalItem[] };
export type TotalItem = { dataElement: DataElement; categoryOptionCombo: CategoryOptionCombo };

function getDataElementLabel(
    dataElement: DataElement,
    section: SectionWithPeriods,
    dataFormInfo: DataFormInfo,
    label: string
) {
    const deName = _.last(label.split(separator)) ?? "";
    const deIndex = section.dataElements.findIndex(de => de.id === dataElement.id) + 1;
    return getIndexedLabel(
        section,
        dataFormInfo,
        deName,
        deIndex + getNonDirectionalIndicatorsCountAtSectionStart(section)
    );
}

function getDataElementHtmlText(dataElement: DataElement, section: SectionWithPeriods, dataFormInfo: DataFormInfo) {
    if (!dataElement.htmlText) return undefined;
    return getDataElementLabel(dataElement, section, dataFormInfo, dataElement.htmlText);
}

function getCategoryOptionComboByColumnName(dataElement: DataElement, column: Column): Maybe<CategoryOptionCombo> {
    return dataElement.categoryCombos.categoryOptionCombos.find(coc => {
        const columnName = coc.formName ?? coc.name;
        return columnName === column.name;
    });
}

function getFilteredIndicators(
    indicators: Indicator[],
    dataElement: DataElement,
    direction: IndicatorDirection
): Indicator[] {
    return indicators.filter(
        indicator => indicator.dataElement?.code === dataElement.code && checkIndicatorDirection(indicator, direction)
    );
}

const COLUMNS_CONFIG_SEPARATOR = "||";
