import React from "react";
import {
    DataTable,
    TableHead,
    DataTableRow,
    TableBody,
    // @ts-ignore
} from "@dhis2/ui";
import { DataFormInfo } from "./AutogeneratedForm";
import { SectionWithSubnationals } from "../../../domain/common/entities/DataForm";
import { DataElementItem } from "./DataElementItem";
import { makeStyles } from "@material-ui/core";
import DataTableSection from "./DataTableSection";
import { GridWithSubNationalViewModel } from "./GridWithSubNationalViewModel";
import i18n from "../../../locales";
import { CustomDataTableCell, CustomDataTableColumnHeader } from "./datatables/CustomDataTables";

export interface GridWithSubNationalProps {
    dataFormInfo: DataFormInfo;
    section: SectionWithSubnationals;
}

const GridWithSubNational: React.FC<GridWithSubNationalProps> = props => {
    const topValue = "0";
    const { dataFormInfo } = props;
    const grid = React.useMemo(() => GridWithSubNationalViewModel.get(props.section), [props.section]);
    const classes = useStyles();

    return (
        <DataTableSection section={grid} sectionStyles={props.section.styles} dataFormInfo={dataFormInfo}>
            <DataTable className={classes.table} layout="fixed" width="initial">
                <TableHead>
                    <DataTableRow>
                        <CustomDataTableColumnHeader>SN</CustomDataTableColumnHeader>
                        <CustomDataTableColumnHeader></CustomDataTableColumnHeader>
                        {grid.parentColumns.map((column, index) => {
                            return (
                                <CustomDataTableColumnHeader
                                    style={props.section.styles.columns}
                                    key={index}
                                    className={classes.centerSpan}
                                >
                                    <span>{column.name}</span>
                                </CustomDataTableColumnHeader>
                            );
                        })}
                    </DataTableRow>

                    <DataTableRow>
                        <CustomDataTableColumnHeader style={props.section.styles.columns} fixed top={topValue}>
                            {i18n.t("Occupation")}
                        </CustomDataTableColumnHeader>
                        <CustomDataTableColumnHeader style={props.section.styles.columns} fixed top={topValue}>
                            {i18n.t("Subnational level name")}
                        </CustomDataTableColumnHeader>

                        {grid.columns.map(column => (
                            <CustomDataTableColumnHeader
                                style={props.section.styles.columns}
                                key={`column-${column.name}`}
                                fixed
                                top={topValue}
                                className={classes.columnWidth}
                            >
                                <span>{column.deName}</span>
                            </CustomDataTableColumnHeader>
                        ))}
                    </DataTableRow>
                </TableHead>

                <TableBody>
                    {grid.rows.map((row, idx) => (
                        <DataTableRow key={`policy-${row.name}`}>
                            <CustomDataTableCell style={props.section.styles.rows} fixed left="0" width="90px">
                                Total
                            </CustomDataTableCell>
                            <CustomDataTableCell
                                style={props.section.styles.rows}
                                fixed
                                left="90px"
                                className={classes.td}
                            >
                                <span>{grid.useIndexes ? (idx + 1).toString() : row.name}</span>
                            </CustomDataTableCell>

                            {row.items.map((item, idx) =>
                                item.dataElement ? (
                                    <CustomDataTableCell
                                        style={props.section.styles.rows}
                                        key={item.dataElement.orgUnit + item.dataElement.id + item.dataElement.cocId}
                                    >
                                        <DataElementItem
                                            dataElement={item.dataElement}
                                            dataFormInfo={dataFormInfo}
                                            manualyDisabled={item.manualyDisabled}
                                            columnDataElements={item.columnDataElements}
                                            columnTotal={item.columnTotal}
                                            noComment={item.column.name !== "Source type for HWF - (Inputs & Outputs)"}
                                        />
                                    </CustomDataTableCell>
                                ) : (
                                    <CustomDataTableCell
                                        style={props.section.styles.rows}
                                        key={`cell-${idx}`}
                                    ></CustomDataTableCell>
                                )
                            )}
                        </DataTableRow>
                    ))}
                </TableBody>
            </DataTable>
        </DataTableSection>
    );
};

const useStyles = makeStyles({
    wrapper: { margin: 10 },
    header: { fontSize: "1.4em", fontWeight: "bold" as const },
    table: { borderWidth: "3px !important", minWidth: "100%" },
    td: { minWidth: "200px !important" },
    columnWidth: { minWidth: "6.2em !important" },
    source: { maxWidth: "35% !important", width: "33% !important", minWidth: "15% !important" },
    centerSpan: {
        "& span": {
            alignItems: "center",
        },
    },
});

export default React.memo(GridWithSubNational);
