import _ from "lodash";
import { Section, SectionWithPeriods, Texts } from "../../../domain/common/entities/DataForm";
import { DataElement } from "../../../domain/common/entities/DataElement";
import { CategoryOptionCombo } from "../../../domain/common/entities/CategoryOptionCombo";
import { Maybe } from "../../../utils/ts-utils";
import { DataFormInfo } from "./AutogeneratedForm";
import { getDescription } from "../../../utils/viewTypes";
import { checkIndicatorDirection, Indicator, IndicatorDirection } from "../../../domain/common/entities/Indicator";
import { getIndexedLabel } from "./DataTableSection";

export interface Grid {
    id: string;
    name: string;
    columns: Column[];
    periods: string[];
    rows: Row[];
    showIndex: Section["showIndex"];
    tabs: Section["tabs"];
    toggle: SectionWithPeriods["toggle"];
    toggleMultiple: SectionWithPeriods["toggleMultiple"];
    texts: Texts;
    summary: Summary[];
    indicators: Indicator[];
    hidden: boolean;
}

interface SubSectionGrid {
    name: string;
    code: Maybe<string>;
    dataElements: DataElement[];
}

interface Column {
    name: string;
    dataElements: DataElement[];
    description?: string;
}

type Row = {
    groupName: string;
    groupDescription: Maybe<string>;
    rows: SubRow[];
};

type SubRow = {
    dataElement: DataElement;
    deName: string;
    name: string;
    period?: string;
};

const separator = " - ";

export function getFormulaByColumnName(section: Section, columnName: string): Maybe<string> {
    if (!section.totals) return undefined;

    const allFormulas = _.flatMap(section.totals, totals => {
        const mappedFormulas = _.map(totals.formulas, (value, key) => ({
            columnKey: key.toLowerCase(),
            formula: value.formula,
        }));

        return totals.formulas ? mappedFormulas : [];
    });

    const columnFormula = _.find(allFormulas, entry => entry.columnKey === columnName.toLowerCase());
    if (!columnFormula) return undefined;

    return columnFormula.formula;
}

export class GridWithCatOptionCombosViewModel {
    static get(section: SectionWithPeriods, dataFormInfo: DataFormInfo): Grid {
        const subsections = _(section.dataElements)
            .flatMap(dataElement => {
                const categoryOptionCombos = dataElement.categoryCombos.categoryOptionCombos;
                return categoryOptionCombos.map(coc => {
                    const categoryOptionCombo = dataElement.categoryCombos.categoryOptionCombos.find(
                        c => c.name === coc.name
                    );
                    return {
                        ...dataElement,
                        cocId: categoryOptionCombo?.id,
                        name: `${coc.name} - ${_(dataElement.name).split(separator).last()}`,
                        fullName: dataElement.name,
                        cocName: coc.formName ?? coc.name,
                        catOptionCode: _(coc.categoryOptions).first()?.code || "",
                    };
                });
            })
            .filter(dataElement => dataElement.cocId !== undefined)
            .groupBy(dataElement => `${dataElement.cocName}--${dataElement.catOptionCode}`)
            .toPairs()
            .map(([groupName, dataElementsForGroup]): SubSectionGrid => {
                const [name, code] = groupName.split("--");
                if (!name) throw Error(`Cannot find column name: ${name}`);
                return {
                    name: name,
                    code: code,
                    dataElements: dataElementsForGroup.map(dataElement => ({
                        ...dataElement,
                        name: dataElement.fullName,
                    })),
                };
            })
            .value();

        const rows = GridWithCatOptionCombosViewModel.getRows(subsections, section, dataFormInfo);
        const columns = GridWithCatOptionCombosViewModel.getColumns(subsections, section, dataFormInfo, rows);
        const summary = GridWithCatOptionCombosViewModel.getSummary(section, columns, dataFormInfo);

        return {
            id: section.id,
            indicators: section.indicators,
            name: section.name,
            columns: columns,
            periods: section.periods,
            rows: rows,
            showIndex: section.showIndex,
            tabs: section.tabs,
            toggle: section.toggle,
            toggleMultiple: section.toggleMultiple,
            texts: section.texts,
            summary: section.totals ? summary : [],
            hidden: section.hidden || false,
        };
    }

    private static getRows(
        subsections: SubSectionGrid[],
        section: SectionWithPeriods,
        dataFormInfo: DataFormInfo
    ): Row[] {
        return _(subsections)
            .flatMap(subsection => subsection.dataElements)
            .uniqBy(de => de.name)
            .groupBy(de => _(de.name.split(separator)).initial().join(" - "))
            .map((group, groupName) => {
                const firstDeInGroup = _(group).first()?.code || "";
                const groupDescription = getDescription(section.groupDescriptions, dataFormInfo, firstDeInGroup);

                return {
                    groupName: groupName,
                    groupDescription: groupDescription,
                    rows: group.flatMap(de => {
                        const deLabel = getDataElementLabel(de, section);
                        const row = { dataElement: de, deName: deLabel, name: de.name };

                        return section.periods.length > 0 ? section.periods.map(period => ({ ...row, period })) : [row];
                    }),
                };
            })
            .value();
    }

    private static getColumns(
        subsections: SubSectionGrid[],
        section: SectionWithPeriods,
        dataFormInfo: DataFormInfo,
        rows: Row[]
    ): Column[] {
        const subsectionColumns = subsections.map(subsection => {
            const columnDescription = getDescription(section.columnsDescriptions, dataFormInfo, subsection.code || "");
            const columnDataElements = rows.flatMap(row => {
                return subsection.dataElements.filter(de => row.rows.map(r => r.name).includes(de.name));
            });

            return {
                name: subsection.name,
                dataElements: columnDataElements,
                description: columnDescription,
            };
        });

        return _.orderBy(subsectionColumns, [section.sortRowsBy ? section.sortRowsBy : ""]);
    }

    private static getSummary(section: SectionWithPeriods, columns: Column[], dataFormInfo: DataFormInfo): Summary[] {
        return _(section.totals)
            .map((sectionTotal, key) => {
                const cellTotals = columns.map(column => {
                    const allDataElements = dataFormInfo.metadata.dataForm.dataElements;
                    const selectedDataElements = allDataElements.filter(dataElement =>
                        sectionTotal.dataElementsCodes.includes(dataElement.code)
                    );

                    const columnWithDataElements = GridWithCatOptionCombosViewModel.getColumnWithDataElements(
                        selectedDataElements,
                        column
                    );

                    return {
                        columnName: column.name,
                        formula: getFormulaByColumnName(section, column.name) || sectionTotal.formula || "",
                        items: columnWithDataElements,
                    };
                });

                return {
                    cellName: key,
                    cells: cellTotals,
                };
            })
            .filter(summaryRow => summaryRow.cells.every(cell => cell.items.length > 0))
            .value();
    }

    private static getColumnWithDataElements(selectedDataElements: DataElement[], column: Column): TotalItem[] {
        const hasInvalidDataElement = selectedDataElements.some(dataElement => {
            if (dataElement.type !== "NUMBER") return true;

            const categoryOptionCombo = getCategoryOptionComboByColumnName(dataElement, column);
            return categoryOptionCombo === undefined;
        });

        if (hasInvalidDataElement) return [];

        return _(selectedDataElements)
            .map((dataElement): TotalItem => {
                const categoryOptionCombo = getCategoryOptionComboByColumnName(dataElement, column);
                if (!categoryOptionCombo)
                    throw new Error(
                        `Cannot find categoryOptionCombo in column ${column.name} for dataElement ${dataElement.code}`
                    );

                return { dataElement, categoryOptionCombo };
            })
            .value();
    }
}

export type Summary = { cells: CellTotal[]; cellName: string };
export type CellTotal = { formula: string; columnName: string; items: TotalItem[] };
export type TotalItem = { dataElement: DataElement; categoryOptionCombo: CategoryOptionCombo };

function getDataElementLabel(dataElement: DataElement, section: SectionWithPeriods) {
    const deName = _.last(dataElement.name.split(separator)) ?? "";
    const deIndex = section.dataElements.findIndex(de => de.id === dataElement.id) + 1;

    return getIndexedLabel(section, deName, deIndex);
}

function getCategoryOptionComboByColumnName(dataElement: DataElement, column: Column): Maybe<CategoryOptionCombo> {
    return dataElement.categoryCombos.categoryOptionCombos.find(coc => {
        const columnName = coc.formName ?? coc.name;
        return columnName === column.name;
    });
}

export function getFilteredIndicators(
    indicators: Indicator[],
    row: SubRow,
    direction: IndicatorDirection
): Maybe<Indicator>[] {
    return indicators.map(indicator =>
        indicator.dataElement?.code === row.dataElement.code && checkIndicatorDirection(indicator, direction)
            ? indicator
            : undefined
    );
}
