import _ from "lodash";
import { Section, SectionWithPeriods, Texts } from "../../../domain/common/entities/DataForm";
import { DataElement } from "../../../domain/common/entities/DataElement";
import { Id } from "../../../domain/common/entities/Base";
import {
    CategoryOptionCombo,
    DEFAULT_CATEGORY_OPTION_COMBO_CODE,
} from "../../../domain/common/entities/CategoryOptionCombo";
import { Maybe } from "../../../utils/ts-utils";
import { getDescription } from "../../../utils/viewTypes";
import { DataFormInfo } from "./AutogeneratedForm";
import { getFormulaByColumnName, Summary } from "./GridWithCatOptionCombosViewModel";
import { getIndicatorRelatedToDataElement, Indicator } from "../../../domain/common/entities/Indicator";
import { GridViewModel } from "./GridFormViewModel";
import { getIndexedLabel } from "./DataTableSection";

export interface GridWithPeriodsI {
    id: string;
    name: string;
    rows: Row[];
    periods: string[];
    showIndex: Section["showIndex"];
    tabs: Section["tabs"];
    toggle: Section["toggle"];
    toggleMultiple: Section["toggleMultiple"];
    texts: Texts;
    periodTabs: PeriodTab[];
    summary: Summary[];
    indicators: Indicator[];
    hidden: boolean;
}

interface DataElementRow {
    type: "dataElement" | "dataElementFile";
    dataElement: DataElement;
    indicator: Maybe<Indicator>;
}

interface DataElementGroup {
    type: "group";
    groupDescription: Maybe<string>;
    name: string;
    rows: DataElementRow[];
}

export interface DataElementSubGroupRow {
    indicator: Maybe<Indicator>;
    groupName: Maybe<string>;
    subGroup: Maybe<string>;
    colSpan: string;
    dataElement: DataElement;
    dataElementsPerSubGroup: number;
}

interface DataElementSubGroup {
    type: "subGroup";
    rows: DataElementSubGroupRow[];
}

type Row = DataElementGroup | DataElementSubGroup | DataElementRow;

const separator = /:| - /;

export class GridWithPeriodsViewModel {
    static get(section: SectionWithPeriods, dataFormInfo: DataFormInfo): GridWithPeriodsI {
        const rows = _(section.dataElements)
            .groupBy(dataElement => _(dataElement.name).split(separator).first())
            .toPairs()
            .map(([groupName, dataElementsForGroup]): Row => {
                if (dataElementsForGroup.length === 1) {
                    const code = dataElementsForGroup[0].code;
                    const indicator = getIndicatorRelatedToDataElement(section.indicators, code);
                    return {
                        type: dataElementsForGroup[0].type === "FILE" ? "dataElementFile" : "dataElement",
                        dataElement: {
                            ...dataElementsForGroup[0],
                            name: getDataElementLabel(dataElementsForGroup[0], section),
                        },
                        indicator: indicator,
                    };
                } else {
                    const hasSubGroup = _(dataElementsForGroup).some(dataElement => isRowSubGroup(dataElement));

                    if (hasSubGroup) {
                        const subGroups = _(dataElementsForGroup)
                            .map((dataElement, index) => {
                                const hasSubGroup = isRowSubGroup(dataElement);
                                if (!hasSubGroup) return undefined;

                                return {
                                    position: index,
                                    subGroup: _(dataElement.name).split(separator).nth(1),
                                };
                            })
                            .compact()
                            .value();

                        const uniqueSubGroups = _(subGroups)
                            .uniqBy(subGroup => subGroup.subGroup)
                            .value();

                        const rows = dataElementsForGroup.map((dataElement, index) => {
                            const hasSubGroup = isRowSubGroup(dataElement);
                            const subGroup = uniqueSubGroups.find(subGroup => subGroup.position === index);

                            const indicator = getIndicatorRelatedToDataElement(section.indicators, dataElement.code);

                            return {
                                groupName: index === 0 ? groupName : undefined,
                                subGroup: subGroup ? subGroup.subGroup : undefined,
                                colSpan: hasSubGroup ? "0" : "2",
                                dataElement: {
                                    ...dataElement,
                                    name: getDataElementLabel(dataElement, section),
                                },
                                indicator: indicator,
                                dataElementsPerSubGroup: subGroup
                                    ? subGroups.filter(sg => sg.subGroup === subGroup.subGroup).length
                                    : 0,
                            };
                        });

                        return { type: "subGroup", rows: rows };
                    } else {
                        const firstDeInGroup = _(dataElementsForGroup).first()?.code || "";
                        const groupDescription = getDescription(
                            section.groupDescriptions,
                            dataFormInfo,
                            firstDeInGroup
                        );

                        return {
                            type: "group",
                            name: groupName,
                            groupDescription: groupDescription,
                            rows: dataElementsForGroup.map(dataElement => {
                                const indicator = getIndicatorRelatedToDataElement(
                                    section.indicators,
                                    dataElement.code
                                );
                                return {
                                    type: "dataElement",
                                    dataElement: {
                                        ...dataElement,
                                        name: getDataElementLabel(dataElement, section),
                                    },
                                    indicator: indicator,
                                };
                            }),
                        };
                    }
                }
            })
            .value();

        const summary = _(section.totals)
            .map((sectionTotal, key) => {
                const cellTotals = section.periods.map(column => {
                    const allDataElements = section.dataElements;
                    const selectedDataElements = allDataElements.filter(dataElement =>
                        sectionTotal.dataElementsCodes.includes(dataElement.code)
                    );

                    const columnWithDataElements = GridViewModel.getColumnWithDataElements(
                        selectedDataElements,
                        column
                    );

                    return {
                        columnName: column,
                        formula: getFormulaByColumnName(section, "") || sectionTotal.formula || "",
                        items: columnWithDataElements,
                    };
                });

                return {
                    cellName: key,
                    cells: cellTotals,
                };
            })
            .filter(summaryRow => summaryRow.cells.every(cell => cell.items.length > 0))
            .value();

        const indicatorsRelatedToDataElements = _(rows)
            .flatMap(row => {
                if (row.type === "dataElement") {
                    return row.indicator?.id || [];
                } else if (row.type === "group") {
                    return row.rows.map(row => row.indicator?.id);
                } else if (row.type === "subGroup") {
                    return row.rows.map(row => row.indicator?.id);
                }
            })
            .compact()
            .value();

        return {
            id: section.id,
            name: section.name,
            rows: rows,
            periods: section.periods,
            showIndex: section.showIndex,
            tabs: section.tabs,
            toggle: section.toggle,
            texts: section.texts,
            periodTabs: this.buildTabs(section.dataElements),
            toggleMultiple: section.toggleMultiple,
            summary: section.totals ? summary : [],
            indicators:
                indicatorsRelatedToDataElements.length > 0
                    ? section.indicators.filter(indicator => !indicatorsRelatedToDataElements.includes(indicator.id))
                    : section.indicators,
            hidden: section.hidden || false,
        };
    }

    private static buildTabs(dataElements: DataElement[]): PeriodTab[] {
        const uniqueCategoryOptions = _(dataElements)
            .flatMap(dataElement => dataElement.categoryCombos.categoryOptionCombos)
            .uniqBy(categoryOptionCombo => categoryOptionCombo.id)
            .value();

        if (this.hasOnlyDefaultCategoryOption(uniqueCategoryOptions)) return [];

        return _(uniqueCategoryOptions)
            .map(categoryOption => {
                return { id: categoryOption.id, name: categoryOption.name };
            })
            .uniqBy(periodTab => periodTab.id)
            .value();
    }

    private static hasOnlyDefaultCategoryOption(allCategoryOptions: CategoryOptionCombo[]): boolean {
        return allCategoryOptions.filter(c => c.name === DEFAULT_CATEGORY_OPTION_COMBO_CODE).length === 1;
    }
}

function isRowSubGroup(dataElement: DataElement): boolean {
    return dataElement.name.split(separator).length === 3;
}

function getDataElementLabel(dataElement: DataElement, section: SectionWithPeriods) {
    const deName = _(dataElement.name).split(separator).last() || "-";
    const deIndex = section.dataElements.findIndex(de => de.id === dataElement.id) + 1;

    return getIndexedLabel(section, deName, deIndex);
}

type PeriodTab = { id: Id | undefined; name: string };
