import _ from "lodash";
import {
    ColumnOrder,
    DataElementWidget,
    Section,
    SectionBase,
    SectionGrid,
} from "../../../domain/common/entities/DataForm";
import { DataElement, DataElementNumber } from "../../../domain/common/entities/DataElement";
import { titleVariant } from "../../../domain/common/entities/TitleVariant";
import { Maybe } from "../../../utils/ts-utils";
import { getFormulaByColumnName, Summary, TotalItem } from "./GridWithCatOptionCombosViewModel";
import { DataFormInfo } from "./AutogeneratedForm";
import { getDescription } from "../../../utils/viewTypes";
import {
    checkIndicatorDirection,
    getIndicatorRelatedToDataElement,
    getNonDirectionalIndicatorsCountAtSectionStart,
    Indicator,
    IndicatorDirection,
    isNonDirectionalIndicator,
} from "../../../domain/common/entities/Indicator";
import { Code } from "../../../domain/common/entities/Base";
import { calculateFormula } from "./datatables/InputFormula";
import { getIndexedLabel } from "./DataTableSection";
import { Period } from "../../../domain/common/entities/Period";
import { isToggleMultipleDeDisabled } from "../../../domain/common/entities/ToggleMultiple";
import { getIndexedIndicator } from "./utils/indicatorIndexing";

export type Grid = GridComponents & {
    dataElements: Array<DataElement & { indicator: Maybe<Indicator> }>;
    id: string;
    name: string;
    columns: Column[];
    rows: Row[];
    showIndex: Section["showIndex"];
    tabs: Section["tabs"];
    toggle: Section["toggle"];
    toggleMultiple: Section["toggleMultiple"];
    useIndexes: boolean;
    texts: Section["texts"];
    titleVariant: titleVariant;
    indicators: Indicator[];
    rowGroups: RowGroup[];
    hasGroups: boolean;
    groupInfo: Record<string, GroupInfo>;
    subGroupInfo: Record<string, GroupInfo>;
    dataEntryPeriod: Maybe<Period>;
    hidden: boolean;
    hasIndicatorsBefore: boolean;
    hasIndicatorsAfter: boolean;
    nonDirectionalIndicators: Indicator[];
    indicatorsConfig: Section["indicatorsConfig"];
};

type GridComponents = {
    columns: Column[];
    rows: Row[];
    summary: Summary[];
};

interface SubSectionGrid {
    name: string;
    dataElements: DataElement[];
}

interface Column {
    code: Code;
    name: string;
    description?: string;
    isSourceType: boolean;
    isVisible: boolean;
}

export interface Row {
    indicator: Maybe<Indicator>;
    includePadding: number;
    name: string;
    htmlText: string;
    group: Maybe<string>;
    subGroup: Maybe<string>;
    items: Array<{
        isVisible: boolean;
        column: Column;
        columnTotal: Maybe<DataElement>;
        columnDataElements: DataElement[];
        dataElement: Maybe<DataElement>;
        disabled: boolean;
        disableComments: boolean;
    }>;
    indicators: {
        before: Indicator[];
        after: Indicator[];
    };
}

const separator = " - ";

type ColumnScoreInput = {
    columnName: string;
    allDataElements: DataElement[];
    priorityByCode: ColumnOrder;
};

type RowNameParts = {
    group: Maybe<string>;
    subGroup: Maybe<string>;
    rowName: string;
    columnName: string;
};

type RowGroup = {
    group: Maybe<string>;
    subGroup: Maybe<string>;
    rows: Row[];
};

export class GridViewModel {
    static get(section: SectionGrid, dataFormInfo: DataFormInfo, viewType: SectionGrid["viewType"]): Grid {
        const dataElements = getDataElementsWithIndexProccessing(section);
        const { columns, rows, summary } = this.getGridComponents(section, dataFormInfo, dataElements, viewType);
        const indicatorIndexOffset =
            section.indicatorsConfig.position === "start" ? 0 : viewType === "grid" ? rows.length : dataElements.length;
        const indicators = this.getIndicators(section).map((indicator, index) =>
            getIndexedIndicator(section, dataFormInfo, indicator, indicatorIndexOffset + index + 1)
        );

        const useIndexes =
            _(rows).every(row => Boolean(row.name.match(/\(\d+\)$/))) &&
            _(rows)
                .groupBy(row => row.name.replace(/\s*\(\d+\)$/, ""))
                .size() === 1;

        const rowGroups = GridViewModel.buildRowGroups(rows);

        const groupInfo = this.buildGroupInfo(rows, "group");
        const subGroupInfo = this.buildGroupInfo(rows, "subGroup");

        const hasIndicatorsBefore = rows.some(row => row.indicators.before.length > 0);
        const hasIndicatorsAfter = rows.some(row => row.indicators.after.length > 0);
        const nonDirectionalIndicators = indicators.filter(indicator => isNonDirectionalIndicator(indicator));

        return {
            id: section.id,
            indicators: indicators,
            name: section.name,
            columns: columns,
            rows: rows,
            toggle: section.toggle,
            toggleMultiple: section.toggleMultiple,
            texts: section.texts,
            useIndexes: useIndexes,
            titleVariant: section.titleVariant,
            summary: section.totals ? summary : [],
            showIndex: section.showIndex,
            tabs: section.tabs,
            dataElements: dataElements.map(dataElement => {
                const indicatorBase = getIndicatorRelatedToDataElement(section.indicators, dataElement.code);
                const indicator = indicatorBase ? getIndexedIndicator(section, dataFormInfo, indicatorBase) : undefined;
                const orgUnitCode = dataFormInfo.orgUnit.code;
                return {
                    ...dataElement,
                    indicator,
                    name: getDataElementLabel(section, dataFormInfo, dataElement, dataElement.name),
                    htmlText: dataElement.htmlText
                        ? getDataElementLabel(section, dataFormInfo, dataElement, dataElement.htmlText)
                        : undefined,
                    disabled: dataElement.disabled || isToggleMultipleDeDisabled(section, dataElement, orgUnitCode),
                };
            }),
            dataEntryPeriod: section.periods[0],
            hidden: section.hidden || false,
            rowGroups,
            hasGroups: section.enableGroups && rowGroups.length > 0,
            groupInfo: groupInfo,
            subGroupInfo: subGroupInfo,
            hasIndicatorsBefore,
            hasIndicatorsAfter,
            nonDirectionalIndicators,
            indicatorsConfig: section.indicatorsConfig,
        };
    }

    private static getGridComponents(
        section: SectionGrid,
        dataFormInfo: DataFormInfo,
        dataElements: DataElement[],
        viewType: SectionGrid["viewType"]
    ): GridComponents {
        const subsections = _(dataElements)
            .groupBy(dataElement => getSubsectionName(dataElement))
            .toPairs()
            .map(
                ([groupName, dataElementsForGroup]): SubSectionGrid => ({
                    name: groupName,
                    dataElements: dataElementsForGroup.map(dataElement => ({
                        ...dataElement,
                        name: _(dataElement.name).split(separator).last() || "-",
                    })),
                })
            )
            .value();

        const baseColumns = GridViewModel.getColumns(subsections, section, dataFormInfo);

        const columnsOrders = section.columnsOrder
            ? _(baseColumns)
                  .sortBy(column => {
                      return this.scoreColumnByLowestDEPriority({
                          columnName: column.name,
                          allDataElements: dataElements,
                          priorityByCode: section.columnsOrder ?? {},
                      });
                  })
                  .value()
            : baseColumns;

        const columns = this.addVisibleToColumns({ columns: columnsOrders, dataFormInfo, section });

        const rows = GridViewModel.getRows(subsections, section, columns, dataElements, dataFormInfo);
        const summary = GridViewModel.getSummary(dataFormInfo, section, columns, viewType);

        return { columns: columns, rows: rows, summary: summary };
    }

    private static getColumns(
        subsections: SubSectionGrid[],
        section: SectionGrid,
        dataFormInfo: DataFormInfo
    ): Column[] {
        const dataElementsConfig = dataFormInfo.metadata.dataForm.options.dataElements;

        return _(subsections)
            .flatMap(subsection => subsection.dataElements)
            .uniqBy(de => de.name)
            .map(({ id, code, name }) => {
                const columnDescription = getDescription(section.columnsDescriptions, dataFormInfo, name);
                const config = dataElementsConfig[id];
                return {
                    code: code,
                    isVisible: true,
                    isSourceType: isSourceTypeColumn(config?.widget),
                    name: name,
                    description: columnDescription,
                };
            })
            .value();
    }

    private static getRows(
        subsections: SubSectionGrid[],
        section: SectionGrid,
        columns: Column[],
        dataElements: DataElement[],
        dataFormInfo: DataFormInfo
    ) {
        const groupsByRow = section.enableGroups ? GridViewModel.groupsByRowName(dataElements) : undefined;

        const dataElementsByTotal = _(section.calculateTotals)
            .groupBy(item => item?.totalDeCode)
            .map((group, totalColumn) => ({
                totalColumn,
                dataElements: group.map(item => _.findKey(section.calculateTotals, obj => obj === item)),
            }))
            .value();

        return subsections.map((subsection, index) => {
            const firstDataElement = _(subsection.dataElements).first();
            const indicator = getIndicatorRelatedToDataElement(section.indicators, firstDataElement?.code || "");
            const items = columns.map(column => {
                const dataElement = subsection.dataElements.find(de => de.name === column.name);
                const deCalculateTotal =
                    section.calculateTotals && dataElement?.code
                        ? section.calculateTotals[dataElement.code]
                        : undefined;

                const parentTotal = deCalculateTotal
                    ? dataElements.find(de => de.code === deCalculateTotal?.totalDeCode)
                    : undefined;

                const dataElementsInTotalColumn = dataElementsByTotal.find(x => x.totalColumn === parentTotal?.code);
                const columnDataElements = dataElements.filter(de =>
                    dataElementsInTotalColumn?.dataElements.includes(de.code)
                );

                const orgUnitCode = dataFormInfo.orgUnit.code;
                const isDEDisabledFromToggleMultiple = isToggleMultipleDeDisabled(section, dataElement, orgUnitCode);

                return {
                    isVisible: column.isVisible,
                    column: column,
                    columnTotal: parentTotal,
                    columnDataElements: columnDataElements,
                    dataElement: dataElement,
                    disabled:
                        deCalculateTotal?.disabled || dataElement?.disabled || isDEDisabledFromToggleMultiple || false,
                    disableComments: section.disableComments || dataElement?.disabledComments || false,
                };
            });

            const itemsWithHtmlText = _(items)
                .map(item => item.dataElement?.htmlText)
                .compact()
                .value();

            const firstItemWithHtmlText = _(itemsWithHtmlText).first() || "";

            const lastPartSubSection = groupsByRow ? _(subsection.name).split(separator).last() ?? "" : undefined;
            const groupMeta = lastPartSubSection && groupsByRow ? groupsByRow[lastPartSubSection] : undefined;
            const rowName = groupsByRow ? lastPartSubSection ?? "" : subsection.name;

            const rowIndex = index + 1 + getNonDirectionalIndicatorsCountAtSectionStart(section);

            return {
                includePadding: 0,
                indicator: indicator,
                name: getIndexedLabel(section, dataFormInfo, rowName, rowIndex),
                htmlText: firstItemWithHtmlText
                    ? getIndexedLabel(section, dataFormInfo, firstItemWithHtmlText, rowIndex)
                    : "",
                items: items,
                group: groupMeta ? groupMeta.group : undefined,
                subGroup: groupMeta ? groupMeta.subGroup : undefined,
                indicators: {
                    before: getFilteredIndicators(section.indicators, items, "before"),
                    after: getFilteredIndicators(section.indicators, items, "after"),
                },
            };
        });
    }

    private static getSummary(
        dataFormInfo: DataFormInfo,
        section: SectionGrid,
        columns: Column[],
        viewType: SectionGrid["viewType"]
    ): Summary[] {
        const allDataElements = dataFormInfo.metadata.dataForm.sections.flatMap(section => section.dataElements);
        switch (viewType) {
            case "table":
                return _(section.totals)
                    .map((sectionTotal, key) => {
                        const selectedDataElements = allDataElements.filter(dataElement =>
                            sectionTotal.dataElementsCodes.includes(dataElement.code)
                        );

                        return {
                            cellName: key,
                            cells: [
                                {
                                    columnName: key,
                                    formula: sectionTotal.formulas?.[key]?.formula || sectionTotal.formula || "",
                                    items: this.getColumnWithDataElements(selectedDataElements, key),
                                    strict: sectionTotal.strict,
                                },
                            ],
                        };
                    })
                    .value();
            case "grid":
                return _(section.totals)
                    .map((sectionTotal, key) => {
                        const selectedDataElements = allDataElements.filter(dataElement =>
                            sectionTotal.dataElementsCodes.includes(dataElement.code)
                        );

                        const cellTotals = columns.map(column => {
                            const columnWithDataElements = GridViewModel.getColumnWithDataElements(
                                selectedDataElements,
                                column.name
                            );

                            return {
                                columnName: column.name,
                                formula: getFormulaByColumnName(section, column.name) || sectionTotal.formula || "",
                                items: columnWithDataElements,
                                strict: sectionTotal.strict,
                            };
                        });

                        return {
                            cellName: key,
                            cells: cellTotals,
                        };
                    })
                    .filter(summaryRow => summaryRow.cells.every(cell => cell.items.length > 0))
                    .value();
            default:
                console.warn(`Unsupported viewType ${viewType} in GridViewModel.getSummary`);
                return [];
        }
    }

    private static getIndicators(section: SectionGrid): Indicator[] {
        const indicatorsRelatedToDataElements = _(section.indicators)
            .map(indicator => (indicator.dataElement ? indicator.id : undefined))
            .compact()
            .value();

        return indicatorsRelatedToDataElements.length > 0
            ? section.indicators.filter(indicator => !indicatorsRelatedToDataElements.includes(indicator.id))
            : section.indicators;
    }

    private static buildRowGroups(rows: Row[]): RowGroup[] {
        const groupSeparator = "||";

        const rowsWithGroup = rows.filter(row => row.group && row.subGroup);
        if (rowsWithGroup.length === 0) return [];

        return _(rowsWithGroup)
            .groupBy(row => `${row.group}${groupSeparator}${row.subGroup}`)
            .toPairs()
            .map(([key, groupedRows]): Maybe<RowGroup> => {
                const [group, subGroup] = key.split(groupSeparator);
                if (!group || !subGroup) return undefined;
                return { group: group, subGroup: subGroup, rows: groupedRows };
            })
            .compact()
            .value();
    }

    private static groupsByRowName(
        dataElements: DataElement[]
    ): Record<string, { group: Maybe<string>; subGroup: Maybe<string> }> {
        return _(dataElements)
            .map(dataElement => this.parseNameParts(dataElement.name))
            .filter(group => Boolean(group.rowName))
            .keyBy(group => group.rowName)
            .mapValues(item => ({ group: item.group, subGroup: item.subGroup }))
            .value();
    }

    static getColumnWithDataElements(selectedDataElements: DataElement[], columnName: string): TotalItem[] {
        const hasInvalidDataElement = selectedDataElements.some(dataElement => {
            if (dataElement.type !== "NUMBER") return true;

            const categoryOptionCombo = getCategoryOptionComboByColumnName(dataElement);
            return categoryOptionCombo === undefined;
        });

        if (hasInvalidDataElement) return [];

        return _(selectedDataElements)
            .map((dataElement): Maybe<TotalItem> => {
                if (dataElement.type !== "NUMBER") return undefined;
                const categoryOptionCombo = getCategoryOptionComboByColumnName(dataElement);
                if (!categoryOptionCombo)
                    throw new Error(
                        `Cannot found categoryOptionCombo in column ${columnName} for dataElement ${dataElement.code}`
                    );

                return { dataElement, categoryOptionCombo };
            })
            .compact()
            .value();
    }

    private static scoreColumnByLowestDEPriority({
        columnName,
        allDataElements,
        priorityByCode,
    }: ColumnScoreInput): number {
        const candidates = allDataElements.filter(de => {
            const last = _.last(_.split(de.name, separator));
            return last === columnName;
        });

        const scores = candidates.map(de => priorityByCode[de.code]);

        return scores.length > 0 ? (_.min(scores) as number) : Number.MAX_SAFE_INTEGER;
    }

    private static parseNameParts(fullName: string): RowNameParts {
        // Supported Pattern
        //  - [Row, Column]
        //  - [Group, SubGroup, Row, Column]

        const parts = _(fullName)
            .split(separator)
            .map(s => s.trim())
            .value();

        if (parts.length === 4) {
            const [group, subGroup, rowName, columnName] = parts;
            return { group, subGroup: subGroup, rowName: rowName ?? "", columnName: columnName ?? "" };
        }

        if (parts.length === 2) {
            const [rowName, columnName] = parts;
            return { rowName: rowName ?? "", columnName: columnName ?? "", group: undefined, subGroup: undefined };
        }

        // Fallback to original pattern [Row - Column]
        const rowName = parts.join(separator).trim();
        return { rowName, columnName: "", group: undefined, subGroup: undefined };
    }

    private static buildGroupInfo(rows: Row[], propertyName: "group" | "subGroup"): Record<Row["name"], GroupInfo> {
        const grouped = _(rows)
            .groupBy(row => row[propertyName])
            .value();

        const spanByProperty = _(rows)
            .groupBy(row => row[propertyName])
            .map((item, key) => {
                return [key, item.length];
            })
            .fromPairs()
            .value();

        return _(grouped)
            .mapValues((items): GroupInfo => {
                const first = items[0];
                const groupName = first[propertyName] ?? "";
                return {
                    rowSpan: spanByProperty[groupName] ?? 0,
                    rowName: first.name,
                };
            })
            .value();
    }

    private static addVisibleToColumns(options: {
        section: SectionGrid;
        columns: Column[];
        dataFormInfo: DataFormInfo;
    }): Column[] {
        const { section, columns, dataFormInfo } = options;
        if (!section.columnsConfig) return columns;

        return _(columns)
            .map(column => {
                const config = section.columnsConfig ? section.columnsConfig[column.code] : undefined;
                if (!config) return { ...column, isVisible: true };

                const dataElementCodes = _(config.rules?.visible?.dataElements)
                    .map(dataElement => dataElement.code)
                    .compact()
                    .value();

                const value = calculateFormula({
                    dataElementCodes: dataElementCodes,
                    dataFormInfo,
                    formula: config.rules?.visible?.formula.value ?? "",
                    period: dataFormInfo.period,
                });

                return { ...column, isVisible: value === config.rules?.visible?.formula.condition };
            })
            .value();
    }
}

type GroupInfo = {
    rowSpan: number;
    rowName: string;
};

export function getDataElementLabel(
    section: SectionBase,
    dataFormInfo: DataFormInfo,
    dataElement: DataElement,
    name: string
): string {
    const deIndex = section.dataElements.findIndex(de => dataElement.id === de.id) + 1;
    return getIndexedLabel(
        section,
        dataFormInfo,
        name,
        deIndex + getNonDirectionalIndicatorsCountAtSectionStart(section)
    );
}

/** Move the data element index to the row name, so indexed data elements are automatically grouped 

    Input:
        MAL - Compound name (1)
        MAL - Compound name (2)
        MAL - Compound symbol (1)
        MAL - Compound symbol (2)

    Output:
        MAL (1) - Compound name
        MAL (2) - Compound name
        MAL (1) - Compound symbol
        MAL (2) - Compound symbol
*/

function getDataElementsWithIndexProccessing(section: Section) {
    return section.dataElements.map((dataElement): typeof dataElement => {
        // "MAL - Compound name (1)" -> "MAL (1) - Compound name"
        const index = dataElement.name.match(/\((\d+)\)$/)?.[1];

        if (!index) {
            return dataElement;
        } else {
            const parts = dataElement.name.split(separator);
            const initial = _.initial(parts).join(separator);
            const last = _.last(parts);
            if (!last) return dataElement;
            const lastWithoutIndex = last.replace(/\s*\(\d+\)$/, "");
            const newName = `${initial} (${index}) - ${lastWithoutIndex}`;
            return { ...dataElement, name: newName };
        }
    });
}

function getSubsectionName(dataElement: DataElement): string {
    // Remove index from enumerated data elements (example: `Chemical name (1)` -> `Chemical name`)
    // so they are grouped with no need to edit each name in the metadata.
    return _(dataElement.name).split(separator).initial().join(separator);
}

export function isSourceTypeColumn(widget: Maybe<DataElementWidget>): boolean {
    return widget === "sourceType";
}

export function getCategoryOptionComboByColumnName(dataElement: DataElementNumber) {
    return dataElement.categoryOptionCombos[0];
}

function getFilteredIndicators(
    indicators: Indicator[],
    items: Row["items"],
    direction: IndicatorDirection
): Indicator[] {
    return indicators.filter(indicator => {
        return (
            items.map(item => item.dataElement?.code).includes(indicator.dataElement?.code) &&
            checkIndicatorDirection(indicator, direction)
        );
    });
}
