import _ from "lodash";
import { Section, SectionWithCategoryColumns, Texts } from "../../../domain/common/entities/DataForm";
import { DataElement } from "../../../domain/common/entities/DataElement";
import { makeCocOrderArray } from "../../../data/common/Dhis2DataElement";
import { Maybe } from "../../../utils/ts-utils";
import { DataFormInfo } from "./AutogeneratedForm";

export interface Grid {
    id: string;
    name: string;
    columns: Column[];
    rows: Row[];
    toggle: Section["toggle"];
    toggleMultiple: Section["toggleMultiple"];
    useIndexes: boolean;
    texts: Texts;
    parentColumns: ParentColumn[];
    calculateTotals: number[];
}

interface Column {
    name: string;
    deName?: string;
    cocName?: string;
    categories?: string[];
    totalCategories: number;
    parentColumnName?: string;
}

interface Row {
    id: string;
    name: string;
    cellsVisible: boolean;
    items: Array<{ dataElement: Maybe<DataElement> }>;
}

type ParentColumn = {
    name: string;
    colSpan: number;
};

const separator = " - ";

export class GridWithCategoryColumnsViewModel {
    static get(section: SectionWithCategoryColumns, dataFormInfo: DataFormInfo): Grid {
        const { parentColumns, columns } = this.getColumns(section);
        const rows = this.buildRows(section);

        return {
            id: section.id,
            name: section.name,
            columns: columns,
            rows: rows,
            toggle: section.toggle,
            texts: section.texts,
            useIndexes: false,
            parentColumns: parentColumns.length === columns.length ? [] : parentColumns,
            toggleMultiple: section.toggleMultiple,
            calculateTotals: this.calculateTotals(rows, dataFormInfo),
        };
    }

    private static getColumns(section: SectionWithCategoryColumns): {
        columns: Column[];
        parentColumns: ParentColumn[];
    } {
        const columns = section.dataElements.map((dataElement): Column => {
            const category = this.categoryColumn(dataElement, section.categoriesColumns);

            const columnName = _(dataElement.name).split(separator).last() || "";
            const parentColumnName = _(dataElement.name).split(separator).first() || "";

            return {
                name: columnName,
                deName: "",
                cocName: "",
                parentColumnName: parentColumnName,
                categories: category?.categoryOptions.map(c => c.name) ?? [],
                totalCategories: category?.categoryOptions.length || 0,
            };
        });

        const parentColumns = _(columns)
            .groupBy(column => column.parentColumnName)
            .map((group, name) => {
                return {
                    name: name,
                    colSpan: _.sumBy(group, c => c.totalCategories || 1),
                };
            })
            .value();

        return { columns: columns, parentColumns: parentColumns };
    }

    private static buildRows(section: SectionWithCategoryColumns): Row[] {
        const { dataElements, categoriesColumns } = section;
        const items = dataElements.flatMap(dataElement => {
            const allOptions = _(dataElement.categoryCombos.categories)
                .flatMap(c => c.categoryOptions.flatMap(co => co))
                .keyBy(x => x.name)
                .value();

            const category = this.categoryColumn(dataElement, categoriesColumns);
            // Options for the category used for columns
            const columnOptions = category?.categoryOptions.map(co => co.name) ?? [];

            // Other categories without the one used for columns
            const restCategories = _(dataElement.categoryCombos.categories)
                .filter(c => c.code !== category?.code)
                .value();

            const restCategoryOptions = restCategories.map(c => c.categoryOptions.flatMap(co => co.name));
            const combinations = restCategoryOptions.length > 0 ? makeCocOrderArray(restCategoryOptions) : [];
            if (combinations.length === 0) return [];

            const dataElementsWithCocId = columnOptions.flatMap(columnOption => {
                const columnOptionCode = allOptions[columnOption]?.code;

                return combinations.map(combination => {
                    const combinationOptionCode = allOptions[combination]?.code;
                    const cocName = [columnOption].concat(combination).join(", ");
                    const cocDetails = dataElement.categoryCombos.categoryOptionCombos.find(
                        coc => coc.name === cocName
                    );

                    if (!cocDetails) {
                        console.warn(
                            `Category option combo with name ${cocName} not found for data element ${dataElement.name}`
                        );
                    }

                    return {
                        ...dataElement,
                        cocId: cocDetails?.id,
                        fullName: dataElement.name,
                        cocName: combination,
                        disabled: !cocDetails,
                        cocCodes: _([columnOptionCode, combinationOptionCode]).compact().value(),
                    };
                });
            });
            return dataElementsWithCocId;
        });

        return _(items)
            .groupBy(item => item.cocName)
            .map((group, name): Row => {
                const id = _(group)
                    .flatMap(x => x.cocCodes)
                    .uniq()
                    .join("-");

                const rowConfig = section.rowsConfig?.[id];

                return {
                    id: id,
                    name,
                    cellsVisible: rowConfig?.cellsVisible ?? true,
                    items: group.map(de => ({ dataElement: de })),
                };
            })
            .value();
    }

    private static categoryColumn(
        dataElement: DataElement,
        categoriesColumnsConfig: SectionWithCategoryColumns["categoriesColumns"]
    ) {
        const categoryColumnConfig = categoriesColumnsConfig.find(
            config => config.dataElementCode === dataElement.code
        );

        return (
            dataElement.categoryCombos.categories.find(
                category => category.code === categoryColumnConfig?.categoryCode
            ) ?? dataElement.categoryCombos.categories[0]
        );
    }

    private static calculateTotals(rows: Row[], dataFormInfo: DataFormInfo): number[] {
        const firstRow = rows[0];
        if (!firstRow) return [];

        const columnCount = firstRow.items.length;

        return Array.from({ length: columnCount }, (_value, colIndex) => {
            const columnValues = rows.map(row =>
                this.getDataElementValue(row.items[colIndex]?.dataElement, dataFormInfo)
            );

            if (columnValues.length > 0) {
                const firstValue = this.getDataElementValue(firstRow.items[colIndex]?.dataElement, dataFormInfo);
                return firstValue ?? _(columnValues).sum();
            }
            return 0;
        });
    }

    private static getDataElementValue(dataElement: Maybe<DataElement>, dataFormInfo: DataFormInfo): Maybe<number> {
        if (!dataElement) return 0;

        const dataValue = dataFormInfo.data.values.get(dataElement, {
            categoryOptionComboId: dataElement.cocId ?? dataFormInfo.categoryOptionComboId,
            orgUnitId: dataFormInfo.orgUnitId,
            period: dataFormInfo.period,
        });

        if (dataValue?.type !== "NUMBER" || dataValue.isMultiple) return 0;

        return dataValue.value ? Number(dataValue.value) : undefined;
    }

    private static sortRows = (rows: Row[], sortField: "name"): Row[] => {
        return _.sortBy(rows, [group => !this.isLetter(group[sortField]), group => group[sortField].toLowerCase()]);
    };

    private static isLetter = (value: string): boolean => {
        return /^[a-zA-Z]/.test(value);
    };
}
