import { SectionBase } from "../../../domain/common/entities/DataForm";
import { Indicator } from "../../../domain/common/entities/Indicator";
import { DataFormInfo } from "./AutogeneratedForm";
import { getIndexedLabel } from "./DataTableSection";

export function getIndexedIndicator(
    section: SectionBase,
    dataFormInfo: DataFormInfo,
    indicator: Indicator,
    indicatorIndex?: number
): Indicator {
    const dataElementIndex = indicator.dataElement
        ? section.dataElements.findIndex(de => de.code === indicator.dataElement?.code)
        : -1;
    const indexedPosition =
        typeof indicatorIndex === "number"
            ? indicatorIndex
            : dataElementIndex >= 0
            ? dataElementIndex + 1
            : undefined;

    return {
        ...indicator,
        name: getIndexedLabel(section, dataFormInfo, indicator.name, indexedPosition),
        description: indicator.description
            ? getIndexedLabel(section, dataFormInfo, indicator.description, indexedPosition)
            : indicator.description,
    };
}
