import React, { useEffect, useRef, useState } from "react";
import { Tabs, Tab, Box, makeStyles } from "@material-ui/core";
import {
    Section,
    SectionWithPeriods,
    ViewType,
    SectionWithTotals,
    SectionWithSubnationals,
    SectionSimple,
    SectionGrid,
} from "../../../domain/common/entities/DataForm";
import TableForm from "./TableForm";
import GridForm from "./GridForm";
import GridWithPeriods from "./GridWithPeriods";
import GridWithTotals from "./GridWithTotals";
import { assertUnreachable } from "../../../utils/ts-utils";
import { DataFormInfo } from "./AutogeneratedForm";
import GridWithCombos from "./GridWithCombos";
import GridWithSubNational from "./GridWithSubNational";
import GridWithCatOptionCombos from "./GridWithCatOptionCombos";
import MatrixGridForm from "./MatrixGridForm";
import AppBar from "@material-ui/core/AppBar";
import styled from "styled-components";

export interface TabPanelProps {
    sections: Section[];
    dataFormInfo: DataFormInfo;
}

interface TabProps {
    section: Section;
    dataFormInfo: DataFormInfo;
    value: number;
}

interface TypeSwitchProps {
    section: Section;
    dataFormInfo: DataFormInfo;
    viewType: ViewType;
}

function TypeSwitch(props: TypeSwitchProps) {
    const { section, dataFormInfo, viewType } = props;

    switch (viewType) {
        case "table":
            return <TableForm key={`${section.id}+tab`} dataFormInfo={dataFormInfo} section={section as SectionGrid} />;
        case "grid":
            return <GridForm key={`${section.id}+tab`} dataFormInfo={dataFormInfo} section={section as SectionGrid} />;
        case "grid-with-periods":
            return (
                <GridWithPeriods
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithPeriods}
                />
            );
        case "grid-with-totals":
            return (
                <GridWithTotals
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithTotals}
                />
            );
        case "grid-with-combos":
            return <GridWithCombos key={`${section.id}+tab`} dataFormInfo={dataFormInfo} section={section} />;
        case "grid-with-cat-option-combos":
            return (
                <GridWithCatOptionCombos
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionSimple}
                />
            );
        case "matrix-grid":
            return (
                <MatrixGridForm
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionSimple}
                />
            );
        case "grid-with-subnational-ous":
            return (
                <GridWithSubNational
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithSubnationals}
                />
            );
        default:
            assertUnreachable(viewType);
    }
}

function isTabHeader(order: number | undefined) {
    if (order === undefined) return false;
    if (order % 1 === 0) return true;

    if (order === Math.floor(order) + 0.1) {
        return true;
    }
}

const AutoFormComponent = React.memo(TypeSwitch);

const TabPanel: React.FC<TabProps> = React.memo(props => {
    const { section, dataFormInfo, value } = props;
    const { viewType, tabs } = section;
    const index = tabs.order !== undefined ? Math.floor(tabs.order) : -1;

    return (
        <div role="tabpanel" hidden={value !== index} id={`tabpanel-${index}`} aria-labelledby={`tab-${index}`}>
            <AutoFormComponent dataFormInfo={dataFormInfo} section={section} viewType={viewType} />
        </div>
    );
});

const SectionsTabs: React.FC<TabPanelProps> = React.memo(props => {
    const { sections, dataFormInfo } = props;

    const [activeTab, setActiveTab] = useState(0);
    const [showLeftFade, setShowLeftFade] = useState(false);
    const [showRightFade, setShowRightFade] = useState(true);

    const classes = useStyles();
    const tabsRef = useRef<HTMLButtonElement>(null);

    const handleChange = (_event: React.ChangeEvent<{}>, value: number) => {
        setActiveTab(value);
    };

    useEffect(() => {
        const tabContainer = document.querySelector(".MuiTabs-scroller.MuiTabs-scrollable") as HTMLDivElement | null;
        const scrollButtons = document.querySelectorAll(".MuiTabs-scrollButtons");

        if (!tabContainer) return;

        const updateFadeVisibility = () => {
            const { scrollLeft, scrollWidth, clientWidth } = tabContainer;
            const scrollRight = scrollWidth - clientWidth - scrollLeft;

            setShowLeftFade(scrollLeft > 0);
            setShowRightFade(scrollRight > 0);
        };

        tabContainer.addEventListener("scroll", updateFadeVisibility);
        updateFadeVisibility();

        const handleScrollButtonClick = () => {
            setTimeout(updateFadeVisibility, 100);
        };

        scrollButtons.forEach(button => {
            button.addEventListener("click", handleScrollButtonClick);
        });

        return () => {
            tabContainer.removeEventListener("scroll", updateFadeVisibility);
            scrollButtons.forEach(button => {
                button.removeEventListener("click", handleScrollButtonClick);
            });
        };
    }, []);

    return (
        <Box sx={{ width: "100%" }}>
            <StyledAppBar position="sticky" color="default">
                <StyledTabs
                    ref={tabsRef}
                    value={activeTab}
                    onChange={handleChange}
                    indicatorColor="primary"
                    textColor="primary"
                    variant="scrollable"
                    scrollButtons="on"
                    TabScrollButtonProps={{
                        style: { zIndex: 10 },
                    }}
                    className={classes.scrollButtons}
                >
                    {sections.flatMap(section => {
                        const order = section.tabs.order;
                        if (isTabHeader(order)) {
                            return (
                                <Tab
                                    key={section.id + "Tab"}
                                    label={section.name}
                                    id={`tab-${order}`}
                                    aria-controls={`tabpanel-${order}`}
                                />
                            );
                        } else {
                            return [];
                        }
                    })}
                </StyledTabs>

                <FadedOverlay showLeftFade={showLeftFade} />
                <FadedOverlay showRightFade={showRightFade} />
            </StyledAppBar>
            {sections.map(section => {
                return (
                    <TabPanel
                        key={section.id + "TabPanel"}
                        value={activeTab}
                        dataFormInfo={dataFormInfo}
                        section={section}
                    />
                );
            })}
        </Box>
    );
});

const useStyles = makeStyles({
    scrollButtons: {
        "& svg": {
            fontSize: "3rem",
        },
    },
});

export default React.memo(SectionsTabs);

const StyledAppBar = styled(AppBar)`
    top: 48px !important;
    z-index: 100 !important;
`;

const StyledTabs = styled(Tabs)`
    position: relative;
`;

const FadedOverlay = styled.div<{ showLeftFade?: boolean; showRightFade?: boolean }>`
    position: absolute;
    top: 0;
    left: ${props => (props.showLeftFade ? 0 : "auto")};
    right: ${props => (props.showRightFade ? 0 : "auto")};
    transform: ${props => (props.showLeftFade ? "rotate(180deg)" : "none")};
    width: 25%;
    height: 100%;
    background: linear-gradient(to left, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0));
    pointer-events: none;
    transition: opacity 0.3s ease-in-out;
    opacity: ${props => (!props.showLeftFade && !props.showRightFade ? 0 : 1)};
`;
