import _ from "lodash";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Tabs, Tab, Box, makeStyles } from "@material-ui/core";
import {
    Section,
    SectionWithPeriods,
    ViewType,
    SectionWithTotals,
    SectionWithSubnationals,
    SectionSimple,
    SectionDisaggregatedCocs,
    SectionGrid,
    SectionWithIndicatorsCalculated,
    SectionWithCategoryColumns,
} from "../../../domain/common/entities/DataForm";
import TableForm from "./TableForm";
import GridForm from "./GridForm";
import GridWithPeriods from "./GridWithPeriods";
import GridWithTotals from "./GridWithTotals";
import { assertUnreachable, Maybe } from "../../../utils/ts-utils";
import { DataFormInfo } from "./AutogeneratedForm";
import GridWithCombos from "./GridWithCombos";
import GridWithSubNational from "./GridWithSubNational";
import GridWithCatOptionCombos from "./GridWithCatOptionCombos";
import MatrixGridForm from "./MatrixGridForm";
import AppBar from "@material-ui/core/AppBar";
import styled from "styled-components";
import { IconButton } from "material-ui";
import { ChevronLeft, ChevronRight } from "@material-ui/icons";
import DisaggregatedCOCsGrid from "./DisaggregatedCOCsGrid";
import GridIndicatorsCalculated from "./GridIndicatorsCalculated";
import { calculateFormula } from "./datatables/InputFormula";
import GridWithCategoryColumns from "./GridWithCategoryColumns";
import { useTabVisibility } from "./hooks/useTabVisibility";
import { DebugLabel } from "../../components/debug/DebugLabel";

export interface TabPanelProps {
    tabbedSections: Section[];
    untabbedSections: Section[];
    dataFormInfo: DataFormInfo;
}

interface TabProps {
    section: Section;
    dataFormInfo: DataFormInfo;
    value: number;
}

interface TypeSwitchProps {
    section: Section;
    dataFormInfo: DataFormInfo;
    viewType: ViewType;
}

type TabScrollButtonDirection = "left" | "right";

type ScrollButtonProps = {
    direction: TabScrollButtonDirection;
    showLeftFade: boolean;
    showRightFade: boolean;
    handleScroll: (direction: TabScrollButtonDirection) => void;
};

function TypeSwitch(props: TypeSwitchProps) {
    const { section, dataFormInfo, viewType } = props;

    switch (viewType) {
        case "table":
            return <TableForm key={`${section.id}+tab`} dataFormInfo={dataFormInfo} section={section as SectionGrid} />;
        case "grid":
            return <GridForm key={`${section.id}+tab`} dataFormInfo={dataFormInfo} section={section as SectionGrid} />;
        case "grid-with-periods":
            return (
                <GridWithPeriods
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithPeriods}
                />
            );
        case "grid-with-totals":
            return (
                <GridWithTotals
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithTotals}
                />
            );
        case "grid-with-combos":
            return <GridWithCombos key={`${section.id}+tab`} dataFormInfo={dataFormInfo} section={section} />;
        case "grid-with-cat-option-combos":
            return (
                <GridWithCatOptionCombos
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithPeriods}
                />
            );
        case "grid-disaggregated-cocs":
            return (
                <DisaggregatedCOCsGrid
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionDisaggregatedCocs}
                />
            );

        case "matrix-grid":
            return (
                <MatrixGridForm
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionSimple}
                />
            );
        case "grid-with-subnational-ous":
            return (
                <GridWithSubNational
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithSubnationals}
                />
            );
        case "grid-indicators-calculated":
            return (
                <GridIndicatorsCalculated
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithIndicatorsCalculated}
                />
            );
        case "grid-category-columns":
            return (
                <GridWithCategoryColumns
                    key={`${section.id}+tab`}
                    dataFormInfo={dataFormInfo}
                    section={section as SectionWithCategoryColumns}
                />
            );
        default:
            assertUnreachable(viewType);
    }
}

// Default tab indices: -1 means no primary tab, 0 means first secondary tab
const DEFAULT_PRIMARY_TAB_INDEX = "-1";
const DEFAULT_SECONDARY_TAB_INDEX = "0";

export function getTabIndices(
    order: Maybe<string>,
    allSections?: {
        tabs: { order?: string };
        showIndex: boolean;
    }[],
    showIndex = false
): [number, number] {
    const [primaryTabIndex, secondaryTabIndex] = order ? order.split(".") : ["", ""];
    const currentPrimary = parseInt(primaryTabIndex ?? DEFAULT_PRIMARY_TAB_INDEX);
    const currentSecondary = parseInt(secondaryTabIndex ?? DEFAULT_SECONDARY_TAB_INDEX);

    if (!allSections || !showIndex) {
        return [currentPrimary, currentSecondary];
    }

    if (currentPrimary === -1) {
        return [-1, currentSecondary];
    }

    const visibleSections = allSections.filter(
        (s): s is typeof s & { tabs: { order: string } } => s.showIndex && !!s.tabs.order
    );

    const adjustedPrimary = _(visibleSections)
        .map(s => parseInt(s.tabs.order.split(".")[0] ?? "-1"))
        .filter(primary => primary !== -1 && primary < currentPrimary)
        .uniq()
        .value().length;

    const adjustedSecondary = visibleSections
        .map(s => {
            const [p, sec] = s.tabs.order.split(".");
            return [parseInt(p ?? "-1"), parseInt(sec ?? "0")] as const;
        })
        .filter(([primary, secondary]) => primary === currentPrimary && secondary < currentSecondary).length;

    return [adjustedPrimary, adjustedSecondary];
}

function isTabHeader(order: Maybe<string>) {
    const [_, secondaryTabIndex] = getTabIndices(order);
    return isNaN(secondaryTabIndex) || secondaryTabIndex === 0 || secondaryTabIndex === 1;
}

function tabHeaderShouldShowIndex(section: Section, sections: Section[]): boolean {
    if (section.showIndex) return true;
    if (!section.tabs.order) return false;

    const [rawPrimaryIndex] = getTabIndices(section.tabs.order);
    const hasSiblingsWithShowIndex = sections.some(s => {
        const siblingOrder = s.tabs.order;
        if (!siblingOrder) return false;
        const [siblingPrimaryIndex] = getTabIndices(siblingOrder);
        return siblingPrimaryIndex === rawPrimaryIndex && s.showIndex;
    });

    return hasSiblingsWithShowIndex;
}

const AutoFormComponent = React.memo(TypeSwitch);

const TabPanel: React.FC<TabProps> = React.memo(props => {
    const { section, dataFormInfo, value } = props;
    const { viewType, tabs } = section;
    const [index, _] = getTabIndices(tabs.order);

    return (
        <div role="tabpanel" hidden={value !== index} id={`tabpanel-${index}`} aria-labelledby={`tab-${index}`}>
            <DebugLabel>
                {section.code} - {section.viewType}
            </DebugLabel>
            <AutoFormComponent dataFormInfo={dataFormInfo} section={section} viewType={viewType} />
        </div>
    );
});

const ScrollButton: React.FC<ScrollButtonProps> = React.memo(props => {
    const { direction, showLeftFade, showRightFade, handleScroll } = props;
    const classes = useStyles();

    return (
        <StyledIconButton
            style={{ position: "absolute", height: "max-content", width: "max-content" }}
            direction={direction}
            showLeftFade={showLeftFade}
            showRightFade={showRightFade}
            onClick={() => handleScroll(direction)}
        >
            {direction === "right" && <ChevronRight className={classes.scrollIcon} />}
            {direction === "left" && <ChevronLeft className={classes.scrollIcon} />}
        </StyledIconButton>
    );
});

const SectionsTabs: React.FC<TabPanelProps> = React.memo(props => {
    const { dataFormInfo, tabbedSections, untabbedSections } = props;

    const [activeTab, setActiveTab] = useState(0);
    const [showLeftFade, setShowLeftFade] = useState(false);
    const [showRightFade, setShowRightFade] = useState(true);
    const { tabVisibilityByIndex, firstVisibleTabIndex } = useTabVisibility(props);

    const handleChange = (_event: React.ChangeEvent<{}>, value: number) => {
        if (value === -1 || tabVisibilityByIndex[value]) {
            setActiveTab(value);
            return;
        }
        if (firstVisibleTabIndex !== undefined) {
            setActiveTab(firstVisibleTabIndex);
        }
    };

    const allSections = useMemo(() => [...tabbedSections, ...untabbedSections], [tabbedSections, untabbedSections]);
    const tabHeaders = useMemo(
        () =>
            tabbedSections.flatMap(section => {
                const order = section.tabs.order;
                if (!isTabHeader(order)) return [];

                const [primaryTabIndex] = getTabIndices(section.tabs.order, allSections, section.showIndex);
                const sectionTabLabel = section.texts.tabLabel || section.name;
                const shouldShowIndex = tabHeaderShouldShowIndex(section, allSections);
                const tabLabel =
                    shouldShowIndex && primaryTabIndex !== -1
                        ? `${primaryTabIndex + 1} - ${sectionTabLabel}`
                        : sectionTabLabel;

                const visibleRule = section.tabs.rules?.visible;
                const dataElementCodes = visibleRule?.dataElements.map(de => de.code) || [];
                const value =
                    visibleRule && dataElementCodes.length > 0
                        ? calculateFormula({
                              dataElementCodes,
                              dataFormInfo,
                              formula: visibleRule.formula.value,
                          })
                        : undefined;

                if (visibleRule && value !== visibleRule.formula.condition) return [];

                const primaryValue = _(order).split(".").first() ?? "0";
                const primaryIndex = Number(primaryValue);

                return [{ key: section.id, order, label: tabLabel, primaryIndex }];
            }),
        [allSections, dataFormInfo, tabbedSections]
    );
    const printTabHeaders = useMemo(() => _.uniqBy(tabHeaders, "primaryIndex"), [tabHeaders]);

    const tabContainer = document.querySelector(".MuiTabs-scroller.MuiTabs-scrollable");
    const handleScroll = useCallback(
        (direction: TabScrollButtonDirection) => {
            const scrollOffset = direction === "left" ? -500 : direction === "right" ? 500 : undefined;

            return tabContainer?.scrollBy({
                left: scrollOffset,
                behavior: "smooth",
            });
        },
        [tabContainer]
    );

    useEffect(() => {
        if (firstVisibleTabIndex === undefined) return;
        if (activeTab === -1) return;
        if (!tabVisibilityByIndex[activeTab]) {
            setActiveTab(firstVisibleTabIndex);
        }
    }, [activeTab, tabVisibilityByIndex, firstVisibleTabIndex]);

    useEffect(() => {
        const scrollButtons = document.querySelectorAll(".MuiTabs-scrollButtons");
        if (!tabContainer) return;

        const updateFadeVisibility = () => {
            const { scrollLeft, scrollWidth, clientWidth } = tabContainer;
            const scrollRight = scrollWidth - clientWidth - scrollLeft;

            setShowLeftFade(scrollLeft > 0);
            setShowRightFade(scrollRight > 10);
        };

        tabContainer.addEventListener("scroll", updateFadeVisibility);
        updateFadeVisibility();

        const handleScrollButtonClick = () => {
            setTimeout(updateFadeVisibility, 100);
        };

        scrollButtons.forEach(button => {
            button.addEventListener("click", handleScrollButtonClick);
        });

        return () => {
            tabContainer.removeEventListener("scroll", updateFadeVisibility);
            scrollButtons.forEach(button => {
                button.removeEventListener("click", handleScrollButtonClick);
            });
        };
    }, [tabContainer]);

    return (
        <Box sx={{ width: "100%" }}>
            <ScreenOnlyContent>
                <StyledAppBar position="sticky" color="default">
                    <ScrollButton
                        direction="left"
                        showLeftFade={showLeftFade}
                        showRightFade={showRightFade}
                        handleScroll={handleScroll}
                    />
                    <ScrollButton
                        direction="right"
                        showLeftFade={showLeftFade}
                        showRightFade={showRightFade}
                        handleScroll={handleScroll}
                    />
                    <StyledTabs
                        value={activeTab}
                        onChange={handleChange}
                        indicatorColor="primary"
                        textColor="primary"
                        variant="scrollable"
                        scrollButtons="auto"
                        TabScrollButtonProps={{ style: { opacity: 0 } }}
                    >
                        {tabHeaders.map(tabHeader => (
                            <Tab
                                key={tabHeader.key + "Tab"}
                                label={tabHeader.label}
                                id={`tab-${tabHeader.order}`}
                                aria-controls={`tabpanel-${tabHeader.order}`}
                                value={tabHeader.primaryIndex}
                            />
                        ))}
                        {untabbedSections.length > 0 && (
                            <Tab
                                key="others-tab"
                                label="Others"
                                id="tab-others"
                                aria-controls="tabpanel-others"
                                value={-1}
                            />
                        )}
                    </StyledTabs>

                    <FadedOverlay hidden={!showLeftFade} style={{ insetInlineStart: 0, transform: "rotate(180deg)" }} />
                    <FadedOverlay hidden={!showRightFade} style={{ insetInlineEnd: 0 }} />
                </StyledAppBar>
                {tabbedSections.map(section => (
                    <TabPanel
                        key={section.id + "TabPanel"}
                        value={activeTab}
                        dataFormInfo={dataFormInfo}
                        section={section}
                    />
                ))}
                <div role="tabpanel" hidden={activeTab !== -1} id="tabpanel-others" aria-labelledby="tab-others">
                    {untabbedSections.map(section => (
                        <React.Fragment key={section.id + "UntabbedSection"}>
                            <DebugLabel>{section.code}</DebugLabel>
                            <AutoFormComponent
                                dataFormInfo={dataFormInfo}
                                section={section}
                                viewType={section.viewType}
                            />
                        </React.Fragment>
                    ))}
                </div>
            </ScreenOnlyContent>

            <PrintOnlyContent>
                {printTabHeaders.map(tabHeader => {
                    const sectionsByTab = tabbedSections.filter(section => {
                        const [primaryTabIndex] = getTabIndices(section.tabs.order);
                        return primaryTabIndex === tabHeader.primaryIndex;
                    });

                    return (
                        <div key={`print-tab-${tabHeader.primaryIndex}`}>
                            <PrintTabLabel>{tabHeader.label}</PrintTabLabel>
                            {sectionsByTab.map(section => (
                                <React.Fragment key={section.id + "PrintSection"}>
                                    <DebugLabel>{section.code}</DebugLabel>
                                    <AutoFormComponent
                                        dataFormInfo={dataFormInfo}
                                        section={section}
                                        viewType={section.viewType}
                                    />
                                </React.Fragment>
                            ))}
                        </div>
                    );
                })}

                {untabbedSections.length > 0 && (
                    <div>
                        <PrintTabLabel>Others</PrintTabLabel>
                        {untabbedSections.map(section => (
                            <React.Fragment key={section.id + "PrintUntabbedSection"}>
                                <DebugLabel>{section.code}</DebugLabel>
                                <AutoFormComponent
                                    dataFormInfo={dataFormInfo}
                                    section={section}
                                    viewType={section.viewType}
                                />
                            </React.Fragment>
                        ))}
                    </div>
                )}
            </PrintOnlyContent>
        </Box>
    );
});

export default React.memo(SectionsTabs);

const useStyles = makeStyles({
    scrollIcon: {
        fontSize: "3rem",
    },
});

const StyledAppBar = styled(AppBar)`
    z-index: 100 !important;
`;

const ScreenOnlyContent = styled.div`
    @media print {
        display: none;
    }
`;

const PrintOnlyContent = styled.div`
    display: none;
    @media print {
        display: block;
    }
`;

const PrintTabLabel = styled.h3`
    margin: 1.5rem 0 0.75rem 0;
    padding: 0.75rem 1rem;
    background: #ffffff;
    font-size: 1rem;
    font-weight: 700;
    line-height: 1.25;
    text-transform: uppercase;
    letter-spacing: 0.02857em;
    page-break-after: avoid;
`;

const StyledTabs = styled(Tabs)`
    position: relative;
`;

const FadedOverlay = styled.div<{ hidden?: boolean }>`
    position: absolute;
    inset-block-start: 0;
    width: 25%;
    height: 100%;
    background: linear-gradient(to left, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0));
    pointer-events: none;
    transition: opacity 0.5s ease-in-out;
    opacity: ${props => (props.hidden ? 0 : 1)};
`;

const StyledIconButton = styled(IconButton).withConfig({
    shouldForwardProp: prop => !["showLeftFade", "showRightFade", "direction"].includes(prop),
})<Omit<ScrollButtonProps, "handleScroll">>`
    opacity: ${props =>
        (!props.showLeftFade && props.direction === "left") || (!props.showRightFade && props.direction === "right")
            ? 0.5
            : undefined};
    inset-inline-start: ${props => (props.direction === "left" ? "-1rem" : undefined)};
    inset-inline-end: ${props => (props.direction === "right" ? "1rem" : undefined)};
    inset-block-end: -0.6rem;
    z-index: 10;
    color: inherit;
`;
